In [1]:
import pandas as pd
import re
import numpy as np

In [2]:
df = pd.read_csv('data_translate.csv')
df.head()

,Unnamed: 0.1,Unnamed: 0,title,role,company_name,category,location,jobId,type,benefit,salary,url,description,title_translated,description_translated,category_translated,role_translated
0,0,0,Penerjemah Bahasa Mandarin，Asisten Manajer Umum,Mandarin-Translator,PT ONEMATE AKSESORIS MOBIL,"Administrasi & Dukungan Perkantoran, Asisten A...","Tangerang, Banten",79976110,Full time,NaN,Rp 8.500.000 – Rp 12.500.000 per month,https://id.jobstreet.com/job/79976110,Asisten Manajer Umum: • Membantu manajer umum ...,Penerjemah Bahasa Mandarin，Asisten Manajer Umum,Asisten Manajer Umum: • Membantu manajer umum ...,"Administrasi & Dukungan Perkantoran, Asisten A...",Mandarin-Translator
1,1,1,Penerjemah Bahasa Mandarin，Asisten Manajer Umum,Mandarin-Translator,PT ONEMATE AKSESORIS MOBIL,"Administrasi & Dukungan Perkantoran, Asisten A...","Tangerang, Banten",79976110,Full time,NaN,Rp 8.500.000 – Rp 12.500.000 per month,https://id.jobstreet.com/job/79976110,Asisten Manajer Umum: • Membantu manajer umum ...,Penerjemah Bahasa Mandarin，Asisten Manajer Umum,Asisten Manajer Umum: • Membantu manajer umum ...,"Administrasi & Dukungan Perkantoran, Asisten A...",Mandarin-Translator
2,2,2,IT Business Analyst,information-technology-business-analyst,PT Nextalent Talenta Nusantara,"Teknologi Informasi & Komunikasi, Analis Bisni...",Jakarta Raya,80187093,Full time,NaN,Rp 10.000.000 – Rp 14.000.000 per month,https://id.jobstreet.com/job/80187093,Qualification : Candidate must possess at leas...,Analis bisnis TI,Error: [Errno 11001] getaddrinfo failed,"Teknolog Informasi & Komununasi, Anis Bisnis/S...",Informasi-Teknologi-Business-Analyst
3,3,3,IT Business Analyst,information-technology-business-analyst,PT Nextalent Talenta Nusantara,"Teknologi Informasi & Komunikasi, Analis Bisni...",Jakarta Raya,80187093,Full time,NaN,Rp 10.000.000 – Rp 14.000.000 per month,https://id.jobstreet.com/job/80187093,Qualification : Candidate must possess at leas...,Analis bisnis TI,Error: [Errno 11001] getaddrinfo failed,"Teknologi Informasi & Komunikasi, Analis Bisni...",Informasi-Teknologi-Business-Analyst
4,4,4,SALES EXECUTIVE,sales-executive,PT. LAXMI UTAMA,"Ritel & Produk Konsumen, Asisten Ritel","Surabaya, Jawa Timur",79645321,Full time,"Gaji Pokok dan Insentif, BPJS Ketenaga kerjaan...",Rp 6.000.000 – Rp 9.000.000 per month,https://id.jobstreet.com/job/79645321,A retail garment sales executive plays a vital...,Eksekutif Penjualan,Error: [Errno 11001] getaddrinfo failed,"Ritel & Produk Mengkonsumsi, Asist Ritel",Eksekutif penjualan

In [3]:
columns_to_drop = ['Unnamed: 0.1', 'Unnamed: 0']

df.drop(columns=columns_to_drop, inplace=True)

In [4]:
df.head()

,title,role,company_name,category,location,jobId,type,benefit,salary,url,description,title_translated,description_translated,category_translated,role_translated
0,Penerjemah Bahasa Mandarin，Asisten Manajer Umum,Mandarin-Translator,PT ONEMATE AKSESORIS MOBIL,"Administrasi & Dukungan Perkantoran, Asisten A...","Tangerang, Banten",79976110,Full time,NaN,Rp 8.500.000 – Rp 12.500.000 per month,https://id.jobstreet.com/job/79976110,Asisten Manajer Umum: • Membantu manajer umum ...,Penerjemah Bahasa Mandarin，Asisten Manajer Umum,Asisten Manajer Umum: • Membantu manajer umum ...,"Administrasi & Dukungan Perkantoran, Asisten A...",Mandarin-Translator
1,Penerjemah Bahasa Mandarin，Asisten Manajer Umum,Mandarin-Translator,PT ONEMATE AKSESORIS MOBIL,"Administrasi & Dukungan Perkantoran, Asisten A...","Tangerang, Banten",79976110,Full time,NaN,Rp 8.500.000 – Rp 12.500.000 per month,https://id.jobstreet.com/job/79976110,Asisten Manajer Umum: • Membantu manajer umum ...,Penerjemah Bahasa Mandarin，Asisten Manajer Umum,Asisten Manajer Umum: • Membantu manajer umum ...,"Administrasi & Dukungan Perkantoran, Asisten A...",Mandarin-Translator
2,IT Business Analyst,information-technology-business-analyst,PT Nextalent Talenta Nusantara,"Teknologi Informasi & Komunikasi, Analis Bisni...",Jakarta Raya,80187093,Full time,NaN,Rp 10.000.000 – Rp 14.000.000 per month,https://id.jobstreet.com/job/80187093,Qualification : Candidate must possess at leas...,Analis bisnis TI,Error: [Errno 11001] getaddrinfo failed,"Teknolog Informasi & Komununasi, Anis Bisnis/S...",Informasi-Teknologi-Business-Analyst
3,IT Business Analyst,information-technology-business-analyst,PT Nextalent Talenta Nusantara,"Teknologi Informasi & Komunikasi, Analis Bisni...",Jakarta Raya,80187093,Full time,NaN,Rp 10.000.000 – Rp 14.000.000 per month,https://id.jobstreet.com/job/80187093,Qualification : Candidate must possess at leas...,Analis bisnis TI,Error: [Errno 11001] getaddrinfo failed,"Teknologi Informasi & Komunikasi, Analis Bisni...",Informasi-Teknologi-Business-Analyst
4,SALES EXECUTIVE,sales-executive,PT. LAXMI UTAMA,"Ritel & Produk Konsumen, Asisten Ritel","Surabaya, Jawa Timur",79645321,Full time,"Gaji Pokok dan Insentif, BPJS Ketenaga kerjaan...",Rp 6.000.000 – Rp 9.000.000 per month,https://id.jobstreet.com/job/79645321,A retail garment sales executive plays a vital...,Eksekutif Penjualan,Error: [Errno 11001] getaddrinfo failed,"Ritel & Produk Mengkonsumsi, Asist Ritel",Eksekutif penjualan

In [5]:
df.shape

(6155, 15)

In [6]:
df.drop_duplicates(inplace=True)

df.head()

,title,role,company_name,category,location,jobId,type,benefit,salary,url,description,title_translated,description_translated,category_translated,role_translated
0,Penerjemah Bahasa Mandarin，Asisten Manajer Umum,Mandarin-Translator,PT ONEMATE AKSESORIS MOBIL,"Administrasi & Dukungan Perkantoran, Asisten A...","Tangerang, Banten",79976110,Full time,NaN,Rp 8.500.000 – Rp 12.500.000 per month,https://id.jobstreet.com/job/79976110,Asisten Manajer Umum: • Membantu manajer umum ...,Penerjemah Bahasa Mandarin，Asisten Manajer Umum,Asisten Manajer Umum: • Membantu manajer umum ...,"Administrasi & Dukungan Perkantoran, Asisten A...",Mandarin-Translator
2,IT Business Analyst,information-technology-business-analyst,PT Nextalent Talenta Nusantara,"Teknologi Informasi & Komunikasi, Analis Bisni...",Jakarta Raya,80187093,Full time,NaN,Rp 10.000.000 – Rp 14.000.000 per month,https://id.jobstreet.com/job/80187093,Qualification : Candidate must possess at leas...,Analis bisnis TI,Error: [Errno 11001] getaddrinfo failed,"Teknolog Informasi & Komununasi, Anis Bisnis/S...",Informasi-Teknologi-Business-Analyst
3,IT Business Analyst,information-technology-business-analyst,PT Nextalent Talenta Nusantara,"Teknologi Informasi & Komunikasi, Analis Bisni...",Jakarta Raya,80187093,Full time,NaN,Rp 10.000.000 – Rp 14.000.000 per month,https://id.jobstreet.com/job/80187093,Qualification : Candidate must possess at leas...,Analis bisnis TI,Error: [Errno 11001] getaddrinfo failed,"Teknologi Informasi & Komunikasi, Analis Bisni...",Informasi-Teknologi-Business-Analyst
4,SALES EXECUTIVE,sales-executive,PT. LAXMI UTAMA,"Ritel & Produk Konsumen, Asisten Ritel","Surabaya, Jawa Timur",79645321,Full time,"Gaji Pokok dan Insentif, BPJS Ketenaga kerjaan...",Rp 6.000.000 – Rp 9.000.000 per month,https://id.jobstreet.com/job/79645321,A retail garment sales executive plays a vital...,Eksekutif Penjualan,Error: [Errno 11001] getaddrinfo failed,"Ritel & Produk Mengkonsumsi, Asist Ritel",Eksekutif penjualan
5,Site Project Staff,Project-Staff,PT Vnv Mandiri Valve,"Konstruksi, Manajemen Proyek","Kabupaten Bekasi, Jawa Barat",79912142,Kontrak,NaN,Rp 4.500.000 – Rp 5.500.000 per month,https://id.jobstreet.com/job/79912142,"Uraian Tugas : Menyusun rencana proyek, termas...",Staf Proyek Situs,"Uraian Tugas : Menyusun rencana proyek, termas...","Konstruksi, Manajemen Proyek",Staf proyek

In [7]:
df.shape

(6150, 15)

In [8]:
df = df.dropna(subset='salary')

df.shape

(6150, 15)

In [9]:
jumlah_null = df.isnull().sum()

print(jumlah_null)

title                        0
role                       352
company_name                 0
category                     0
location                     0
jobId                        0
type                         0
benefit                   3918
salary                       0
url                          0
description                  2
title_translated             0
description_translated       0
category_translated          0
role_translated              0
dtype: int64

In [10]:
#mengubah huruf kecil semua
for col in df.select_dtypes(include='object').columns:
    df[col] = df[col].str.lower()

df.head()

,title,role,company_name,category,location,jobId,type,benefit,salary,url,description,title_translated,description_translated,category_translated,role_translated
0,penerjemah bahasa mandarin，asisten manajer umum,mandarin-translator,pt onemate aksesoris mobil,"administrasi & dukungan perkantoran, asisten a...","tangerang, banten",79976110,full time,NaN,rp 8.500.000 – rp 12.500.000 per month,https://id.jobstreet.com/job/79976110,asisten manajer umum: • membantu manajer umum ...,penerjemah bahasa mandarin，asisten manajer umum,asisten manajer umum: • membantu manajer umum ...,"administrasi & dukungan perkantoran, asisten a...",mandarin-translator
2,it business analyst,information-technology-business-analyst,pt nextalent talenta nusantara,"teknologi informasi & komunikasi, analis bisni...",jakarta raya,80187093,full time,NaN,rp 10.000.000 – rp 14.000.000 per month,https://id.jobstreet.com/job/80187093,qualification : candidate must possess at leas...,analis bisnis ti,error: [errno 11001] getaddrinfo failed,"teknolog informasi & komununasi, anis bisnis/s...",informasi-teknologi-business-analyst
3,it business analyst,information-technology-business-analyst,pt nextalent talenta nusantara,"teknologi informasi & komunikasi, analis bisni...",jakarta raya,80187093,full time,NaN,rp 10.000.000 – rp 14.000.000 per month,https://id.jobstreet.com/job/80187093,qualification : candidate must possess at leas...,analis bisnis ti,error: [errno 11001] getaddrinfo failed,"teknologi informasi & komunikasi, analis bisni...",informasi-teknologi-business-analyst
4,sales executive,sales-executive,pt. laxmi utama,"ritel & produk konsumen, asisten ritel","surabaya, jawa timur",79645321,full time,"gaji pokok dan insentif, bpjs ketenaga kerjaan...",rp 6.000.000 – rp 9.000.000 per month,https://id.jobstreet.com/job/79645321,a retail garment sales executive plays a vital...,eksekutif penjualan,error: [errno 11001] getaddrinfo failed,"ritel & produk mengkonsumsi, asist ritel",eksekutif penjualan
5,site project staff,project-staff,pt vnv mandiri valve,"konstruksi, manajemen proyek","kabupaten bekasi, jawa barat",79912142,kontrak,NaN,rp 4.500.000 – rp 5.500.000 per month,https://id.jobstreet.com/job/79912142,"uraian tugas : menyusun rencana proyek, termas...",staf proyek situs,"uraian tugas : menyusun rencana proyek, termas...","konstruksi, manajemen proyek",staf proyek

In [11]:
# columns_to_drop = ['title', 'role', 'category', 'description']

# df.drop(columns=columns_to_drop, inplace=True)

In [12]:
# rename_column = {
#     'title_translated': 'title',
#     'description_translated': 'description',
#     'category_translated': 'category',
#     'role_translated': 'role'
# }

# df = df.rename(columns=rename_column)

# Title

In [13]:
print(df['title'].unique())

['penerjemah bahasa mandarin，asisten manajer umum' 'it business analyst'
 'sales executive' ... 'people development supervisor'
 'manager finance accounting'
 'cluster permit pic ftth project (medan, palembang)']

In [14]:
#menghapus spasi berlebih
df['title'] = df['title'].str.strip().str.replace(r'\s+', ' ', regex=True)

df.head()

,title,role,company_name,category,location,jobId,type,benefit,salary,url,description,title_translated,description_translated,category_translated,role_translated
0,penerjemah bahasa mandarin，asisten manajer umum,mandarin-translator,pt onemate aksesoris mobil,"administrasi & dukungan perkantoran, asisten a...","tangerang, banten",79976110,full time,NaN,rp 8.500.000 – rp 12.500.000 per month,https://id.jobstreet.com/job/79976110,asisten manajer umum: • membantu manajer umum ...,penerjemah bahasa mandarin，asisten manajer umum,asisten manajer umum: • membantu manajer umum ...,"administrasi & dukungan perkantoran, asisten a...",mandarin-translator
2,it business analyst,information-technology-business-analyst,pt nextalent talenta nusantara,"teknologi informasi & komunikasi, analis bisni...",jakarta raya,80187093,full time,NaN,rp 10.000.000 – rp 14.000.000 per month,https://id.jobstreet.com/job/80187093,qualification : candidate must possess at leas...,analis bisnis ti,error: [errno 11001] getaddrinfo failed,"teknolog informasi & komununasi, anis bisnis/s...",informasi-teknologi-business-analyst
3,it business analyst,information-technology-business-analyst,pt nextalent talenta nusantara,"teknologi informasi & komunikasi, analis bisni...",jakarta raya,80187093,full time,NaN,rp 10.000.000 – rp 14.000.000 per month,https://id.jobstreet.com/job/80187093,qualification : candidate must possess at leas...,analis bisnis ti,error: [errno 11001] getaddrinfo failed,"teknologi informasi & komunikasi, analis bisni...",informasi-teknologi-business-analyst
4,sales executive,sales-executive,pt. laxmi utama,"ritel & produk konsumen, asisten ritel","surabaya, jawa timur",79645321,full time,"gaji pokok dan insentif, bpjs ketenaga kerjaan...",rp 6.000.000 – rp 9.000.000 per month,https://id.jobstreet.com/job/79645321,a retail garment sales executive plays a vital...,eksekutif penjualan,error: [errno 11001] getaddrinfo failed,"ritel & produk mengkonsumsi, asist ritel",eksekutif penjualan
5,site project staff,project-staff,pt vnv mandiri valve,"konstruksi, manajemen proyek","kabupaten bekasi, jawa barat",79912142,kontrak,NaN,rp 4.500.000 – rp 5.500.000 per month,https://id.jobstreet.com/job/79912142,"uraian tugas : menyusun rencana proyek, termas...",staf proyek situs,"uraian tugas : menyusun rencana proyek, termas...","konstruksi, manajemen proyek",staf proyek

In [15]:
#menghilangkan karakter khusus
df['title'] = df['title'].str.replace(r'[^\w\s]', '', regex=True)

#mengatasi kata yang berulang
df['title'] = df['title'].str.replace(r'\b(\w+)\s+\1\b', r'\1', regex=True)

#hapus value yang kosong
df = df[df['title'].notnull() & ~df['title'].str.contains('unknown|tidak ada', na=False)]

In [16]:
#setelah dilihat terdapat bahasa cina pada title
#deteksi entri dengan karakter non-Latin
non_latin_titles = df[df['title'].str.contains(r'[^\x00-\x7F]', na=False)]

for idx, title in non_latin_titles['title'].items():
    print(f"Index {idx}: {title}")

Index 146: mandarin assistant manager 中文助理
Index 272: 门店管培生 management trainee operations  mandarin speaker jakarta
Index 297: 政府事务部经理public affairs manager
Index 423: administrative assistant 行政助理 mandarin speaker
Index 572: 办公室翻译助理
Index 652: 门店文员 admin outlet  mandarin speaker
Index 923: 运营翻译助理
Index 1030: assistant to general manager mandarin translator普通话流利
Index 1137: 中文翻译专业岗位中文翻译mandarin translation
Index 1257: client relation chinese speaker 新能源部客服岗位
Index 1445: 行政专员  中文
Index 1462: adminkoordinator bilingual mandarinindonesia 双语文员或协管员 中印
Index 1508: 临时中文翻译
Index 1600: accountant会计
Index 1904: 税务处理员 staff tax acounting
Index 2486: customs manager 关务经理
Index 2791: finance 财务 mandarin speaker
Index 3534: mandarin translator 工厂翻译
Index 3620: 应届毕业生机会  印尼中文人才
Index 4434: 中文餐厅运营助理
Index 4804: staff media  品牌媒体专员
Index 5335: 中文助理 mandarin assistant
Index 5629: live operation specialist 直播运营
Index 5908: tax  accounting 税务会计

In [17]:
translate_bahasa_cina = {
    '办公室翻译助理': 'asisten terjemahan kantor',
    '运营翻译助理': 'asisten penerjemahan operasi',
    '行政专员  中文': 'spesialis administrasi cina',
    '临时中文翻译': 'penerjemah bahasa mandarin',
    '应届毕业生机会  印尼中文人才': 'talenta tionghoa indonesia',
    '中文餐厅运营助理': 'asisten operasi restoran cina'
}

df['title'] = df['title'].replace(translate_bahasa_cina)

In [18]:
#setelah dilihat terdapat bahasa cina pada title
#deteksi entri dengan karakter non-Latin
non_latin_titles = df[df['title'].str.contains(r'[^\x00-\x7F]', na=False)]

for idx, title in non_latin_titles['title'].items():
    print(f"Index {idx}: {title}")

Index 146: mandarin assistant manager 中文助理
Index 272: 门店管培生 management trainee operations  mandarin speaker jakarta
Index 297: 政府事务部经理public affairs manager
Index 423: administrative assistant 行政助理 mandarin speaker
Index 652: 门店文员 admin outlet  mandarin speaker
Index 1030: assistant to general manager mandarin translator普通话流利
Index 1137: 中文翻译专业岗位中文翻译mandarin translation
Index 1257: client relation chinese speaker 新能源部客服岗位
Index 1445: 行政专员  中文
Index 1462: adminkoordinator bilingual mandarinindonesia 双语文员或协管员 中印
Index 1600: accountant会计
Index 1904: 税务处理员 staff tax acounting
Index 2486: customs manager 关务经理
Index 2791: finance 财务 mandarin speaker
Index 3534: mandarin translator 工厂翻译
Index 4804: staff media  品牌媒体专员
Index 5335: 中文助理 mandarin assistant
Index 5629: live operation specialist 直播运营
Index 5908: tax  accounting 税务会计

In [19]:
non_latin_mask = df['title'].str.contains(r'[^\x00-\x7F]', na=False)
df = df[~non_latin_mask]
df.reset_index(drop=True, inplace=True)

In [20]:
#setelah dilihat terdapat bahasa cina pada title
#deteksi entri dengan karakter non-Latin
non_latin_titles = df[df['title'].str.contains(r'[^\x00-\x7F]', na=False)]

for idx, title in non_latin_titles['title'].items():
    print(f"Index {idx}: {title}")

In [21]:
def clean_text(text):
    if isinstance(text, str):  # Pastikan hanya string yang diproses
        # Ganti '/' dengan 'atau' dan '&' dengan 'dan'
        text = text.replace('/', 'atau').replace('&', 'dan')
        # Hilangkan spasi di awal, akhir, dan spasi berlebih antar kata menggunakan re.sub
        text = re.sub(r'\s+', ' ', text.strip())
    return text

df = df.applymap(clean_text)

C:\Users\USER\AppData\Local\Temp\ipykernel_24436\2082930823.py:9: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df = df.applymap(clean_text)

In [22]:
df.head()

,title,role,company_name,category,location,jobId,type,benefit,salary,url,description,title_translated,description_translated,category_translated,role_translated
0,penerjemah bahasa mandarinasisten manajer umum,mandarin-translator,pt onemate aksesoris mobil,"administrasi dan dukungan perkantoran, asisten...","tangerang, banten",79976110,full time,NaN,rp 8.500.000 – rp 12.500.000 per month,https:atauatauid.jobstreet.comataujobatau79976110,asisten manajer umum: • membantu manajer umum ...,penerjemah bahasa mandarin，asisten manajer umum,asisten manajer umum: • membantu manajer umum ...,"administrasi dan dukungan perkantoran, asisten...",mandarin-translator
1,it business analyst,information-technology-business-analyst,pt nextalent talenta nusantara,"teknologi informasi dan komunikasi, analis bis...",jakarta raya,80187093,full time,NaN,rp 10.000.000 – rp 14.000.000 per month,https:atauatauid.jobstreet.comataujobatau80187093,qualification : candidate must possess at leas...,analis bisnis ti,error: [errno 11001] getaddrinfo failed,"teknolog informasi dan komununasi, anis bisnis...",informasi-teknologi-business-analyst
2,it business analyst,information-technology-business-analyst,pt nextalent talenta nusantara,"teknologi informasi dan komunikasi, analis bis...",jakarta raya,80187093,full time,NaN,rp 10.000.000 – rp 14.000.000 per month,https:atauatauid.jobstreet.comataujobatau80187093,qualification : candidate must possess at leas...,analis bisnis ti,error: [errno 11001] getaddrinfo failed,"teknologi informasi dan komunikasi, analis bis...",informasi-teknologi-business-analyst
3,sales executive,sales-executive,pt. laxmi utama,"ritel dan produk konsumen, asisten ritel","surabaya, jawa timur",79645321,full time,"gaji pokok dan insentif, bpjs ketenaga kerjaan...",rp 6.000.000 – rp 9.000.000 per month,https:atauatauid.jobstreet.comataujobatau79645321,a retail garment sales executive plays a vital...,eksekutif penjualan,error: [errno 11001] getaddrinfo failed,"ritel dan produk mengkonsumsi, asist ritel",eksekutif penjualan
4,site project staff,project-staff,pt vnv mandiri valve,"konstruksi, manajemen proyek","kabupaten bekasi, jawa barat",79912142,kontrak,NaN,rp 4.500.000 – rp 5.500.000 per month,https:atauatauid.jobstreet.comataujobatau79912142,"uraian tugas : menyusun rencana proyek, termas...",staf proyek situs,"uraian tugas : menyusun rencana proyek, termas...","konstruksi, manajemen proyek",staf proyek

## normalisasi kata-kata title

In [23]:
#filter baris dengan jumlah kata lebih dari 10 pada kolom 'title'
kata_lebih_10 = df[df['title'].apply(lambda x: len(str(x).split()) > 10)]
kata_lebih_10.to_csv("title_lebih_10_kata.csv", index=False)

In [24]:
#normalisasi untuk title yang lebih dari 10 kata
df.loc[df['title'] == 'host live tiktok full time gaji up to 15 jt komisi no limit', 'title'] = 'live tiktok host'
df.loc[df['title'] == 'personal assistant pa to the ceo of lex mall east jakarta', 'title'] = 'personal assistant'
df.loc[df['title'] == 'business developmentchina clients do not apply if you cant speak mandarin', 'title'] = 'business development'
df.loc[df['title'] == 'app vip user account manager require live stream host with fluent english', 'title'] = 'account manager'
df.loc[df['title'] == 'sales executive sales support a sales manager marine pump spare parts', 'title'] = 'sales executive'
df.loc[df['title'] == 'join our teaching adventure in paradise english teachers needed for ef lombok', 'title'] = 'english teacher'
df.loc[df['title'] == 'it senior staff sap s4 hana ppmm module manufacturing bekasi a107673', 'title'] = 'it senior staff'
df.loc[df['title'] == 'sales marketing manager wfh in batam area steel trading batam b113030', 'title'] = 'sales marketing manager'
df.loc[df['title'] == 'credit analyst staff multifinance company mahada finance member of ppa group', 'title'] = 'credit analyst'

In [25]:
#filter baris dengan jumlah kata lebih dari 7 pada kolom 'title'
kata_lebih_7 = df[df['title'].apply(lambda x: len(str(x).split()) > 7)]
kata_lebih_7.to_csv("title_lebih_7_kata.csv", index=False)

In [26]:
#normalisasi untuk title yang lebih dari 7 kata
df.loc[df['title'] == 'management trainee teknik proyek instalasi medis dan alkes', 'title'] = 'management trainee'
df.loc[df['title'] == 'technical sales manager animal nutrition jakarta wfo id 659268', 'title'] = 'technical sales manager'
df.loc[df['title'] == 'general audit assistant manager manufacture karawang id 658906', 'title'] = 'general audit assistant manager'
df.loc[df['title'] == 'sales staff crane industry cikarang wfo id 659408', 'title'] = 'sales staff'
df.loc[df['title'] == 'japanese speaker budget controller spvasst manager fmcg karawanga112562', 'title'] = 'budget controller'
df.loc[df['title'] == 'mandarin speaker in education field multiple roles full time', 'title'] = 'mandarin speaker'
df.loc[df['title'] == 'hp executive assistant account officer tangerang bogor area', 'title'] = 'executive assistant'
df.loc[df['title'] == 'marketing supervisor senior spv japanese restaurant wfo 659971', 'title'] = 'marketing supervisor'
df.loc[df['title'] == 'electrical component assembly assembler to the kingdom of saudi arabia', 'title'] = 'electrical component assembler'
df.loc[df['title'] == 'social media specialist content creator operator host live', 'title'] = 'social media specialist'
df.loc[df['title'] == 'agent english live chat cefr certified min b2', 'title'] = 'live chat agent'
df.loc[df['title'] == 'guru musik anak pengajar musik piano drum keyboard gitar', 'title'] = 'guru musik'
df.loc[df['title'] == 'psikolog klinis clinical psychologist online dan tatap muka', 'title'] = 'clinical psychologist'
df.loc[df['title'] == 'premier bancassurance life consultant bsd gading serpong alam sutera', 'title'] = 'bancassurance consultant'
df.loc[df['title'] == 'dokter umum klinik bimc jakarta depok dan bandung', 'title'] = 'dokter umum'
df.loc[df['title'] == 'sales executive builtin kitchen appliances or commercial refrigeration', 'title'] = 'sales executive'
df.loc[df['title'] == 'sales assistant manager manufacture karawang wfo id 659313', 'title'] = 'sales assistant manager'
df.loc[df['title'] == 'stone mining site translator mandarin speaker with regular roster leave', 'title'] = 'site translator'
df.loc[df['title'] == 'sales marketing lulusan dokter hewan atau sarjana peternakan', 'title'] = 'sales marketing'
df.loc[df['title'] == 'sales executive freight forwarding export import air logistic cargo', 'title'] = 'sales executive'
df.loc[df['title'] == 'sales manager household builtin kitchen appliances or commercial refrigeration', 'title'] = 'sales manager'
df.loc[df['title'] == 'importer and distributor department head wfo jakarta id 657856', 'title'] = 'department head'
df.loc[df['title'] == 'regional marketing executive base in indonesia work for anywhere', 'title'] = 'regional marketing executive'
df.loc[df['title'] == 'quantity surveyor and supervisor for structure highrise building', 'title'] = 'quantity surveyor'
df.loc[df['title'] == 'premier bancassurance life consultant pik asemka gajah mada', 'title'] = 'bancassurance consultant'
df.loc[df['title'] == 'financial advisor area sales manager bancassurance penempatan surabaya', 'title'] = 'financial advisor'
df.loc[df['title'] == 'area manager toko retail gadget acc service dan sparepart hp', 'title'] = 'area manager'
df.loc[df['title'] == 'accounting staff automotive parts karawang wfo id 659356', 'title'] = 'accounting staff'
df.loc[df['title'] == 'sales executive bahan bangunan area tegal pemalang pekalongan batang', 'title'] = 'sales executive'
df.loc[df['title'] == 'area manager operational mama roz cold press juice', 'title'] = 'area manager'
df.loc[df['title'] == 'quality engineering staff sales engineer automotive cikarang b112745', 'title'] = 'sales engineer'
df.loc[df['title'] == 'head of administration and admissions at british school of bali', 'title'] = 'head of administration'
df.loc[df['title'] == 'mechanical engineer site plant cikarang karawang sidoarjo construction', 'title'] = 'mechanical engineer'
df.loc[df['title'] == '1 content creator 2 digital advertiser dan 3 graphic design', 'title'] = 'content creator'
df.loc[df['title'] == 'qc inspection sni assistant manager manufacture depok b112862', 'title'] = 'qc inspection assistant manager'
df.loc[df['title'] == 'asisten refraksi optik asro sales counter optik yogyakarta', 'title'] = 'asisten refraksi optik'
df.loc[df['title'] == 'team leader divisi hp area medan kisaran dan aceh', 'title'] = 'team leader'
df.loc[df['title'] == 'interior design drafter interior works electrical installation b112254', 'title'] = 'interior design drafter'
df.loc[df['title'] == 'japanese speaker service mechanical engineer machinery bekasi a111460', 'title'] = 'mechanical engineer'
df.loc[df['title'] == 'guest service agent new luxury hotel based in macau', 'title'] = 'guest service agent'
df.loc[df['title'] == 'operator mesin uv printing digital printing uv flatbed', 'title'] = 'uv printing operator'
df.loc[df['title'] == 'business development manager it hardware ssd tangerang b112707', 'title'] = 'business development manager'
df.loc[df['title'] == 'sales promotion area gresik mojosari mojokerto malang madiun', 'title'] = 'sales promotion'
df.loc[df['title'] == 'staff health safety and environment hse document control', 'title'] = 'hse staff'
df.loc[df['title'] == 'cook 1 2 section wok seafood restaurant pik 2', 'title'] = 'cook'
df.loc[df['title'] == 'site manager project system pendingin refrigerasi cold room hvac', 'title'] = 'site manager'
df.loc[df['title'] == 'uiux designer with 3d rendering cgi and animation expertise', 'title'] = 'uiux designer'
df.loc[df['title'] == 'hr executive staff level manufacture sumatra utara c112069', 'title'] = 'hr executive'
df.loc[df['title'] == 'senior teacher for elementary school tingkat sekolah dasar', 'title'] = 'senior teacher'
df.loc[df['title'] == 'nurse for hair transplant clinic in jimbaran bali', 'title'] = 'nurse'
df.loc[df['title'] == 'qc laboratory leader chemical karawang wfo id 659649', 'title'] = 'qc laboratory leader'
df.loc[df['title'] == 'accounting admin logistic gudang supervisor mep drafter mep', 'title'] = 'accounting admin'
df.loc[df['title'] == 'senior teacher for junior high school sekolah tingkat pertama', 'title'] = 'senior teacher'
df.loc[df['title'] == 'tax accounting hrga assistant manager forwarding jakarta utara c109955', 'title'] = 'tax accounting assistant manager'
df.loc[df['title'] == 'merchandising purchasing for furniture ecommerce retail mandarin speaking', 'title'] = 'merchandising'
df.loc[df['title'] == 'agency relationship executive manado tomohon bitung minahasa selatan', 'title'] = 'agency relationship executive'
df.loc[df['title'] == 'production senior staff manufacture cikarang wfo id 659748', 'title'] = 'production senior staff'
df.loc[df['title'] == 'estimator pengawas proyek sipil interior di elite home creations', 'title'] = 'estimator'
df.loc[df['title'] == 'marketing pembiayaan modal ventura penempatan jakarta dan karawang', 'title'] = 'marketing pembiayaan'
df.loc[df['title'] == 'customer service reply email live chat english night shifthigh salary', 'title'] = 'customer service'
df.loc[df['title'] == 'corrugated box packaging inner dan outer printing manager', 'title'] = 'packaging manager'
df.loc[df['title'] == 'asisten refraksi optik asro sales counter optik jakarta', 'title'] = 'asisten refraksi optik'
df.loc[df['title'] == 'pengajar bahasa jepang pengajar perawat lansia jepang nihongo kaigo sensei', 'title'] = 'pengajar bahasa jepang'
df.loc[df['title'] == 'sales promotor elektronik jakarta bogor depok tangerang bekasi', 'title'] = 'sales promotor'
df.loc[df['title'] == 'cook 1 leader central kitchen ubitiri baik pik 2', 'title'] = 'cook leader'
df.loc[df['title'] == 'financial advisor area jakarta selatan falatehan melawai blok m', 'title'] = 'financial advisor'
df.loc[df['title'] == 'civil engineer quantity surveyor pengawas lapangan berdomisili di bali', 'title'] = 'civil engineer'
df.loc[df['title'] == 'head of retail business development fashion retail b112670', 'title'] = 'head of retail business development'
df.loc[df['title'] == 'sales marketing assistant manager mencatat kegiatan bisnis retail b112439', 'title'] = 'sales marketing assistant manager'
df.loc[df['title'] == 'digital marketing assistant manager influencer marketing b112214', 'title'] = 'digital marketing assistant manager'
df.loc[df['title'] == 'business development manager logistics expediting transportation', 'title'] = 'business development manager'
df.loc[df['title'] == 'field supervisor for civil works general construction civil drafter', 'title'] = 'field supervisor'
df.loc[df['title'] == 'finance accounting budget staff factory manager karawang', 'title'] = 'finance accounting budget staff'
df.loc[df['title'] == 'pharmaceutical regulatory affairs manager jakarta', 'title'] = 'regulatory affairs manager'
df.loc[df['title'] == 'production supervisor untuk tekstil garment dan power plant', 'title'] = 'production supervisor'
df.loc[df['title'] == 'senior quality engineer automotive lighting automotive manufacturing', 'title'] = 'senior quality engineer'
df.loc[df['title'] == 'survey and design engineer ftth medan pemalang mataram', 'title'] = 'survey engineer'
df.loc[df['title'] == 'sales staff fresh graduate manufacture cikarang wfo id 658599', 'title'] = 'sales staff'
df.loc[df['title'] == 'asistent manager research and development r d mold', 'title'] = 'assistant manager'
df.loc[df['title'] == 'agent english live chat cefr certified min b2', 'title'] = 'live chat agent'
df.loc[df['title'] == 'key account manager korean mandarin speaker warehouse cikaranga112844', 'title'] = 'key account manager'
df.loc[df['title'] == 'japanese speaker after sales service engineer fg ok machinery a109774', 'title'] = 'after sales engineer'
df.loc[df['title'] == 'marketing staff wfh in batam area steel trading batam b113000', 'title'] = 'marketing staff'
df.loc[df['title'] == 'supervisor marketing 2w homebase makassar pt mitra rubber industries', 'title'] = 'marketing supervisor'
df.loc[df['title'] == 'salesman sparepart mobil motor area jakarta dan serpong', 'title'] = 'salesman spareparts'
df.loc[df['title'] == 'it exim staff open for fresh graduates trading cikarang c113075', 'title'] = 'IT EXIM staff'
df.loc[df['title'] == 'tech lead it consulting work in japan a112924', 'title'] = 'tech lead'
df.loc[df['title'] == 'assistant manager new business development chemical trading b112783', 'title'] = 'assistant manager'
df.loc[df['title'] == 'sozo manajer klinik clinic manager cakung bekasi tangerang', 'title'] = 'clinic manager'
df.loc[df['title'] == 'finance accounting manager karawang manufacturing wfo id 654833', 'title'] = 'finance accounting manager'
df.loc[df['title'] == 'area sales manager pet care key account ecommerce jabodetabek', 'title'] = 'area sales manager'
df.loc[df['title'] == 'account manager for software solution division sap b1 huawei cloud', 'title'] = 'account manager'
df.loc[df['title'] == 'area sales representatives denpasar makassar manado balikpapan semarang', 'title'] = 'sales representative'
df.loc[df['title'] == 'tailor cutting pattern maker penjahit tukang potong dan pattern maker', 'title'] = 'tailor'
df.loc[df['title'] == 'cook helper central kitchen ubitiri baik pik 2', 'title'] = 'cook helper'
df.loc[df['title'] == 'restaurant management team store manager asst manager supervisor captain', 'title'] = 'restaurant manager'
df.loc[df['title'] == 'technical staff printing labeling cikarang wfo id 660640', 'title'] = 'technical staff'
df.loc[df['title'] == 'regional key account manager oil lubricants industrial b2b sumatera', 'title'] = 'regional account manager'
df.loc[df['title'] == 'tax manager for it distribution hardware software services', 'title'] = 'tax manager'
df.loc[df['title'] == 'sales daytona area jakarta depok bekasi karawang purwakarta', 'title'] = 'sales'
df.loc[df['title'] == 'chief marketing and sales officer retail industry required', 'title'] = 'chief marketing officer'
df.loc[df['title'] == 'finance accounting tax pajak admin manager konveksi garment', 'title'] = 'finance manager'
df.loc[df['title'] == 'head of after service and maintenance team lift and escalator', 'title'] = 'service manager'
df.loc[df['title'] == 'bancassurance advisor syariah senior jawa timur surabaya malang', 'title'] = 'bancassurance advisor'
df.loc[df['title'] == 'finance analyst cost control supervisor konstruksi proyek toll', 'title'] = 'finance analyst'
df.loc[df['title'] == 'accounting staff multifinance company mahada finance member of ppa group', 'title'] = 'accounting staff'
df.loc[df['title'] == 'asisten refraksi optik asro sales counter optik bali', 'title'] = 'optical assistant'
df.loc[df['title'] == 'medical devices representative sales staff alat kesehatan seluruh indonesia', 'title'] = 'medical devices sales'
df.loc[df['title'] == 'accounting and tax supervisor cv kharisma tiara abadi', 'title'] = 'accounting supervisor'
df.loc[df['title'] == 'app talenthost recruitor bd manager require basic english speaking', 'title'] = 'BD manager'
df.loc[df['title'] == 'relationship manager funding institutional jakarta jawa bali sumatera area', 'title'] = 'relationship manager'
df.loc[df['title'] == 'sales taking order retail latubo madiun jember kediri', 'title'] = 'sales retail'
df.loc[df['title'] == 'intellectual property officer legal south jakarta wfo id 660337', 'title'] = 'IP officer'
df.loc[df['title'] == 'sales store staff at brewsuniq store gading serpong', 'title'] = 'store sales staff'
df.loc[df['title'] == 'it senior sales manager it hris software tangerang a112619', 'title'] = 'IT sales manager'
df.loc[df['title'] == 'senior marketing executive product ivd jawa tengah and diy', 'title'] = 'marketing executive'
df.loc[df['title'] == 'japanese speaker guest relation and marketing staff hotel karawanga112427', 'title'] = 'guest relations staff'
df.loc[df['title'] == 'area sales promotion supervisor malang pt agel langgeng', 'title'] = 'sales supervisor'
df.loc[df['title'] == 'ffe engineer staff interior staff placement badung bali', 'title'] = 'FFE engineer'
df.loc[df['title'] == 'senior legal officer ma south jakarta wfo id 660336', 'title'] = 'senior legal officer'
df.loc[df['title'] == 'outdoor sales machinery for oil gas bogor b112861', 'title'] = 'outdoor sales'
df.loc[df['title'] == 'asisten refraksi optik asro sales counter optik surabaya', 'title'] = 'optical assistant'
df.loc[df['title'] == 'sales marketing staff open for fg trading coating division b113040', 'title'] = 'sales marketing staff'
df.loc[df['title'] == 'area sales manager sumatera bagian selatan frozen food', 'title'] = 'area sales manager'
df.loc[df['title'] == 'japanese speaker hrga assistant manager real estate a112925', 'title'] = 'HRGA assistant manager'
df.loc[df['title'] == 'sales to taking order toys soft toys stationery mtgt', 'title'] = 'sales order'
df.loc[df['title'] == 'optometrist refraksionis optisien optisi cek mata refraksi optisi ro', 'title'] = 'optometrist'
df.loc[df['title'] == 'translator mandarin indonesia manufaktur tas di jombang jawa timur', 'title'] = 'translator'
df.loc[df['title'] == 'marketing tigaraksa cikupa bitung citra raya balaraja curug panongan tangerang', 'title'] = 'marketing'
df.loc[df['title'] == 'branch manager ella skin care kudus sukabumi cirebon', 'title'] = 'branch manager'
df.loc[df['title'] == 'sales marketing supervisor raw material furniture karawang b112404', 'title'] = 'sales marketing supervisor'
df.loc[df['title'] == 'talent conten toko kudus semarang yogyakarta sukabumi mandailing', 'title'] = 'talent content'
df.loc[df['title'] == 'head of hrga it solution jakarta utara c112442', 'title'] = 'HRGA head'
df.loc[df['title'] == 'tenaga teknis kefarmasian apotek k24 bp sudirman jember', 'title'] = 'pharmaceutical technician'
df.loc[df['title'] == 'business development manager manufacture jakarta wfo id 661178', 'title'] = 'business development manager'
df.loc[df['title'] == 'medical device executive bandung cirebon jember surabaya mataram', 'title'] = 'medical device executive'
df.loc[df['title'] == 'sales marketing assistant manager manufacturing foam karawang b112404', 'title'] = 'sales marketing assistant manager'
df.loc[df['title'] == 'financial advisor balikpapan samarinda manado mamuju gorontalo kendari', 'title'] = 'financial advisor'
df.loc[df['title'] == 'administration staff area semarang padang palembang balikpapan samarinda', 'title'] = 'administration staff'
df.loc[df['title'] == 'qc senior staff manufacture cikarang wfo id 659732', 'title'] = 'QC senior staff'
df.loc[df['title'] == 'bancassurance advisor syariah senior jawa timur malang surabaya', 'title'] = 'bancassurance advisor'
df.loc[df['title'] == 'financial advisor bancassurance area jakpus jaksel jakbar jaktim jakut', 'title'] = 'financial advisor'
df.loc[df['title'] == 'marketing fresh graduate domisili jakarta barat dan kota tangerang', 'title'] = 'marketing fresh graduate'
df.loc[df['title'] == 'production engineer automotive manufacturing proficient in cnc machine', 'title'] = 'production engineer'
df.loc[df['title'] == 'area sales manager oil lubricants industrial b2b lampung batam medan', 'title'] = 'area sales manager'
df.loc[df['title'] == 'marketing representative sales used car bintaro tangsel cinere depok', 'title'] = 'marketing representative'
df.loc[df['title'] == 'admin tim p3dn peningkatan penggunaan produk dalam negeri', 'title'] = 'admin P3DN'
df.loc[df['title'] == 'oracle cloud hcm techno consultant it consulting a112913', 'title'] = 'Oracle Cloud consultant'
df.loc[df['title'] == 'asisten refraksi optik asro sales counter optik samarinda', 'title'] = 'optical assistant'
df.loc[df['title'] == 'host live full time produk skincare tangerang selatan', 'title'] = 'live host'
df.loc[df['title'] == 'sales spare part alat berat truk mobil lv untuk tambang', 'title'] = 'sales spare part'
df.loc[df['title'] == 'business development manager team leader forex cfd market surabaya', 'title'] = 'business development manager'
df.loc[df['title'] == 'enterprise presales consultant global mnc up to 60m idr monthly', 'title'] = 'presales consultant'
df.loc[df['title'] == 'financial advisor area jakarta pusat cikini kebon sirih gambir thamrin', 'title'] = 'financial advisor'
df.loc[df['title'] == 'legal hrga administration senior staff fmcg bsd c112839', 'title'] = 'legal HRGA staff'
df.loc[df['title'] == 'supervisor marketing 4w principal pt mitra rubber industries', 'title'] = 'marketing supervisor'
df.loc[df['title'] == 'sales staff for surabaya semarang and medan area', 'title'] = 'sales staff'
df.loc[df['title'] == 'project manager for civil architec piping mechanical erection', 'title'] = 'project manager'
df.loc[df['title'] == 'sales taking order penempatan bandung tasik dan cirebon', 'title'] = 'sales order'
df.loc[df['title'] == 'asisten pribadi fasih bahasa mandarin baca ketik lisan', 'title'] = 'personal assistant'
df.loc[df['title'] == 'asisten refraksi optik asro sales counter optik bekasi', 'title'] = 'optical assistant'
df.loc[df['title'] == 'account manager for all it product solution sales project', 'title'] = 'account manager'
df.loc[df['title'] == 'bancassurance adisor syariah senior jawa timur malang surabaya', 'title'] = 'bancassurance advisor'
df.loc[df['title'] == 'financial advisorbancassurance area jakpus jaksel jakbar jaktim jakut', 'title'] = 'financial advisor'
df.loc[df['title'] == 'marketing freshgraduate domisili jakarta barat dan kota tangerang', 'title'] = 'marketing'
df.loc[df['title'] == 'marketing representativesales used car bintaro tangsel cinere depok', 'title'] = 'marketing representative'
df.loc[df['title'] == 'business development managerteam leader forex cfd market surabaya', 'title'] = 'business development manager'

In [27]:
print(df[df['title'].apply(lambda x: len(str(x).split()) > 7)])

Empty DataFrame
Columns: [title, role, company_name, category, location, jobId, type, benefit, salary, url, description, title_translated, description_translated, category_translated, role_translated]
Index: []

In [28]:
#filter baris dengan jumlah kata lebih dari 5 pada kolom 'title'
kata_lebih_5 = df[df['title'].apply(lambda x: len(str(x).split()) > 5)]
kata_lebih_5.to_csv("title_lebih_5_kata.csv", index=False)

In [29]:
#normalisasi untuk title yang lebih dari 5 kata
df.loc[df['title'] == 'researcher open for fresh graduates consulting c103686', 'title'] = 'researcher consulting'
df.loc[df['title'] == 'tenaga teknis kefarmasian apotek k24 banyumas', 'title'] = 'teknis kefarmasian'
df.loc[df['title'] == 'fraud risk analyst bahasa indonesia kuala lumpur', 'title'] = 'fraud risk analyst'
df.loc[df['title'] == 'financial advisor special hire jaksel bogor depok', 'title'] = 'financial advisor'
df.loc[df['title'] == 'creative director for international agency in bali', 'title'] = 'creative director'
df.loc[df['title'] == 'sales force marketing microfinancing fifgroup jatiuwung tangerang', 'title'] = 'sales marketing microfinancing'
df.loc[df['title'] == 'account manager fsi telecommunications industry jakarta wfo', 'title'] = 'account manager telecommunications'
df.loc[df['title'] == 'senior sales executive managed print services jakarta', 'title'] = 'senior sales executive'
df.loc[df['title'] == 'sales logistic manager freight forwarding b106563', 'title'] = 'sales logistic manager'
df.loc[df['title'] == 'learning and development telemarketing english speaker', 'title'] = 'learning development telemarketing'
df.loc[df['title'] == 'hr supervisor manufacturing wfo cikarang 660374', 'title'] = 'hr supervisor manufacturing'
df.loc[df['title'] == 'senior research and development r d', 'title'] = 'senior r&d'
df.loc[df['title'] == 'real estate marketing placement in bali', 'title'] = 'real estate marketing'
df.loc[df['title'] == 'ppiclogistic manager manufacture cikarang wfo id 658861', 'title'] = 'ppic logistic manager'
df.loc[df['title'] == 'ketua tim penyusun amdal konsultan lingkungan', 'title'] = 'ketua tim amdal'
df.loc[df['title'] == 'human capital officer in leading holidays company', 'title'] = 'human capital officer'
df.loc[df['title'] == 'sales project building material interior design manado', 'title'] = 'sales project building material'
df.loc[df['title'] == 'shipping logistic coordinator mandarin and english speaker', 'title'] = 'shipping logistic coordinator'
df.loc[df['title'] == 'accounting tax supervisor placement alam sutera', 'title'] = 'accounting tax supervisor'
df.loc[df['title'] == 'host live streaming tiktok tas dan baju', 'title'] = 'live streaming tiktok host'
df.loc[df['title'] == 'sales promotor spgspb terkeral multi finance company', 'title'] = 'sales promotor'
df.loc[df['title'] == 'aluminium door window designer european design', 'title'] = 'aluminium door window designer'
df.loc[df['title'] == 'admin quality control online shop fashion', 'title'] = 'admin quality control'
df.loc[df['title'] == 'administrasi ppic production planning inventory control', 'title'] = 'administrasi ppic'
df.loc[df['title'] == 'senior sales executive b2b b2g bandung', 'title'] = 'senior sales executive b2b'
df.loc[df['title'] == 'freelance guru liveclass dan pembuat soal', 'title'] = 'freelance guru'
df.loc[df['title'] == 'web development production information communication technology', 'title'] = 'web development production'
df.loc[df['title'] == 'surabaya sales executive freight forwarding exportimportair logistic', 'title'] = 'sales executive freight forwarding'
df.loc[df['title'] == 'konten kreator berpengalaman media tiktok instagram', 'title'] = 'konten kreator'
df.loc[df['title'] == 'keep account salesprinting and packaging mandarin', 'title'] = 'keep account sales'
df.loc[df['title'] == 'quality control manager solar panel wfo 660497', 'title'] = 'quality control manager'
df.loc[df['title'] == 'fullilment responsible specialist printing and packaging', 'title'] = 'fulfillment specialist'
df.loc[df['title'] == 'hr recruitment training employee relations engineer', 'title'] = 'hr recruitment engineer'
df.loc[df['title'] == 'relationship manager lending sme commercial banking ao', 'title'] = 'relationship manager lending'
df.loc[df['title'] == 'account manager transportation telecommunications industry jakarta wfo', 'title'] = 'account manager transportation'
df.loc[df['title'] == 'travel advisor in leading holidays company', 'title'] = 'travel advisor'
df.loc[df['title'] == 'full stack developer java script fulltime onsite', 'title'] = 'full stack developer'
df.loc[df['title'] == 'business development manager fluent english mandarin', 'title'] = 'business development manager'
df.loc[df['title'] == 'substitute primary prep classroom teacher maternity cover', 'title'] = 'substitute teacher'
df.loc[df['title'] == 'net developer it solutions services wfo jakarta', 'title'] = 'net developer'
df.loc[df['title'] == 'junior and high school teacher coach', 'title'] = 'junior high school teacher'
df.loc[df['title'] == 'sales marketing electric panel lv mv', 'title'] = 'sales marketing electric panel'
df.loc[df['title'] == 'senior tax and accounting staff experienced', 'title'] = 'senior tax accounting'
df.loc[df['title'] == 'marketing coordinator jakarta tangerang bogor area', 'title'] = 'marketing coordinator'
df.loc[df['title'] == 'ecommerce and social media platform operator', 'title'] = 'ecommerce social media operator'
df.loc[df['title'] == 'kepala departemen credit analyst modal kerja investasi', 'title'] = 'credit analyst'
df.loc[df['title'] == 'senior programmatic advertising trader jakarta indonesia', 'title'] = 'programmatic advertising trader'
df.loc[df['title'] == 'nlp natural language processing ai developer', 'title'] = 'nlp ai developer'
df.loc[df['title'] == 'salesman sepeda motor yamaha area maumere', 'title'] = 'salesman sepeda motor'
df.loc[df['title'] == 'villa assistant manager in seminyak bali', 'title'] = 'villa assistant manager'
df.loc[df['title'] == 'helper to the republic of benin', 'title'] = 'helper republic of benin'
df.loc[df['title'] == 'mandarin teacher part full time offline class', 'title'] = 'mandarin teacher'
df.loc[df['title'] == 'admin online shop instagram tiktok shopee tokopedia', 'title'] = 'admin online shop'
df.loc[df['title'] == 'home appliances senior product store promoter', 'title'] = 'home appliances promoter'
df.loc[df['title'] == 'supervisor marketing bahan bangunan dan alat pertanian', 'title'] = 'supervisor marketing'
df.loc[df['title'] == 'cook to the republic of benin', 'title'] = 'cook republic of benin'
df.loc[df['title'] == 'coal buyer seller specialist trader coal', 'title'] = 'coal buyer seller'
df.loc[df['title'] == 'junior merchandiser manager for parfume cosmetics', 'title'] = 'junior merchandiser'
df.loc[df['title'] == 'english teacher i can read alam sutera', 'title'] = 'english teacher'
df.loc[df['title'] == 'mandarin speakerme engineer manufacture machine automation', 'title'] = 'mandarin speaker engineer'
df.loc[df['title'] == 'technical sales representative tsr penempatan padang', 'title'] = 'technical sales representative'
df.loc[df['title'] == 'team leader sumbawa nusa tenggara barat', 'title'] = 'team leader sumbawa'
df.loc[df['title'] == 'asisten lapangan kebun kelapa sawit karet', 'title'] = 'asisten lapangan kebun'
df.loc[df['title'] == 'sales promotor spgspb terkeral multi finance company', 'title'] = 'sales promotor'
df.loc[df['title'] == 'sales executive modern traditional market toys specialist', 'title'] = 'sales executive toys'
df.loc[df['title'] == 'account officer microfinancing salatiga ungaran boyolali', 'title'] = 'account officer microfinancing'
df.loc[df['title'] == 'injection molding process engineer clients company', 'title'] = 'injection molding process engineer'
df.loc[df['title'] == 'financing specialist mandarin and english speaker', 'title'] = 'financing specialist'
df.loc[df['title'] == 'junior collection field fifgroup kota semarang ii', 'title'] = 'junior collection field'
df.loc[df['title'] == 'walk in interview bancassurance life consultant jabodetabek', 'title'] = 'bancassurance life consultant'
df.loc[df['title'] == 'sales marketing solar panel wfo 660495', 'title'] = 'sales marketing solar panel'
df.loc[df['title'] == 'business development manager logistics freight forwarding b112350', 'title'] = 'business development manager logistics'
df.loc[df['title'] == 'human resource general affair hr ga', 'title'] = 'human resource general affair'
df.loc[df['title'] == 'digital sales manager digital marketing creative agency', 'title'] = 'digital sales manager'
df.loc[df['title'] == 'senior consultant legal tax advisory', 'title'] = 'senior consultant legal'
df.loc[df['title'] == 'technical support untuk hardware printer dan mesin fotocopy', 'title'] = 'technical support hardware'
df.loc[df['title'] == 'business development freight forwarding ksa saudia arabia', 'title'] = 'business development freight forwarding'
df.loc[df['title'] == 'customer service executivept properti di indonesia', 'title'] = 'customer service executive'
df.loc[df['title'] == 'security guard', 'title'] = 'security guard'
df.loc[df['title'] == 'senior hr manager greenfield project consultancy', 'title'] = 'senior hr manager'
df.loc[df['title'] == 'business process analyst area jabodetabek', 'title'] = 'business process analyst'
df.loc[df['title'] == 'assist project supervisor', 'title'] = 'assist project supervisor'
df.loc[df['title'] == 'desain produk produk engineering designer', 'title'] = 'produk engineering designer'
df.loc[df['title'] == 'account executive for bancassurance agent', 'title'] = 'account executive bancassurance'

In [30]:
#normaliasisi title lebih dari 5 kata
df.loc[df['title'] == 'praktek dokter spesialis jakarta bekasi dan makassar', 'title'] = 'dokter spesialis'
df.loc[df['title'] == 'business development manager trading raw material feed', 'title'] = 'business development manager'
df.loc[df['title'] == 'field collection kolektor lapangan area demak', 'title'] = 'field collector'
df.loc[df['title'] == 'sales executive pipa ac air conditioner', 'title'] = 'sales executive'
df.loc[df['title'] == 'presales consultant cybersecurity industry based in jakarta', 'title'] = 'presales consultant'
df.loc[df['title'] == 'head of laboratory water food internal lab', 'title'] = 'head of laboratory'
df.loc[df['title'] == 'host live online marketing customer service', 'title'] = 'live online host'
df.loc[df['title'] == 'branch manager dealer byd mandarin speaker', 'title'] = 'branch manager'
df.loc[df['title'] == 'performance digital marketer digital platform advertiser', 'title'] = 'digital marketer'
df.loc[df['title'] == 'site supervisor ftth project lampung dan banjarbaru', 'title'] = 'site supervisor'
df.loc[df['title'] == 'data center operations engineer jakarta 247 shift', 'title'] = 'data center engineer'
df.loc[df['title'] == 'coal buyer seller assistance trader coal', 'title'] = 'coal trader'
df.loc[df['title'] == 'marketing assistant manager finance leasing b111655', 'title'] = 'marketing assistant'
df.loc[df['title'] == 'drafter 2d teknik sipil arsitektur di bali', 'title'] = 'drafter 2D'
df.loc[df['title'] == 'business development tiktok kol specialist 50 vacancy', 'title'] = 'business development tiktok'
df.loc[df['title'] == 'qc manager feedmill balaraja tangerang banten', 'title'] = 'qc manager'
df.loc[df['title'] == 'japanese speaker hrga manager machinery cikarang a112975', 'title'] = 'hrga manager'
df.loc[df['title'] == 'senior sales executive b2b b2g surabaya', 'title'] = 'senior sales executive'
df.loc[df['title'] == 'marketing emkl ekspedisi muat kapal laut', 'title'] = 'marketing emkl'
df.loc[df['title'] == 'teknisi konstruksi aluminium welding bending assembling', 'title'] = 'teknisi konstruksi'
df.loc[df['title'] == 'sales operation area supervisor premium vehicle', 'title'] = 'sales operation supervisor'
df.loc[df['title'] == 'welder to the republic of benin', 'title'] = 'welder'
df.loc[df['title'] == 'human resource general affair hr ga', 'title'] = 'hr general affair'
df.loc[df['title'] == 'finance accounting and tax japanese speaker', 'title'] = 'finance and tax'
df.loc[df['title'] == 'mechanics to the republic of benin', 'title'] = 'mechanics'
df.loc[df['title'] == 'accounts finance executive senior accounts finance executive', 'title'] = 'accounts executive'
df.loc[df['title'] == 'staff ppc manufaktur offset paper packaging', 'title'] = 'ppc staff'
df.loc[df['title'] == 'operations officer in leading holidays company', 'title'] = 'operations officer'
df.loc[df['title'] == 'general manager finance accounting and tax', 'title'] = 'general manager finance'
df.loc[df['title'] == 'retail store spv realme official store', 'title'] = 'retail store spv'
df.loc[df['title'] == 'senior operations executive import export logistics', 'title'] = 'operations executive'
df.loc[df['title'] == 'finance supervisor mandarin speaker logistics a112358', 'title'] = 'finance supervisor'
df.loc[df['title'] == 'kepala dealer semarang pemalang pekalongan tegal brebes', 'title'] = 'kepala dealer'
df.loc[df['title'] == 'assistant for director mandarin and english speaker', 'title'] = 'assistant director'
df.loc[df['title'] == 'payroll country owner indonesia payroll implementation', 'title'] = 'payroll implementation'
df.loc[df['title'] == 'research and development manager food technology carrageenan', 'title'] = 'rd manager'
df.loc[df['title'] == 'beauty consultant sales promotion counter surabaya', 'title'] = 'beauty consultant'
df.loc[df['title'] == 'marketing specialist digital marketing manufacturing wfo 660190', 'title'] = 'marketing specialist'
df.loc[df['title'] == 'vapeecig se asia regional directorsalary bonuses', 'title'] = 'regional director'
df.loc[df['title'] == 'premier bancassurance life consultant jakarta pusat', 'title'] = 'bancassurance consultant'
df.loc[df['title'] == 'manager finance accounting and tax fat', 'title'] = 'finance accounting manager'
df.loc[df['title'] == 'business development manager electric vehicle ev', 'title'] = 'business development ev'
df.loc[df['title'] == 'business strategic and development sr staff', 'title'] = 'business development sr'
df.loc[df['title'] == 'financial advisor area bali denpasar badung', 'title'] = 'financial advisor bali'
df.loc[df['title'] == 'applied science technician in sales and marketing', 'title'] = 'applied science technician'
df.loc[df['title'] == 'myp math teacher prefer ib experience', 'title'] = 'math teacher'
df.loc[df['title'] == 'performance management total rewards asst manager', 'title'] = 'performance management assistant'
df.loc[df['title'] == 'mandarin speaker chinese speaker consultant service', 'title'] = 'mandarin consultant'
df.loc[df['title'] == 'senior relationship officer sro kc mataram', 'title'] = 'relationship officer'
df.loc[df['title'] == 'sales export staff automotive cikarang b110266', 'title'] = 'sales export staff'
df.loc[df['title'] == 'field collector cirebon indramayu dan kuningan', 'title'] = 'field collector'
df.loc[df['title'] == 'agen independen petugas freelance penerima pendaftaran kkgi', 'title'] = 'agen independen'
df.loc[df['title'] == 'asisten manager finansial financial accountant assistant', 'title'] = 'financial assistant'
df.loc[df['title'] == 'financial advisor area timika dan nabire', 'title'] = 'financial advisor timika'
df.loc[df['title'] == 'kepala produksi manufaktur pipa pvc hdpe', 'title'] = 'kepala produksi'
df.loc[df['title'] == 'teknisi mechanical ac listrik dan civil', 'title'] = 'teknisi mechanical'
df.loc[df['title'] == 'sales assistant manager packaging bekasi b112881', 'title'] = 'sales assistant manager'
df.loc[df['title'] == 'head of business development sales head', 'title'] = 'head of business development'
df.loc[df['title'] == 'rd staff refrigeration and air conditioning engineering', 'title'] = 'rd staff'
df.loc[df['title'] == 'kolektor lapangan area pasuruan jawa timur', 'title'] = 'field collector'
df.loc[df['title'] == 'me engineer supervisor manufacture karawang b112890', 'title'] = 'me engineer supervisor'
df.loc[df['title'] == 'trainer doctor for medical aesthetic company', 'title'] = 'trainer doctor'
df.loc[df['title'] == 'fleet manager operation manager tug barge', 'title'] = 'fleet manager'
df.loc[df['title'] == 'financial advisor area jakarta selatan sudirman', 'title'] = 'financial advisor'
df.loc[df['title'] == 'graphic design staff manufacture bekasi b112339', 'title'] = 'graphic design staff'
df.loc[df['title'] == 'product executive for art hobbyistprofessional product', 'title'] = 'product executive'
df.loc[df['title'] == 'project manager piping dan jalan raya', 'title'] = 'project manager'
df.loc[df['title'] == 'smd marketing yogyakarta meliputi jogjakulon progo gunungkidul', 'title'] = 'smd marketing'
df.loc[df['title'] == 'bag operator mesin produksi teknisi mesin', 'title'] = 'bag operator'
df.loc[df['title'] == 'executive secretary mandarin speaker manufacture bogor a112406', 'title'] = 'executive secretary'
df.loc[df['title'] == 'senior salesmarketing medical representatif alat kesehatan', 'title'] = 'senior sales marketing'
df.loc[df['title'] == 'graphic designer and social media specialist', 'title'] = 'graphic designer'
df.loc[df['title'] == 'manager hrga pt corindo amagi putra', 'title'] = 'hrga manager'
df.loc[df['title'] == 'teknik sipil jalan raya dan piping', 'title'] = 'teknik sipil'
df.loc[df['title'] == 'vp of sales fttx data center', 'title'] = 'vp of sales'
df.loc[df['title'] == 'general administration and ga general affair', 'title'] = 'general affair'
df.loc[df['title'] == 'retail business development operation manager fashion retail', 'title'] = 'retail business manager'
df.loc[df['title'] == 'produk direct selling team leader jakarta', 'title'] = 'direct selling team leader'
df.loc[df['title'] == 'finance and accounting supervisor medan b112624', 'title'] = 'finance and accounting supervisor'
df.loc[df['title'] == 'finance marketing sales supervisor bekasi b111872', 'title'] = 'finance marketing supervisor'
df.loc[df['title'] == 'teknisi operasional customer service area bali', 'title'] = 'customer service technician'
df.loc[df['title'] == 'executive sekretaris senior sekretaris senior admin assistant', 'title'] = 'executive secretary'
df.loc[df['title'] == 'marketing digital strategi social media marketing', 'title'] = 'digital marketing strategist'
df.loc[df['title'] == 'regional head production supplier', 'title'] = 'regional head production'
df.loc[df['title'] == 'strategic sourcing purchasing manager supplier quality', 'title'] = 'strategic sourcing manager'
df.loc[df['title'] == 'staff supervisor abc department', 'title'] = 'staff supervisor'

In [31]:
#normalisasi title denganlebih dari 5 kata
df.loc[df['title'] == 'branch manager forwarding logistics makasar south sulawesi', 'title'] = 'branch manager logistics'
df.loc[df['title'] == 'maintenance assistant manager manufacture karawang b112669', 'title'] = 'maintenance assistant manager'
df.loc[df['title'] == 'vendor management operation collection english speaker', 'title'] = 'vendor management operation'
df.loc[df['title'] == 'hr cum admin executive mandarin speaker', 'title'] = 'hr admin executive'
df.loc[df['title'] == 'japanese speaker sales staff trading a111024', 'title'] = 'japanese speaker sales staff'
df.loc[df['title'] == 'regional sales pompa air dan bahan bangunan', 'title'] = 'regional sales'
df.loc[df['title'] == 'pricing staff for fresh graduate jakarta placement', 'title'] = 'pricing staff'
df.loc[df['title'] == 'tiktok content creator video sales content', 'title'] = 'tiktok content creator'
df.loc[df['title'] == 'sales sparepart mobil dan motor area cirebon', 'title'] = 'sales sparepart'
df.loc[df['title'] == 'sales area yogyakarta mur dan baut', 'title'] = 'sales area'
df.loc[df['title'] == 'business manager nusa tenggara barat seluruh lombok', 'title'] = 'business manager'
df.loc[df['title'] == 'sales manager for software erp sap b1', 'title'] = 'sales manager software'
df.loc[df['title'] == 'financial advisor cirebon majalengka ciledug dan sekitarnya', 'title'] = 'financial advisor'
df.loc[df['title'] == 'business development executive fashion vape store industry', 'title'] = 'business development executive'
df.loc[df['title'] == 'call center eksekutif telesales sales consultant', 'title'] = 'call center executive'
df.loc[df['title'] == 'administrasi pengembangan bisnis dan cetak kartu', 'title'] = 'administrasi pengembangan bisnis'
df.loc[df['title'] == 'channel assistant manager medical equipment b108306', 'title'] = 'channel assistant manager'
df.loc[df['title'] == 'content creator digital marketing social media specialist', 'title'] = 'content creator digital marketing'
df.loc[df['title'] == 'trade marketing spv modern trade fmcg company', 'title'] = 'trade marketing supervisor'
df.loc[df['title'] == 'pipeline infrastructure sales mandarin speaker trading a110101', 'title'] = 'pipeline infrastructure sales'
df.loc[df['title'] == 'sales executive account manager food service', 'title'] = 'sales executive'
df.loc[df['title'] == 'head chef kota sorongpapua barat daya', 'title'] = 'head chef'
df.loc[df['title'] == 'staff ppic production planning inventory control', 'title'] = 'staff ppic'
df.loc[df['title'] == 'accounting cost control supervisor pik 2', 'title'] = 'accounting cost control supervisor'
df.loc[df['title'] == 'fx account manager sales support jakarta', 'title'] = 'fx account manager'
df.loc[df['title'] == 'sales assistant jewelry lippo mall puri', 'title'] = 'sales assistant'
df.loc[df['title'] == 'finance accounting and tax mandarin speaker', 'title'] = 'finance accounting and tax'
df.loc[df['title'] == 'personal assistant japanese sepaker transit oriented development', 'title'] = 'personal assistant'
df.loc[df['title'] == 'english customer service urgent hiring yogyakarta', 'title'] = 'english customer service'
df.loc[df['title'] == 'pengawas lapangan project supervisor arsitek bali', 'title'] = 'project supervisor'
df.loc[df['title'] == 'business development english speaker fresh graduate', 'title'] = 'business development'
df.loc[df['title'] == 'area sales manajer jabodetabek dan kalimantan', 'title'] = 'area sales manager'
df.loc[df['title'] == 'area sales manager fmcg kalimantan b110233', 'title'] = 'area sales manager fmcg'
df.loc[df['title'] == 'sales representatif pelumas otomotif channel b2c', 'title'] = 'sales representative'
df.loc[df['title'] == 'finance account receivable spesialist accounting supervisior', 'title'] = 'finance account receivable'
df.loc[df['title'] == 'application engineer audio visual cfs division', 'title'] = 'application engineer'
df.loc[df['title'] == 'japanese speaker luxury goods appraiser retail a112766', 'title'] = 'japanese speaker luxury goods'
df.loc[df['title'] == 'long term mine planning engineer coal', 'title'] = 'long term mine planning engineer'
df.loc[df['title'] == 'sales and marketing in shipping agency', 'title'] = 'sales and marketing'
df.loc[df['title'] == 'presales consultant sap erp idr 80k gross', 'title'] = 'presales consultant'
df.loc[df['title'] == 'relationship manager priority funding bank surabaya b113063', 'title'] = 'relationship manager'
df.loc[df['title'] == 'direct sales bca finance penempatan lubuklinggau palembang', 'title'] = 'direct sales'
df.loc[df['title'] == 'ecommerce listing ota staff bali indonesia', 'title'] = 'ecommerce listing ota staff'
df.loc[df['title'] == 'financial spesialist bancassurance lubuk linggau bengkulu', 'title'] = 'financial specialist bancassurance'
df.loc[df['title'] == 'mekanik alat berat mekanik task force', 'title'] = 'mekanik alat berat'
df.loc[df['title'] == 'penerjemah bahasa dan general affair mandarin', 'title'] = 'penerjemah bahasa'
df.loc[df['title'] == 'deputy general manager sales b2b marineminingfleet', 'title'] = 'deputy general manager sales'
df.loc[df['title'] == 'sales admin 3 bulan pengganti cuti lahiran', 'title'] = 'sales admin'
df.loc[df['title'] == 'bancassurance advisor syariah jawa tengah yogyasolotegal', 'title'] = 'bancassurance advisor'
df.loc[df['title'] == 'finance accounting and tax fat officer', 'title'] = 'finance accounting tax officer'
df.loc[df['title'] == 'hr ir assistant manager manufacture cikarang wfo', 'title'] = 'hr ir assistant manager'
df.loc[df['title'] == 'qantity surveyor interior design firm bali', 'title'] = 'quantity surveyor'
df.loc[df['title'] == 'plant assistant manager garment or textile industry', 'title'] = 'plant assistant manager'
df.loc[df['title'] == 'personal driver supir kantor dan pribadi', 'title'] = 'personal driver'
df.loc[df['title'] == 'hrga supervisor automotive manufacture cikarang id 658172', 'title'] = 'hrga supervisor'
df.loc[df['title'] == 'staff export import ppjk drafter pib peb', 'title'] = 'staff export import'
df.loc[df['title'] == 'tax supervisor tax manager english speaker', 'title'] = 'tax supervisor'
df.loc[df['title'] == 'penunjang pengoperasian onshore receiving facilities orf', 'title'] = 'onshore receiving facilities'
df.loc[df['title'] == 'bd admin senior staff trading c112786', 'title'] = 'bd admin senior staff'
df.loc[df['title'] == 'assistant and translator ceo mandarin speaking', 'title'] = 'assistant translator ceo'
df.loc[df['title'] == 'asisten refraksi optisien asro sales counter optik', 'title'] = 'asisten refraksi optisien'
df.loc[df['title'] == 'japanese speaker hr manager hospitality a110761', 'title'] = 'japanese speaker hr manager'
df.loc[df['title'] == 'early years teacher for july 2025', 'title'] = 'early years teacher'
df.loc[df['title'] == 'ticketing staff english galileo and sabre experience', 'title'] = 'ticketing staff'
df.loc[df['title'] == 'it infrastructure engineer cilegon it consulting a109844', 'title'] = 'it infrastructure engineer'
df.loc[df['title'] == 'remedial officer collection bali dan nusa tenggara', 'title'] = 'remedial officer collection'
df.loc[df['title'] == 'japanese speaker restaurant staffleader restaurant a112246', 'title'] = 'japanese speaker restaurant staff'
df.loc[df['title'] == 'field collection kolektor lapangan area purwakarta', 'title'] = 'field collection'
df.loc[df['title'] == 'sales supervisor tire ban arvia jakarta', 'title'] = 'sales supervisor tire'
df.loc[df['title'] == 'id business development executive insurance channel', 'title'] = 'business development executive'
df.loc[df['title'] == 'hrd barge pontoon shipping company experienced only', 'title'] = 'hrd barge pontoon'
df.loc[df['title'] == 'assistant manager finance accounting tax bekasi manufacturing', 'title'] = 'assistant manager finance'
df.loc[df['title'] == 'staff akunting dan pajak wilayah medan', 'title'] = 'staff akunting'
df.loc[df['title'] == 'spa therapist hotel yogyakarta bali', 'title'] = 'spa therapist hotel'
df.loc[df['title'] == 'network engineer english speaker west jakarta', 'title'] = 'network engineer'
df.loc[df['title'] == 'hrga spv assistant manager manufacture', 'title'] = 'hrga supervisor'
df.loc[df['title'] == 'drilling engineer gas energy project', 'title'] = 'drilling engineer'
df.loc[df['title'] == 'financial consultant capital market property', 'title'] = 'financial consultant'
df.loc[df['title'] == 'e commerce assistant web admin e commerce management', 'title'] = 'e commerce assistant'

In [32]:
#normalisasi title lebih dari 5 kata
df.loc[df['title'] == 'sales executive area manado selatanmanado utara', 'title'] = 'sales executive'
df.loc[df['title'] == 'field collection kolektor lapangan area boyolali', 'title'] = 'field collection'
df.loc[df['title'] == 'sales medical devices ivd product kalimantan barat', 'title'] = 'sales medical devices'
df.loc[df['title'] == 'senior sales horeca distributor fb kitchen equipment', 'title'] = 'senior sales horeca'
df.loc[df['title'] == 'branch manager with function head of sales', 'title'] = 'branch manager'
df.loc[df['title'] == 'net system analyst sa for application programming', 'title'] = 'net system analyst'
df.loc[df['title'] == 'building management junior executive assistant manager', 'title'] = 'building management'
df.loc[df['title'] == 'assistan to the chairman of the company', 'title'] = 'assistant chairman'
df.loc[df['title'] == 'sales marketing gravure ink supervisor level', 'title'] = 'sales marketing'
df.loc[df['title'] == 'japanese speaker sales staff logistics a113207', 'title'] = 'sales staff logistics'
df.loc[df['title'] == 'junior senior cruise tour sales consultant', 'title'] = 'cruise tour sales'
df.loc[df['title'] == 'agency relation denpasar gianyar tabanan buleleng', 'title'] = 'agency relation'
df.loc[df['title'] == 'kerja remote freelance wfh host live streaming', 'title'] = 'remote freelance host'
df.loc[df['title'] == 'therapist sulam alis eyeliner dan bibir', 'title'] = 'therapist sulam'
df.loc[df['title'] == 'sr manager of hr and adm', 'title'] = 'sr manager hr'
df.loc[df['title'] == 'kolektor lapangan area jember jawa timur', 'title'] = 'field collection'
df.loc[df['title'] == 'hse and compliance manager toygarmentfootwear remote', 'title'] = 'hse compliance manager'
df.loc[df['title'] == 'it data warehouse engineer assistant manager', 'title'] = 'data warehouse engineer'
df.loc[df['title'] == 'crane operator to the republic of benin', 'title'] = 'crane operator'
df.loc[df['title'] == 'japanese speaker n3n1 fb company jakarta', 'title'] = 'japanese speaker'
df.loc[df['title'] == 'asset management specialist data center operations', 'title'] = 'asset management specialist'
df.loc[df['title'] == 'team leader relationship manager funding deposito', 'title'] = 'team leader relationship'
df.loc[df['title'] == 'premier bancassurance life consultant bandar lampung', 'title'] = 'bancassurance consultant'
df.loc[df['title'] == 'operations supervisor for travel mandarin speaker', 'title'] = 'operations supervisor'
df.loc[df['title'] == 'it business analyst treasury bankingfinancial services', 'title'] = 'it business analyst'
df.loc[df['title'] == 'sales assistant manager automotive manufacture karawang wfo', 'title'] = 'sales assistant manager'
df.loc[df['title'] == 'financial advisor area tanjung priuk jakut', 'title'] = 'financial advisor'
df.loc[df['title'] == 'sales fitness consultan cinere depok tangsel', 'title'] = 'sales fitness consultant'
df.loc[df['title'] == 'public relations branding specialist fresh graduate', 'title'] = 'public relations specialist'
df.loc[df['title'] == 'financial advisor area jakarta utara pluit', 'title'] = 'financial advisor'
df.loc[df['title'] == 'financial advisor area jakarta barat kyai tapa', 'title'] = 'financial advisor'
df.loc[df['title'] == 'manager logistik palm oil company refinery fractionation', 'title'] = 'logistik manager'
df.loc[df['title'] == 'senior manager mam major account manager', 'title'] = 'senior manager'
df.loc[df['title'] == 'oem sales assistant manager automotive trading b112959', 'title'] = 'oem sales assistant manager'
df.loc[df['title'] == 'internal audit chiefassistant manager manufacture cikampek c112498', 'title'] = 'internal audit manager'
df.loc[df['title'] == 'walk in interview bancassurance life consultant magelang', 'title'] = 'bancassurance consultant'
df.loc[df['title'] == 'shift facilities technician ac refelectrical batam', 'title'] = 'shift facilities technician'
df.loc[df['title'] == 'hr assistant manager services cengkareng c108350', 'title'] = 'hr assistant manager'
df.loc[df['title'] == 'admin sales for it software division', 'title'] = 'admin sales'
df.loc[df['title'] == 'field collection kolektor lapangan area cirebon majalengkategal', 'title'] = 'field collection'
df.loc[df['title'] == 'finance admin executive based in jakarta selatan', 'title'] = 'finance admin executive'
df.loc[df['title'] == 'field collection kolektor lapangan area solo banjarsari', 'title'] = 'field collection'
df.loc[df['title'] == 'sales officer penempatan kediri dan surabaya', 'title'] = 'sales officer'
df.loc[df['title'] == 'part planner mandarin speaker machinery a110043', 'title'] = 'part planner'
df.loc[df['title'] == 'bancassurance specialist semarang pekalongan tegal cepu jepara', 'title'] = 'bancassurance specialist'
df.loc[df['title'] == 'financial advisor area jakarta barat daan mogot', 'title'] = 'financial advisor'
df.loc[df['title'] == 'junior accountant manufacturing industry remote work', 'title'] = 'junior accountant'
df.loc[df['title'] == 'maintenance reliability onshore receiving facilities orf', 'title'] = 'maintenance reliability'
df.loc[df['title'] == 'finance accounting tax staff at jakarta', 'title'] = 'finance tax staff'
df.loc[df['title'] == 'ppiclogistics manager automotive manufacture cikarang id 658861', 'title'] = 'ppic logistics manager'
df.loc[df['title'] == 'japanese speaker ga staff manufacturing tangerang a113078', 'title'] = 'japanese speaker ga staff'
df.loc[df['title'] == 'hp executive assistant account officer surabaya area', 'title'] = 'hp executive assistant'
df.loc[df['title'] == 'business development manager personal care ingredients', 'title'] = 'business development manager'
df.loc[df['title'] == 'premier bancassurance life consultant jakarta kemayoran', 'title'] = 'bancassurance consultant'
df.loc[df['title'] == 'marketing verification officer js mvo solo', 'title'] = 'marketing verification officer'
df.loc[df['title'] == 'store managerkepala toko kudus semarang sukabumi makassar', 'title'] = 'store manager'
df.loc[df['title'] == 'english teacher phonics reading specialist efl conversation', 'title'] = 'english teacher'
df.loc[df['title'] == 'teknik listrik mekanik boiler dan wtp', 'title'] = 'teknik listrik mekanik'
df.loc[df['title'] == 'auditiso certification officer building material surabaya b113166', 'title'] = 'audit certification officer'
df.loc[df['title'] == 'quantity surveyor qs sipil dan mep', 'title'] = 'quantity surveyor'
df.loc[df['title'] == 'distribution collection palembang pekanbaru manado aceh', 'title'] = 'distribution collection'
df.loc[df['title'] == 'quality control staff manufacture karawang b112356', 'title'] = 'quality control staff'
df.loc[df['title'] == 'full time secretary social media specialist', 'title'] = 'full time secretary'
df.loc[df['title'] == 'premier bancassurance life consultant malangtapal kuda', 'title'] = 'bancassurance consultant'
df.loc[df['title'] == 'admin sales for crm software division salesforce', 'title'] = 'admin sales crm'
df.loc[df['title'] == 'pengawas proyek restoran caffe mall admin', 'title'] = 'pengawas proyek'
df.loc[df['title'] == 'sales executive medical devices jakarta dan sekitarnya', 'title'] = 'sales executive medical devices'
df.loc[df['title'] == 'it system support junior staff trading a112186', 'title'] = 'it system support'
df.loc[df['title'] == 'student advisor customer advisor progress advisor', 'title'] = 'student advisor'
df.loc[df['title'] == 'sales staff trading plastic polymer resin b112184', 'title'] = 'sales staff trading'
df.loc[df['title'] == 'arsitek estimator sipil struktur bq rab', 'title'] = 'arsitek estimator'
df.loc[df['title'] == 'brand and digtal marketing manager surabaya', 'title'] = 'brand marketing manager'
df.loc[df['title'] == 'human capital and general affair manager', 'title'] = 'human capital manager'
df.loc[df['title'] == 'customs clearance logistics specialist logistics c112348', 'title'] = 'customs clearance specialist'
df.loc[df['title'] == 'shipment operations logistics supervisor for forwarder', 'title'] = 'shipment operations supervisor'
df.loc[df['title'] == 'management trainee sales jakarta surabaya', 'title'] = 'management trainee sales'
df.loc[df['title'] == 'event specialist hospitality industry area medan', 'title'] = 'event specialist'
df.loc[df['title'] == 'tax supervisor controller sr accountant', 'title'] = 'tax supervisor'
df.loc[df['title'] == 'quantity surveyor sr estimator sipil bq rab', 'title'] = 'quantity surveyor estimator'
df.loc[df['title'] == 'presales consultant new business division', 'title'] = 'presales consultant'
df.loc[df['title'] == 'field collection collector part time work sabtu minggu', 'title'] = 'field collection collector'
df.loc[df['title'] == 'hr personnel assistant sr', 'title'] = 'hr personnel assistant'
df.loc[df['title'] == 'fullstack javascript developer', 'title'] = 'fullstack javascript developer'
df.loc[df['title'] == 'quality control supervisor', 'title'] = 'quality control supervisor'
df.loc[df['title'] == 'health care consultant medical device specialist', 'title'] = 'health care consultant'
df.loc[df['title'] == 'management trainee the valley jakarta utara', 'title'] = 'management trainee'
df.loc[df['title'] == 'developer senior fullstack front end', 'title'] = 'senior fullstack developer'
df.loc[df['title'] == 'digital marketing campaign specialist jakarta', 'title'] = 'digital marketing specialist'
df.loc[df['title'] == 'training manager lms corporate', 'title'] = 'training manager'
df.loc[df['title'] == 'assistant store manager malang area', 'title'] = 'assistant store manager'
df.loc[df['title'] == 'community engagement specialisthuman resource development', 'title'] = 'community engagement specialist'
df.loc[df['title'] == 'sales assistant supervisor indonesia territory', 'title'] = 'sales assistant supervisor'
df.loc[df['title'] == 'financial controller', 'title'] = 'financial controller'
df.loc[df['title'] == 'social media marketing coordinator', 'title'] = 'social media coordinator'

In [33]:
#normalisasi title dengan lebih dari 5 kata
df.loc[df['title'] == 'japanese speaker hrga staff chemical karawang a112341', 'title'] = 'japanese speaker hrga staff'
df.loc[df['title'] == 'b2b sales manager enterprise training product', 'title'] = 'b2b sales manager'
df.loc[df['title'] == 'team lead sales surabaya malang madiun', 'title'] = 'team lead sales'
df.loc[df['title'] == 'hotel manager place in lampung selatan', 'title'] = 'hotel manager'
df.loc[df['title'] == 'national sales manager racing parts 2w', 'title'] = 'national sales manager'
df.loc[df['title'] == 'kabag teknisi mesin laminasi terpal berpengalaman', 'title'] = 'teknisi mesin laminasi'
df.loc[df['title'] == 'sales motoris jakarta tangerang dan bekasi', 'title'] = 'sales motoris'
df.loc[df['title'] == 'digital marketing hanya utk pengalaman seo ads', 'title'] = 'digital marketing'
df.loc[df['title'] == 'customer success specialist sport tech startup', 'title'] = 'customer success specialist'
df.loc[df['title'] == 'english teachers needed for ef malang', 'title'] = 'english teacher'
df.loc[df['title'] == 'marketing agency pembiayaan bpkb kendaraan semarang', 'title'] = 'marketing agency'
df.loc[df['title'] == 'finance accounting tax staff mandarin speaker', 'title'] = 'finance accounting tax staff'
df.loc[df['title'] == 'senior finance accounting and tax english speaker', 'title'] = 'senior finance accounting'
df.loc[df['title'] == 'bancassurance spesialist denpasar ntt ntb bali', 'title'] = 'bancassurance specialist'
df.loc[df['title'] == 'search engine optimization specialist fresh graduate', 'title'] = 'seo specialist'
df.loc[df['title'] == 'sap consultant trainee fresh graduate program', 'title'] = 'sap consultant trainee'
df.loc[df['title'] == 'long term mine planning engineer supervisor coal', 'title'] = 'mine planning engineer'
df.loc[df['title'] == 'personal assistant to manager mandarin speaker', 'title'] = 'personal assistant'
df.loc[df['title'] == 'financial advisor area jakarta selatan fatmawati', 'title'] = 'financial advisor'
df.loc[df['title'] == 'it chief application development manufacture a112118', 'title'] = 'it chief application development'
df.loc[df['title'] == 'hrga accounting staff sr staff spv', 'title'] = 'hrga accounting staff'
df.loc[df['title'] == 'it data center hardware and software', 'title'] = 'it data center'
df.loc[df['title'] == 'finance accounting tax manager fat trading', 'title'] = 'finance accounting tax manager'
df.loc[df['title'] == 'sales supervisor air minum dalam kemasan amdk', 'title'] = 'sales supervisor'
df.loc[df['title'] == 'kepala bagian waste water wwt wwtp', 'title'] = 'kepala bagian waste water'
df.loc[df['title'] == 'apoteker apotek k24 ciledug kabupaten cirebon', 'title'] = 'apoteker apotek'
df.loc[df['title'] == 'relationship manager priority funding bank medan b113062', 'title'] = 'relationship manager'
df.loc[df['title'] == 'system analyst it consultant 3 positions', 'title'] = 'system analyst'
df.loc[df['title'] == 'tax associate contract based 6 months', 'title'] = 'tax associate'
df.loc[df['title'] == 'rd supervisor manufacture foods cikarang b112581', 'title'] = 'rd supervisor'
df.loc[df['title'] == 'finance accounting supervisor cikarang manufacture id 657656', 'title'] = 'finance accounting supervisor'
df.loc[df['title'] == 'logistic manager logistics service cikarang id 611065', 'title'] = 'logistic manager'
df.loc[df['title'] == 'back end asset management beam karawang cikampek', 'title'] = 'back end asset management'
df.loc[df['title'] == 'sales executive area jakarta tangerang bogor', 'title'] = 'sales executive'
df.loc[df['title'] == 'legal officer mandarin speaker electronic industry', 'title'] = 'legal officer'
df.loc[df['title'] == 'bancassurance life consultant samarinda bontang sangatta tenggarong', 'title'] = 'bancassurance life consultant'
df.loc[df['title'] == 'japanese speaker hrga accounting staff trading a112303', 'title'] = 'japanese speaker hrga accounting staff'
df.loc[df['title'] == 'tenaga teknis kefarmasian apotek k24 leles garut', 'title'] = 'tenaga teknis kefarmasian'
df.loc[df['title'] == 'customer service mandarin freight forwading company', 'title'] = 'customer service'
df.loc[df['title'] == 'sales percetakan offset operator mesin gto', 'title'] = 'sales operator mesin gto'
df.loc[df['title'] == 'dokter estetika leveine aesthetic clinic surabaya', 'title'] = 'dokter estetika'
df.loc[df['title'] == 'sustainability research manager agriculture lampung b102235', 'title'] = 'sustainability research manager'
df.loc[df['title'] == 'social media manager only bali based', 'title'] = 'social media manager'
df.loc[df['title'] == 'japanese speaker sales staff trading a111805', 'title'] = 'japanese speaker sales staff'
df.loc[df['title'] == 'premier bancassurance life consultant cikarang karawang', 'title'] = 'bancassurance life consultant'
df.loc[df['title'] == 'japanese speaker sales staffsupervisor insurance a112365', 'title'] = 'japanese speaker sales supervisor'
df.loc[df['title'] == 'secretary to board of directors urgent', 'title'] = 'secretary to board of directors'
df.loc[df['title'] == 'nurse_rs emc pulomas icu operating theater hemodialysis', 'title'] = 'nurse'
df.loc[df['title'] == 'business manager kepala cabang pemalang pekalongan kendal', 'title'] = 'business manager'
df.loc[df['title'] == 'branch manager lampung automotive wfo id 654766', 'title'] = 'branch manager'
df.loc[df['title'] == 'hr assistant managermanager services tangerang c113151', 'title'] = 'hr assistant manager'
df.loc[df['title'] == 'product development supervisor skincare and cosmetic', 'title'] = 'product development supervisor'
df.loc[df['title'] == 'sales manager it solution and infratstructure provider', 'title'] = 'sales manager'
df.loc[df['title'] == 'collection coordinator supervisor_kary tetap area aek kanopan', 'title'] = 'collection coordinator'
df.loc[df['title'] == 'marketing event planner kota sorongpapua barat daya', 'title'] = 'marketing event planner'
df.loc[df['title'] == 'international global account manager furniture tangerang', 'title'] = 'international global account manager'
df.loc[df['title'] == 'retail customer service bali batch iii 2024', 'title'] = 'retail customer service'
df.loc[df['title'] == 'dept head hcgs site kalimantan timur', 'title'] = 'dept head hcgs site'
df.loc[df['title'] == 'personal assistant mandarin speaker urgently needed', 'title'] = 'personal assistant'
df.loc[df['title'] == 'senior engineer for civil geotechnic marine mechanical', 'title'] = 'senior engineer'
df.loc[df['title'] == 'customer relationship officer mandarin speaker logistics a109723', 'title'] = 'customer relationship officer'
df.loc[df['title'] == 'customer service staff mandarin speaker logistics a113070', 'title'] = 'customer service staff'
df.loc[df['title'] == 'tenaga teknis kefarmasian apotek k24 ciledug cirebon', 'title'] = 'tenaga teknis kefarmasian'
df.loc[df['title'] == 'full stack developer reactjs and net', 'title'] = 'full stack developer'
df.loc[df['title'] == 'procurement section program officer ngo c112618', 'title'] = 'procurement section officer'
df.loc[df['title'] == 'kepala store mur dan baut cabang surakarta', 'title'] = 'kepala store'
df.loc[df['title'] == 'financial advisorbancassurance area bandung kbp cianjur sukabumi', 'title'] = 'financial advisor bancassurance'
df.loc[df['title'] == 'bancassurance life consultant pontianak kuburaya dan singkawang', 'title'] = 'bancassurance life consultant'
df.loc[df['title'] == 'sales advisor spg spb jayapura papua', 'title'] = 'sales advisor'
df.loc[df['title'] == 'cost accounting tax staff penempatan tangerang', 'title'] = 'cost accounting tax staff'
df.loc[df['title'] == 'japanese speaker support staff area jakarta', 'title'] = 'japanese speaker support staff'
df.loc[df['title'] == 'project coordinator modern retail retail floor', 'title'] = 'project coordinator'
df.loc[df['title'] == 'it engineer computer hardware service product and sales', 'title'] = 'it engineer'
df.loc[df['title'] == 'senior sap consultant hardware logistics project', 'title'] = 'senior sap consultant'
df.loc[df['title'] == 'apprentice for chemical engineering malang i89151', 'title'] = 'apprentice chemical engineering'
df.loc[df['title'] == 'peternakan budidaya ikan tanaman pangan perkebunan', 'title'] = 'peternakan budidaya ikan'
df.loc[df['title'] == 'operator gudang warehouse jogja yogyakarta', 'title'] = 'operator gudang'
df.loc[df['title'] == 'financial planning associate sarjana hukum fresh graduate', 'title'] = 'financial planning associate'
df.loc[df['title'] == 'hrga supervisor fresh graduate jakarta', 'title'] = 'hrga supervisor'
df.loc[df['title'] == 'brand manager automotive industry 40jakarta', 'title'] = 'brand manager'
df.loc[df['title'] == 'hr and ga manager hrga manager jakarta', 'title'] = 'hrga manager'
df.loc[df['title'] == 'technical and engineer manager jakarta industrial', 'title'] = 'technical engineer manager'
df.loc[df['title'] == 'assistant manager seattle', 'title'] = 'assistant manager'

In [34]:
#normalisasi title lebih dari 5 kata
df.loc[df['title'] == 'surveyor bpkb cirebon indramayu dan kuningan', 'title'] = 'surveyor bpkb'
df.loc[df['title'] == 'sales manager horeca fb distributor kitchen equipment', 'title'] = 'sales manager horeca'
df.loc[df['title'] == 'sales membership advisor sequis tower scbd', 'title'] = 'sales membership advisor'
df.loc[df['title'] == 'sales manager modern trade stationery background', 'title'] = 'sales manager modern trade'
df.loc[df['title'] == 'product purchasing merchandiser manager entertainment c107455', 'title'] = 'product purchasing manager'
df.loc[df['title'] == 'kolektor lapangan area lamongan jawa timur', 'title'] = 'kolektor lapangan'
df.loc[df['title'] == 'it cloud sales manager saas b109433', 'title'] = 'it cloud sales manager'
df.loc[df['title'] == 'marketing support mandarin speaker machinery a110552', 'title'] = 'marketing support mandarin speaker'
df.loc[df['title'] == 'accounts executive assistant accountant dadap tangerang', 'title'] = 'accounts executive'
df.loc[df['title'] == 'financial advisor area jakarta selatan plaza mandiri', 'title'] = 'financial advisor'
df.loc[df['title'] == 'marketing sales chemical trading b2b sales', 'title'] = 'marketing sales chemical trading'
df.loc[df['title'] == 'second level maintenance slm managed service', 'title'] = 'second level maintenance'
df.loc[df['title'] == 'it operations and performance management support', 'title'] = 'it operations support'
df.loc[df['title'] == 'sales marketing property developer depok b112571', 'title'] = 'sales marketing property developer'
df.loc[df['title'] == 'sales representative plts pembangkit listrik tenaga surya', 'title'] = 'sales representative PLTS'
df.loc[df['title'] == 'import assistant manager freight forwarding c112529', 'title'] = 'import assistant manager'
df.loc[df['title'] == 'sales marketing executive chemical solvent polymer', 'title'] = 'sales marketing executive'
df.loc[df['title'] == 'cambridge primary english teacher native english speaker', 'title'] = 'cambridge primary english teacher'
df.loc[df['title'] == 'luxury goods valuer japanese speaking jlpt n3', 'title'] = 'luxury goods valuer'
df.loc[df['title'] == 'kolektor lapangan area malang jawa timur', 'title'] = 'kolektor lapangan'
df.loc[df['title'] == 'terapis spa massage placement in uluwatu bali', 'title'] = 'terapis spa massage'
df.loc[df['title'] == 'crew outlet ubitiri baik pik 2', 'title'] = 'crew outlet'
df.loc[df['title'] == 'account manager for software crm salesforce', 'title'] = 'account manager software crm'
df.loc[df['title'] == 'former production monitor of process equipment', 'title'] = 'production monitor'
df.loc[df['title'] == 'operator alat berat wheel loader and excavator', 'title'] = 'operator alat berat'
df.loc[df['title'] == 'japanese speaker support it project finance a112572', 'title'] = 'japanese speaker support'
df.loc[df['title'] == 'innovative of food drink brand experiences bar', 'title'] = 'food drink brand experiences'
df.loc[df['title'] == 'financial and tax accountant money changer', 'title'] = 'financial and tax accountant'
df.loc[df['title'] == 'urgently needed japanese teacher for welders', 'title'] = 'japanese teacher'
df.loc[df['title'] == 'senior teacher for kindergarten tingkat kanakkanak', 'title'] = 'senior teacher kindergarten'
df.loc[df['title'] == 'credit marketing officer depok jakarta selatan cibubur', 'title'] = 'credit marketing officer'
df.loc[df['title'] == 'press sleeve senior application and service engineer', 'title'] = 'senior application engineer'
df.loc[df['title'] == 'business development manager drop shipper aggregator', 'title'] = 'business development manager'
df.loc[df['title'] == 'japanese speaker business development hardware service a113146', 'title'] = 'japanese speaker business development'
df.loc[df['title'] == 'electrical instrumental engineer ei epc company bontang', 'title'] = 'electrical instrumental engineer'
df.loc[df['title'] == 'english teachers needed for ef gresik', 'title'] = 'english teacher'
df.loc[df['title'] == 'operation staffsenior staff forwarding jakarta utara c112281', 'title'] = 'operation staff'
df.loc[df['title'] == 'sales supervisor automotivemanufacture karawang wfo id 659313', 'title'] = 'sales supervisor'
df.loc[df['title'] == 'field collection kolektor lapangan area bandungcimahi selatansoreang', 'title'] = 'field collection'
df.loc[df['title'] == 'production planning inventory control ppic staff', 'title'] = 'production planning staff'
df.loc[df['title'] == 'clinical trainer aesthetic nurse bukan bidan', 'title'] = 'clinical trainer aesthetic nurse'
df.loc[df['title'] == 'tax senior staff trading jakarta barat c112337', 'title'] = 'tax senior staff'
df.loc[df['title'] == 'social media spesialist content creator and editor', 'title'] = 'social media specialist'
df.loc[df['title'] == 'financial advisorbancassurance area surabaya malang kediri mojokerto', 'title'] = 'financial advisor bancassurance'
df.loc[df['title'] == 'sales staff heavy equipment forklift b106868', 'title'] = 'sales staff heavy equipment'
df.loc[df['title'] == 'marketing medical devices ivd product sulawesi', 'title'] = 'marketing medical devices'
df.loc[df['title'] == 'area sales manajer jawa timur balokpang', 'title'] = 'area sales manager'
df.loc[df['title'] == 'design social media specialist junior officerofficer', 'title'] = 'social media specialist'
df.loc[df['title'] == 'sales admin mandarin speaker machinery a111646', 'title'] = 'sales admin mandarin speaker'
df.loc[df['title'] == 'field collection kolektor lapangan area pekalongan pemalang', 'title'] = 'field collection'
df.loc[df['title'] == 'financial service consultant syariah area surabaya raya', 'title'] = 'financial service consultant'
df.loc[df['title'] == 'japanese speaker secretary manufacturing cikarang a113058', 'title'] = 'japanese speaker secretary'
df.loc[df['title'] == 'field collection bandung timur dan garut', 'title'] = 'field collection'
df.loc[df['title'] == 'sales manager horecafood service food distributor b112752', 'title'] = 'sales manager horeca food service'
df.loc[df['title'] == 'admin accounting assistant ecommerce amazon seller internship', 'title'] = 'admin accounting assistant'
df.loc[df['title'] == 'admin front office untuk gym fitness center', 'title'] = 'admin front office'
df.loc[df['title'] == 'maintenance supervisorasst manager food semarang b112528', 'title'] = 'maintenance supervisor'
df.loc[df['title'] == 'crew store area malang jawa timur', 'title'] = 'crew store'
df.loc[df['title'] == 'field collection kolektor lapangan area kudus jepara', 'title'] = 'field collection'
df.loc[df['title'] == 'deputy general manager hr maritime transportation', 'title'] = 'deputy general manager hr'
df.loc[df['title'] == 'financial advisor rantauprapat penyambungan sipirok sinunukan sibuhuan', 'title'] = 'financial advisor'
df.loc[df['title'] == 'marketing mortgage branch tangerang 1 karawaci', 'title'] = 'marketing mortgage branch'
df.loc[df['title'] == 'business development customer service ecommerce crm', 'title'] = 'business development customer service'
df.loc[df['title'] == 'mining sales executive sales produk hasil pertambangan', 'title'] = 'mining sales executive'
df.loc[df['title'] == 'legal manager mandarin speaker mining a108919', 'title'] = 'legal manager mandarin speaker'
df.loc[df['title'] == 'social media specialist social media officer', 'title'] = 'social media specialist'
df.loc[df['title'] == 'production supervisor consumer goods speak english', 'title'] = 'production supervisor consumer goods'
df.loc[df['title'] == 'junior high school bahasa indonesia teacher', 'title'] = 'junior high school teacher'
df.loc[df['title'] == 'daily worker sorter penempatan dc denpasar bali', 'title'] = 'daily worker sorter'
df.loc[df['title'] == 'sales staff alat kesehatan surabaya b112855', 'title'] = 'sales staff alat kesehatan'
df.loc[df['title'] == 'business manager kepala cabang banjarnegara purbalingga', 'title'] = 'business manager'
df.loc[df['title'] == 'front end web developer fresh graduate', 'title'] = 'front end web developer'
df.loc[df['title'] == 'medical data management icd 9 doctor background', 'title'] = 'medical data management'
df.loc[df['title'] == 'welding engineer llc construction project', 'title'] = 'welding engineer'
df.loc[df['title'] == 'accounting supervisor project finance jakarta', 'title'] = 'accounting supervisor'
df.loc[df['title'] == 'customer service senayan jakarta pusat', 'title'] = 'customer service'
df.loc[df['title'] == 'guest service officer airport level senior agent', 'title'] = 'guest service officer'
df.loc[df['title'] == 'sales expert counter sales supervisor kiosk carrefour c110207', 'title'] = 'sales expert counter sales'
df.loc[df['title'] == 'field collection account officer malang', 'title'] = 'field collection'
df.loc[df['title'] == 'field collection supervisor medan', 'title'] = 'field collection supervisor'
df.loc[df['title'] == 'quality control qc manager agribusiness', 'title'] = 'quality control manager'
df.loc[df['title'] == 'supply chain manager jakarta utara', 'title'] = 'supply chain manager'
df.loc[df['title'] == 'warehouse staff walini area bogor', 'title'] = 'warehouse staff'
df.loc[df['title'] == 'operation supervisor surabaya area', 'title'] = 'operation supervisor'
df.loc[df['title'] == 'graduate trainee retail operation', 'title'] = 'graduate trainee retail'
df.loc[df['title'] == 'manager and staff operation pharmaceutic', 'title'] = 'manager staff operation'
df.loc[df['title'] == 'sales coordinator pharmaceutical company east java', 'title'] = 'sales coordinator pharmaceutical'
df.loc[df['title'] == 'store manager retail outlet brand new jakarta', 'title'] = 'store manager retail outlet'
df.loc[df['title'] == 'field collection kolektor lapangan solo', 'title'] = 'field collection'

In [35]:
#normalisasi title lebih dari 5 kata
df.loc[df['title'] == 'general manager gm sales partners b2g b2b', 'title'] = 'general manager sales'
df.loc[df['title'] == 'oracle crm techno consultant it consulting a112906', 'title'] = 'oracle crm consultant'
df.loc[df['title'] == 'field collection kolektor lapangan area sragen', 'title'] = 'field collection'
df.loc[df['title'] == 'senior accountant for intanah pte ltd', 'title'] = 'senior accountant'
df.loc[df['title'] == 'peluang buat branch manager yang hobi marketing', 'title'] = 'branch manager'
df.loc[df['title'] == 'sales bahan bangunan area jakarta timur', 'title'] = 'sales bahan bangunan'
df.loc[df['title'] == 'supervisor spv untuk rumah makan resto', 'title'] = 'supervisor rumah makan'
df.loc[df['title'] == 'telemarketing konten kreator kokichef dimsum spgspb', 'title'] = 'telemarketing konten kreator'
df.loc[df['title'] == 'contact center supporting team tl qa trainer', 'title'] = 'contact center team lead'
df.loc[df['title'] == 'sales executive bsd and alam sutra', 'title'] = 'sales executive'
df.loc[df['title'] == 'live streaming host ecommerce experience only', 'title'] = 'live streaming host'
df.loc[df['title'] == 'branch manager sales freight forwarding batam', 'title'] = 'branch manager sales'
df.loc[df['title'] == 'trade marketing manager be placed in mexico', 'title'] = 'trade marketing manager'
df.loc[df['title'] == 'oracle financial technical consultant it consulting a112915', 'title'] = 'oracle financial consultant'
df.loc[df['title'] == 'staff hc human capital wilayah jakarta', 'title'] = 'staff human capital'
df.loc[df['title'] == 'cluster permit pic ftth project medan palembang', 'title'] = 'cluster permit pic'

In [36]:
print(df[df['title'].apply(lambda x: len(str(x).split()) > 5)])

Empty DataFrame
Columns: [title, role, company_name, category, location, jobId, type, benefit, salary, url, description, title_translated, description_translated, category_translated, role_translated]
Index: []

In [37]:
df.head(30)

,title,role,company_name,category,location,jobId,type,benefit,salary,url,description,title_translated,description_translated,category_translated,role_translated
0,penerjemah bahasa mandarinasisten manajer umum,mandarin-translator,pt onemate aksesoris mobil,"administrasi dan dukungan perkantoran, asisten...","tangerang, banten",79976110,full time,NaN,rp 8.500.000 – rp 12.500.000 per month,https:atauatauid.jobstreet.comataujobatau79976110,asisten manajer umum: • membantu manajer umum ...,penerjemah bahasa mandarin，asisten manajer umum,asisten manajer umum: • membantu manajer umum ...,"administrasi dan dukungan perkantoran, asisten...",mandarin-translator
1,it business analyst,information-technology-business-analyst,pt nextalent talenta nusantara,"teknologi informasi dan komunikasi, analis bis...",jakarta raya,80187093,full time,NaN,rp 10.000.000 – rp 14.000.000 per month,https:atauatauid.jobstreet.comataujobatau80187093,qualification : candidate must possess at leas...,analis bisnis ti,error: [errno 11001] getaddrinfo failed,"teknolog informasi dan komununasi, anis bisnis...",informasi-teknologi-business-analyst
2,it business analyst,information-technology-business-analyst,pt nextalent talenta nusantara,"teknologi informasi dan komunikasi, analis bis...",jakarta raya,80187093,full time,NaN,rp 10.000.000 – rp 14.000.000 per month,https:atauatauid.jobstreet.comataujobatau80187093,qualification : candidate must possess at leas...,analis bisnis ti,error: [errno 11001] getaddrinfo failed,"teknologi informasi dan komunikasi, analis bis...",informasi-teknologi-business-analyst
3,sales executive,sales-executive,pt. laxmi utama,"ritel dan produk konsumen, asisten ritel","surabaya, jawa timur",79645321,full time,"gaji pokok dan insentif, bpjs ketenaga kerjaan...",rp 6.000.000 – rp 9.000.000 per month,https:atauatauid.jobstreet.comataujobatau79645321,a retail garment sales executive plays a vital...,eksekutif penjualan,error: [errno 11001] getaddrinfo failed,"ritel dan produk mengkonsumsi, asist ritel",eksekutif penjualan
4,site project staff,project-staff,pt vnv mandiri valve,"konstruksi, manajemen proyek","kabupaten bekasi, jawa barat",79912142,kontrak,NaN,rp 4.500.000 – rp 5.500.000 per month,https:atauatauid.jobstreet.comataujobatau79912142,"uraian tugas : menyusun rencana proyek, termas...",staf proyek situs,"uraian tugas : menyusun rencana proyek, termas...","konstruksi, manajemen proyek",staf proyek
5,kepala sipil struktur engineering,engineering,cv renon property - emporio architect,"teknik, teknik sipilataustruktural","jakarta pusat, jakarta raya",80181996,full time,NaN,rp 8.000.000 – rp 8.100.000 per month,https:atauatauid.jobstreet.comataujobatau80181996,"kami, emporio architect . firma arsitektur yan...",kepala sipil atau struktur engineering,"kami, emporio architect . firma arsitektur yan...","teknik, teknik sipilataustruktural",rekayasa
6,sales marketing,marketing,pt pratama indonesia lestari,"ritel dan produk konsumen, asisten ritel",jakarta raya,80101420,full time,NaN,rp 4.500.000 – rp 6.500.000 per month,https:atauatauid.jobstreet.comataujobatau80101420,kualifikasi : pendidikan minimal smaatausedera...,pemasaran penjualan,kualifikasi : pendidikan minimal smaatausedera...,"ritel dan produk mengkonsumsi, asist ritel",pemasaran
7,staff management korean specialist,management-staff,pt cosmax indonesia,"administrasi dan dukungan perkantoran, asisten...","jakarta selatan, jakarta raya",79602834,full time,NaN,rp 6.000.000 – rp 8.000.000 per month,https:atauatauid.jobstreet.comataujobatau79602834,pt. cosmax indonesia is a no 1 toll manufactur...,manajemen staf (spesialis korea),error: [errno 11001] getaddrinfo failed,"administrasi dan dukungan perkantoran, asisten...",staf manajemen
8,telemarketing,NaN,pt era manunggal sejahtera,"penjualan, perwakilanataukonsultan penjualan","jakarta selatan, jakarta raya",79576950,full time,NaN,rp 3.500.000 – rp 4.200.000 per month,https:atauatauid.jobstreet.comataujobatau79576950,pt. era manunggal sejahtera merupakan perusaha...,telemarketing,pt. era manunggal sejahtera merupakan perusaha...,"penjualan, perwakilanataukonsultan penjualan",error: expected string or bytes-like object
9,pengawas lapangan interiorfurniture,field-supervisor,maitaru dadijaya bali,"desain dan arsitektur, desain interior","badung, bali",80175329,full time,NaN,rp 4.500.000 – rp 6.500.000 per month,https:atauatauid.jobstreet.comataujobatau80175329,dibutuhkan pengawas lapangan interiorataufurni...,pengawas lapangan interioratautempat,dibutuhkan pengawas lapangan interiorataufurni...,"desain dan arsitektur, desain interior",supervisor lapangan
10,senior auditor public accounting firm,accounting,pt equilibrium cita selaras,"akuntansi, audit – eksternal","jakarta selatan, jakarta raya",80144596,full time,"wfo in kuningan (south jakarta), full-time emp...",rp 7.500.000 – rp 11.000.000 per month,https:atauatauid.jobstreet.comataujobatau80144596,our client – ​​an established public accountin...,auditor senior (firma akuntansi publik),error: [errno 11001] getaddrinfo failed,"akuntansi, audit – eksternal",akuntansi
11,sales executive,sales-executive,pengiklan anonim,"penjualan, perwakilanataukonsultan penjualan",cikarang,79702119,kontrak,"jenjang karir, bonus tahunan, bpjs kesehatan n...",rp 3.800.000 – rp 4.602.000 per month,https:atauatauid.jobstreet.comataujobatau79702119,tugas tanggungjawab : mengidentifikasi dan men...,penjualan eksekutif,tugas tanggungjawab : mengidentifikasi dan men...,"penjualan, perwakilanataukonsultan penjualan",eksekutif penjualan
12,merchandiser,merchandiser,pt kafe batavia fatahillah,"ritel dan produk konsumen, merchandiser","jakarta barat, jakarta raya",79800476,full time,NaN,rp 5.000.000 – rp 7.000.000 per month,https:atauatauid.jobstreet.comataujobatau79800476,kualifikasi 1. pendidikan min smk atau d3 (per...,merchandiser,kualifikasi 1. pendidikan min smk atau d3 (per...,"ritel dan produk mengkonsumsi, merchandiser",merchandiser
13,receiptionist bali,receptionist,pt.samudra estetika perkasa,"ritel dan produk konsumen, asisten ritel",bali,80175828,full time,NaN,rp 3.000.000 – rp 3.096.823 per month,https:atauatauid.jobstreet.comataujobatau80175828,tanggung jawab : mengurus registrasi membalas ...,resepsionis (bali),tanggung jawab : mengurus registrasi membalas ...,"ritel dan produk mengkonsumsi, asist ritel",resepsionis
14,administrasi spv sa,supervisor,pt golden brilliant sanitaryware,"ritel dan produk konsumen, asisten ritel","bekasi, jawa barat",80185299,full time,NaN,rp 3.500.000 – rp 4.500.000 per month,https:atauatauid.jobstreet.comataujobatau80185299,pt. golden brilliant sanitaryware (germany bri...,administrasi adalah spv sa,pt. golden brilliant sanitaryware (germany bri...,"ritel dan produk mengkonsumsi, asist ritel",pengawas
15,dokter kecantikan estetika,beauty-doctor,sk.n atelier,"kesehatan dan medis, dokter umum","pamulang, banten",79645796,full time,NaN,rp 11.500.000 – rp 15.000.000 per month,https:atauatauid.jobstreet.comataujobatau79645796,kualifikasi : pendidikan profesi dokter (s1) m...,dokter kecantikan atau estetika,kualifikasi : pendidikan profesi dokter (s1) m...,"kesehatan dan medis, dokter umum",doktor kecantikan
16,deputy sales manager,sales-manager,pt iconic talent indonesia,"penjualan, manajemen",cikarang,79993623,full time,NaN,rp 23.500.000 – rp 26.500.000 per month,https:atauatauid.jobstreet.comataujobatau79993623,responsibilities or job desc • implementation ...,wakil manajer penjualan,error: [errno 11001] getaddrinfo failed,"penjualan, manajemen",manajer penjualan
17,production line leader mandarin speaker,production-line-leader,pt cfu technology indonesia,"manufaktur, transportasi dan logistik, pemimpi...",jawa barat,79657626,kontrak,NaN,rp 5.500.000 – rp 6.500.000 per month,https:atauatauid.jobstreet.comataujobatau79657626,1.running day to day productionactivity in goo...,pemimpin jalur produksi (pembicara mandarin),error: [errno 11001] getaddrinfo failed,"manufaktur, transportasi dan logistik, pemimpi...",pemimpin produksi-line
18,videographer,videographer,pt. putra perkasa,"periklanan, seni dan media, fotografi","surabaya, jawa timur",79695850,full time,"jaminan asuransi kesehatan, bonus berdasarkan ...","rp 5,000,000 – rp 5,500,000 per month",https:atauatauid.jobstreet.comataujobatau79695850,triv adalah salah satu bursa kripto terbesar d...,videografer,triv adalah salah satu bursa kripto terbesar d...,"periklanan, seni dan media, fotografi",videografer
19,analis lab plating qc staff,laboratory-analyst,pt nichias metalworks indonesia,"sains dan teknologi, jasa laboratorium dan teknis","cikarang pusat, jawa barat",80061013,full time,"bonus tahunan, bpjs, asuransi swasta (kartap*)",rp 7.000.000 – rp 8.000.000 per month,https:atauatauid.jobstreet.comataujobatau80061013,tugas dan tanggung jawab : melakukan analisa s...,lab analis.plating (staf qc),tugas dan tanggung jawab : melakukan analisa s...,"sains dan teknologi, jasa laboratorium dan teknis",laboratorium-analis
20,sales project,sales,pt shinmado,"penjualan, perwakilanataukonsultan penjualan","jakarta utara, jakarta raya",79517441,full time,NaN,rp 5.000.000 – rp 7.000.000 per month,https:atauatauid.jobstreet.comataujobatau79517441,job description qualifications: at least 2-3 y...,proyek penjualan,error: [errno 11001] getaddrinfo failed,"penjualan, perwakilanataukonsultan penjualan",penjualan
21,fullstack developer,full-stack-developer,koffiesoft group,"teknologi informasi dan komunikasi, developera...","surabaya, jawa timur",80161629,full time,NaN,rp 4.500.000 – rp 6.750.000 per month,https:atauatauid.jobstreet.comataujobatau80161629,• berpengalaman minimal 3 tahun menggunakan ph...,pengembang tumpukan penuh,• berpengalaman minimal 3 tahun menggunakan ph...,"teknologi informasi dan komunikasi, developera...",pengembang full-stack
22,customer service japanese speaker,customer-service-role,pt. akazora usaha mandiri,"call center dan layanan konsumen, layanan kons...",cikarang,80102855,full time,"budaya kerja yang kreatif dan inovatif, pengem...",rp 5.200.000 – rp 5.500.000 per month,https:atauatauid.jobstreet.comataujobatau80102855,kualifikasi: usia minimal 23 tahun maksimal 40...,layanan pelanggan (pembicara jepang),kualifikasi: usia minimal 23 tahun maksimal 40...,"call center dan layanan konsumen, layanan kons...",perangkalan layanan pelanggan
23,sales marketing,marketing,pt. cipta aneka selera,"penjualan, pengembangan bisnis baru","parung, jawa barat",79760681,full time,mitra yang sudah tersebar di seluruh indonesia...,"rp 5,500,000 – rp 6,200,000 per month",https:atauatauid.jobstreet.comataujobatau79760681,kualfikasi : bertanggung jawab pendidikan mini...,pemasaran penjualan,kualfikasi : bertanggung jawab pendidikan mini...,"penjualan, pengembangan bisnis baru",marketing
24,bancassurance specialist jakarta kemayoran,bancassurance-specialist,pt bni life insurance,"penjualan, perwakilanataukonsultan penjualan","jakarta pusat, jakarta raya",80093228,full time,NaN,"rp 2,000,000 – rp 3,000,000 per month",https:atauatauid.jobstreet.comataujobatau80093228,bancassurance specialist (bas) representative ...,bancassurance specialist - jakarta kemayoran,bancassurance specialist (bas) representative ...,"penjualan, perwakilanataukonsultan penjualan",spesialis bancassurance
25,sales marketing,marketing,pt ruang sukses indonesia,"penjualan, perwakilanataukonsultan penjualan","jakarta barat, jakarta raya",79854347,full time,NaN,rp 3.500.000 – rp 4.500.000 per month,https:atauatauid.jobstreet.comataujobatau79854347,ruangpedia sedang mencari tenaga profesional s...,penjualan dan pemasaran,ruangpedia sedang mencari tenaga profesional s...,"penjualan, perwakilanataukonsultan penjualan",pemasaran
26,security manager area pekanbaru,security-manager,pt sigap prima astrea,"keterampilan dan jasa, jasa keamanan","pekanbaru, riau",79676318,full time,"asuransi kesehatan, security training and educ...","rp 6,500,000 – rp 7,000,000 per month",https:atauatauid.jobstreet.comataujobatau79676318,kualifikasi: pendidikan s1 segala jurusan deng...,security manager (area pekanbaru),kualifikasi: pendidikan s1 segala jurusan deng...,"keterampilan dan jasa, jasa keamanan",manajer keamanan
27,account manager,account-manager,pt yuxi jayatama indonesia,"periklanan, seni dan media, manajemen akun agensi","jakarta utara, jakarta raya",79720509,full time,"career growth, bpjs, various allowance",rp 7.500.000 – rp 11.000.000 per month,https:atauatauid.jobstreet.comataujobatau79720509,about us : yuxi jayatama is an multi-channel n...,manajer akun,error: [errno 11001] getaddrinfo failed,"periklanan, seni dan media, manajemen akun agensi",manajer akun
28,recruitment officer,recruitment-officer,pt bimasakti multi sinergi,"sumber daya manusia dan perekrutan, perekrutan...","sidoarjo, jawa timur",79946300,full time,NaN,rp 4.500.000 – rp 5.000.000 per month,https:atauatauid.jobstreet.comataujobatau79946300,"manage sourcing for multiple, complex searches...",petugas perekrutan,error: [errno 11001] getaddrinfo failed,"sumber daya manusia dan perekrutan, perekrutan...",kepala recrutment
29,driver bluebird bekasi,driver,pt. morante jaya tbk (bekasi),"manufaktur, transportasi dan logistik, transpo...","bekasi, jawa barat",80003440,full time,"terdapat bonus harian dan bulanan, beasiswa an...",rp 4.500.000 – rp 6.500.000 per month,https:atauatauid.jobstreet.comataujobatau80003440,perusahaan jasa transportasi terbaik di indone...,driver bluebird bekasi,perusahaan jasa transportasi terbaik di indone...,"manufaktur, transportasi dan logistik, transpo...",pengemudi

# Role

In [38]:
df.head(30)

,title,role,company_name,category,location,jobId,type,benefit,salary,url,description,title_translated,description_translated,category_translated,role_translated
0,penerjemah bahasa mandarinasisten manajer umum,mandarin-translator,pt onemate aksesoris mobil,"administrasi dan dukungan perkantoran, asisten...","tangerang, banten",79976110,full time,NaN,rp 8.500.000 – rp 12.500.000 per month,https:atauatauid.jobstreet.comataujobatau79976110,asisten manajer umum: • membantu manajer umum ...,penerjemah bahasa mandarin，asisten manajer umum,asisten manajer umum: • membantu manajer umum ...,"administrasi dan dukungan perkantoran, asisten...",mandarin-translator
1,it business analyst,information-technology-business-analyst,pt nextalent talenta nusantara,"teknologi informasi dan komunikasi, analis bis...",jakarta raya,80187093,full time,NaN,rp 10.000.000 – rp 14.000.000 per month,https:atauatauid.jobstreet.comataujobatau80187093,qualification : candidate must possess at leas...,analis bisnis ti,error: [errno 11001] getaddrinfo failed,"teknolog informasi dan komununasi, anis bisnis...",informasi-teknologi-business-analyst
2,it business analyst,information-technology-business-analyst,pt nextalent talenta nusantara,"teknologi informasi dan komunikasi, analis bis...",jakarta raya,80187093,full time,NaN,rp 10.000.000 – rp 14.000.000 per month,https:atauatauid.jobstreet.comataujobatau80187093,qualification : candidate must possess at leas...,analis bisnis ti,error: [errno 11001] getaddrinfo failed,"teknologi informasi dan komunikasi, analis bis...",informasi-teknologi-business-analyst
3,sales executive,sales-executive,pt. laxmi utama,"ritel dan produk konsumen, asisten ritel","surabaya, jawa timur",79645321,full time,"gaji pokok dan insentif, bpjs ketenaga kerjaan...",rp 6.000.000 – rp 9.000.000 per month,https:atauatauid.jobstreet.comataujobatau79645321,a retail garment sales executive plays a vital...,eksekutif penjualan,error: [errno 11001] getaddrinfo failed,"ritel dan produk mengkonsumsi, asist ritel",eksekutif penjualan
4,site project staff,project-staff,pt vnv mandiri valve,"konstruksi, manajemen proyek","kabupaten bekasi, jawa barat",79912142,kontrak,NaN,rp 4.500.000 – rp 5.500.000 per month,https:atauatauid.jobstreet.comataujobatau79912142,"uraian tugas : menyusun rencana proyek, termas...",staf proyek situs,"uraian tugas : menyusun rencana proyek, termas...","konstruksi, manajemen proyek",staf proyek
5,kepala sipil struktur engineering,engineering,cv renon property - emporio architect,"teknik, teknik sipilataustruktural","jakarta pusat, jakarta raya",80181996,full time,NaN,rp 8.000.000 – rp 8.100.000 per month,https:atauatauid.jobstreet.comataujobatau80181996,"kami, emporio architect . firma arsitektur yan...",kepala sipil atau struktur engineering,"kami, emporio architect . firma arsitektur yan...","teknik, teknik sipilataustruktural",rekayasa
6,sales marketing,marketing,pt pratama indonesia lestari,"ritel dan produk konsumen, asisten ritel",jakarta raya,80101420,full time,NaN,rp 4.500.000 – rp 6.500.000 per month,https:atauatauid.jobstreet.comataujobatau80101420,kualifikasi : pendidikan minimal smaatausedera...,pemasaran penjualan,kualifikasi : pendidikan minimal smaatausedera...,"ritel dan produk mengkonsumsi, asist ritel",pemasaran
7,staff management korean specialist,management-staff,pt cosmax indonesia,"administrasi dan dukungan perkantoran, asisten...","jakarta selatan, jakarta raya",79602834,full time,NaN,rp 6.000.000 – rp 8.000.000 per month,https:atauatauid.jobstreet.comataujobatau79602834,pt. cosmax indonesia is a no 1 toll manufactur...,manajemen staf (spesialis korea),error: [errno 11001] getaddrinfo failed,"administrasi dan dukungan perkantoran, asisten...",staf manajemen
8,telemarketing,NaN,pt era manunggal sejahtera,"penjualan, perwakilanataukonsultan penjualan","jakarta selatan, jakarta raya",79576950,full time,NaN,rp 3.500.000 – rp 4.200.000 per month,https:atauatauid.jobstreet.comataujobatau79576950,pt. era manunggal sejahtera merupakan perusaha...,telemarketing,pt. era manunggal sejahtera merupakan perusaha...,"penjualan, perwakilanataukonsultan penjualan",error: expected string or bytes-like object
9,pengawas lapangan interiorfurniture,field-supervisor,maitaru dadijaya bali,"desain dan arsitektur, desain interior","badung, bali",80175329,full time,NaN,rp 4.500.000 – rp 6.500.000 per month,https:atauatauid.jobstreet.comataujobatau80175329,dibutuhkan pengawas lapangan interiorataufurni...,pengawas lapangan interioratautempat,dibutuhkan pengawas lapangan interiorataufurni...,"desain dan arsitektur, desain interior",supervisor lapangan
10,senior auditor public accounting firm,accounting,pt equilibrium cita selaras,"akuntansi, audit – eksternal","jakarta selatan, jakarta raya",80144596,full time,"wfo in kuningan (south jakarta), full-time emp...",rp 7.500.000 – rp 11.000.000 per month,https:atauatauid.jobstreet.comataujobatau80144596,our client – ​​an established public accountin...,auditor senior (firma akuntansi publik),error: [errno 11001] getaddrinfo failed,"akuntansi, audit – eksternal",akuntansi
11,sales executive,sales-executive,pengiklan anonim,"penjualan, perwakilanataukonsultan penjualan",cikarang,79702119,kontrak,"jenjang karir, bonus tahunan, bpjs kesehatan n...",rp 3.800.000 – rp 4.602.000 per month,https:atauatauid.jobstreet.comataujobatau79702119,tugas tanggungjawab : mengidentifikasi dan men...,penjualan eksekutif,tugas tanggungjawab : mengidentifikasi dan men...,"penjualan, perwakilanataukonsultan penjualan",eksekutif penjualan
12,merchandiser,merchandiser,pt kafe batavia fatahillah,"ritel dan produk konsumen, merchandiser","jakarta barat, jakarta raya",79800476,full time,NaN,rp 5.000.000 – rp 7.000.000 per month,https:atauatauid.jobstreet.comataujobatau79800476,kualifikasi 1. pendidikan min smk atau d3 (per...,merchandiser,kualifikasi 1. pendidikan min smk atau d3 (per...,"ritel dan produk mengkonsumsi, merchandiser",merchandiser
13,receiptionist bali,receptionist,pt.samudra estetika perkasa,"ritel dan produk konsumen, asisten ritel",bali,80175828,full time,NaN,rp 3.000.000 – rp 3.096.823 per month,https:atauatauid.jobstreet.comataujobatau80175828,tanggung jawab : mengurus registrasi membalas ...,resepsionis (bali),tanggung jawab : mengurus registrasi membalas ...,"ritel dan produk mengkonsumsi, asist ritel",resepsionis
14,administrasi spv sa,supervisor,pt golden brilliant sanitaryware,"ritel dan produk konsumen, asisten ritel","bekasi, jawa barat",80185299,full time,NaN,rp 3.500.000 – rp 4.500.000 per month,https:atauatauid.jobstreet.comataujobatau80185299,pt. golden brilliant sanitaryware (germany bri...,administrasi adalah spv sa,pt. golden brilliant sanitaryware (germany bri...,"ritel dan produk mengkonsumsi, asist ritel",pengawas
15,dokter kecantikan estetika,beauty-doctor,sk.n atelier,"kesehatan dan medis, dokter umum","pamulang, banten",79645796,full time,NaN,rp 11.500.000 – rp 15.000.000 per month,https:atauatauid.jobstreet.comataujobatau79645796,kualifikasi : pendidikan profesi dokter (s1) m...,dokter kecantikan atau estetika,kualifikasi : pendidikan profesi dokter (s1) m...,"kesehatan dan medis, dokter umum",doktor kecantikan
16,deputy sales manager,sales-manager,pt iconic talent indonesia,"penjualan, manajemen",cikarang,79993623,full time,NaN,rp 23.500.000 – rp 26.500.000 per month,https:atauatauid.jobstreet.comataujobatau79993623,responsibilities or job desc • implementation ...,wakil manajer penjualan,error: [errno 11001] getaddrinfo failed,"penjualan, manajemen",manajer penjualan
17,production line leader mandarin speaker,production-line-leader,pt cfu technology indonesia,"manufaktur, transportasi dan logistik, pemimpi...",jawa barat,79657626,kontrak,NaN,rp 5.500.000 – rp 6.500.000 per month,https:atauatauid.jobstreet.comataujobatau79657626,1.running day to day productionactivity in goo...,pemimpin jalur produksi (pembicara mandarin),error: [errno 11001] getaddrinfo failed,"manufaktur, transportasi dan logistik, pemimpi...",pemimpin produksi-line
18,videographer,videographer,pt. putra perkasa,"periklanan, seni dan media, fotografi","surabaya, jawa timur",79695850,full time,"jaminan asuransi kesehatan, bonus berdasarkan ...","rp 5,000,000 – rp 5,500,000 per month",https:atauatauid.jobstreet.comataujobatau79695850,triv adalah salah satu bursa kripto terbesar d...,videografer,triv adalah salah satu bursa kripto terbesar d...,"periklanan, seni dan media, fotografi",videografer
19,analis lab plating qc staff,laboratory-analyst,pt nichias metalworks indonesia,"sains dan teknologi, jasa laboratorium dan teknis","cikarang pusat, jawa barat",80061013,full time,"bonus tahunan, bpjs, asuransi swasta (kartap*)",rp 7.000.000 – rp 8.000.000 per month,https:atauatauid.jobstreet.comataujobatau80061013,tugas dan tanggung jawab : melakukan analisa s...,lab analis.plating (staf qc),tugas dan tanggung jawab : melakukan analisa s...,"sains dan teknologi, jasa laboratorium dan teknis",laboratorium-analis
20,sales project,sales,pt shinmado,"penjualan, perwakilanataukonsultan penjualan","jakarta utara, jakarta raya",79517441,full time,NaN,rp 5.000.000 – rp 7.000.000 per month,https:atauatauid.jobstreet.comataujobatau79517441,job description qualifications: at least 2-3 y...,proyek penjualan,error: [errno 11001] getaddrinfo failed,"penjualan, perwakilanataukonsultan penjualan",penjualan
21,fullstack developer,full-stack-developer,koffiesoft group,"teknologi informasi dan komunikasi, developera...","surabaya, jawa timur",80161629,full time,NaN,rp 4.500.000 – rp 6.750.000 per month,https:atauatauid.jobstreet.comataujobatau80161629,• berpengalaman minimal 3 tahun menggunakan ph...,pengembang tumpukan penuh,• berpengalaman minimal 3 tahun menggunakan ph...,"teknologi informasi dan komunikasi, developera...",pengembang full-stack
22,customer service japanese speaker,customer-service-role,pt. akazora usaha mandiri,"call center dan layanan konsumen, layanan kons...",cikarang,80102855,full time,"budaya kerja yang kreatif dan inovatif, pengem...",rp 5.200.000 – rp 5.500.000 per month,https:atauatauid.jobstreet.comataujobatau80102855,kualifikasi: usia minimal 23 tahun maksimal 40...,layanan pelanggan (pembicara jepang),kualifikasi: usia minimal 23 tahun maksimal 40...,"call center dan layanan konsumen, layanan kons...",perangkalan layanan pelanggan
23,sales marketing,marketing,pt. cipta aneka selera,"penjualan, pengembangan bisnis baru","parung, jawa barat",79760681,full time,mitra yang sudah tersebar di seluruh indonesia...,"rp 5,500,000 – rp 6,200,000 per month",https:atauatauid.jobstreet.comataujobatau79760681,kualfikasi : bertanggung jawab pendidikan mini...,pemasaran penjualan,kualfikasi : bertanggung jawab pendidikan mini...,"penjualan, pengembangan bisnis baru",marketing
24,bancassurance specialist jakarta kemayoran,bancassurance-specialist,pt bni life insurance,"penjualan, perwakilanataukonsultan penjualan","jakarta pusat, jakarta raya",80093228,full time,NaN,"rp 2,000,000 – rp 3,000,000 per month",https:atauatauid.jobstreet.comataujobatau80093228,bancassurance specialist (bas) representative ...,bancassurance specialist - jakarta kemayoran,bancassurance specialist (bas) representative ...,"penjualan, perwakilanataukonsultan penjualan",spesialis bancassurance
25,sales marketing,marketing,pt ruang sukses indonesia,"penjualan, perwakilanataukonsultan penjualan","jakarta barat, jakarta raya",79854347,full time,NaN,rp 3.500.000 – rp 4.500.000 per month,https:atauatauid.jobstreet.comataujobatau79854347,ruangpedia sedang mencari tenaga profesional s...,penjualan dan pemasaran,ruangpedia sedang mencari tenaga profesional s...,"penjualan, perwakilanataukonsultan penjualan",pemasaran
26,security manager area pekanbaru,security-manager,pt sigap prima astrea,"keterampilan dan jasa, jasa keamanan","pekanbaru, riau",79676318,full time,"asuransi kesehatan, security training and educ...","rp 6,500,000 – rp 7,000,000 per month",https:atauatauid.jobstreet.comataujobatau79676318,kualifikasi: pendidikan s1 segala jurusan deng...,security manager (area pekanbaru),kualifikasi: pendidikan s1 segala jurusan deng...,"keterampilan dan jasa, jasa keamanan",manajer keamanan
27,account manager,account-manager,pt yuxi jayatama indonesia,"periklanan, seni dan media, manajemen akun agensi","jakarta utara, jakarta raya",79720509,full time,"career growth, bpjs, various allowance",rp 7.500.000 – rp 11.000.000 per month,https:atauatauid.jobstreet.comataujobatau79720509,about us : yuxi jayatama is an multi-channel n...,manajer akun,error: [errno 11001] getaddrinfo failed,"periklanan, seni dan media, manajemen akun agensi",manajer akun
28,recruitment officer,recruitment-officer,pt bimasakti multi sinergi,"sumber daya manusia dan perekrutan, perekrutan...","sidoarjo, jawa timur",79946300,full time,NaN,rp 4.500.000 – rp 5.000.000 per month,https:atauatauid.jobstreet.comataujobatau79946300,"manage sourcing for multiple, complex searches...",petugas perekrutan,error: [errno 11001] getaddrinfo failed,"sumber daya manusia dan perekrutan, perekrutan...",kepala recrutment
29,driver bluebird bekasi,driver,pt. morante jaya tbk (bekasi),"manufaktur, transportasi dan logistik, transpo...","bekasi, jawa barat",80003440,full time,"terdapat bonus harian dan bulanan, beasiswa an...",rp 4.500.000 – rp 6.500.000 per month,https:atauatauid.jobstreet.comataujobatau80003440,perusahaan jasa transportasi terbaik di indone...,driver bluebird bekasi,perusahaan jasa transportasi terbaik di indone...,"manufaktur, transportasi dan logistik, transpo...",pengemudi

In [39]:
df['role'] = df['role'].str.replace('/', 'atau', regex=False)
df['role'] = df['role'].str.replace('&', 'dan', regex=False)
df['role'] = df['role'].str.lower()
df['role'] = df['role'].fillna('tidak diketahui')
df['role'] = df['role'].str.replace(r'[^\w\s]', ' ', regex=True)  #menghapus karakter selain huruf dan spasi
df['role'] = df['role'].str.strip().str.replace(r'\s+', ' ', regex=True) #menghapus spasi berlenih

In [40]:
df.head()

,title,role,company_name,category,location,jobId,type,benefit,salary,url,description,title_translated,description_translated,category_translated,role_translated
0,penerjemah bahasa mandarinasisten manajer umum,mandarin translator,pt onemate aksesoris mobil,"administrasi dan dukungan perkantoran, asisten...","tangerang, banten",79976110,full time,NaN,rp 8.500.000 – rp 12.500.000 per month,https:atauatauid.jobstreet.comataujobatau79976110,asisten manajer umum: • membantu manajer umum ...,penerjemah bahasa mandarin，asisten manajer umum,asisten manajer umum: • membantu manajer umum ...,"administrasi dan dukungan perkantoran, asisten...",mandarin-translator
1,it business analyst,information technology business analyst,pt nextalent talenta nusantara,"teknologi informasi dan komunikasi, analis bis...",jakarta raya,80187093,full time,NaN,rp 10.000.000 – rp 14.000.000 per month,https:atauatauid.jobstreet.comataujobatau80187093,qualification : candidate must possess at leas...,analis bisnis ti,error: [errno 11001] getaddrinfo failed,"teknolog informasi dan komununasi, anis bisnis...",informasi-teknologi-business-analyst
2,it business analyst,information technology business analyst,pt nextalent talenta nusantara,"teknologi informasi dan komunikasi, analis bis...",jakarta raya,80187093,full time,NaN,rp 10.000.000 – rp 14.000.000 per month,https:atauatauid.jobstreet.comataujobatau80187093,qualification : candidate must possess at leas...,analis bisnis ti,error: [errno 11001] getaddrinfo failed,"teknologi informasi dan komunikasi, analis bis...",informasi-teknologi-business-analyst
3,sales executive,sales executive,pt. laxmi utama,"ritel dan produk konsumen, asisten ritel","surabaya, jawa timur",79645321,full time,"gaji pokok dan insentif, bpjs ketenaga kerjaan...",rp 6.000.000 – rp 9.000.000 per month,https:atauatauid.jobstreet.comataujobatau79645321,a retail garment sales executive plays a vital...,eksekutif penjualan,error: [errno 11001] getaddrinfo failed,"ritel dan produk mengkonsumsi, asist ritel",eksekutif penjualan
4,site project staff,project staff,pt vnv mandiri valve,"konstruksi, manajemen proyek","kabupaten bekasi, jawa barat",79912142,kontrak,NaN,rp 4.500.000 – rp 5.500.000 per month,https:atauatauid.jobstreet.comataujobatau79912142,"uraian tugas : menyusun rencana proyek, termas...",staf proyek situs,"uraian tugas : menyusun rencana proyek, termas...","konstruksi, manajemen proyek",staf proyek

In [41]:
unique_roles = df['role'].unique()
for role in unique_roles:
    print(role)

mandarin translator
information technology business analyst
sales executive
project staff
engineering
marketing
management staff
tidak diketahui
field supervisor
accounting
merchandiser
receptionist
supervisor
beauty doctor
sales manager
production line leader
videographer
laboratory analyst
sales
full stack developer
customer service role
bancassurance specialist
security manager
account manager
recruitment officer
driver
export import manager
researcher
finance specialist
area manager
pharmaceutical technician
art director
accountant
national sales manager
sales administration
maintenance staff
academic team leader
coach
site safety supervisor
software engineer
design manager
store manager
management trainee
import and export staff
risk analyst
content creator
financial adviser
creative director
import staff
operations staff
project administrator
accounting and taxation officer
field service engineer
warehouse operator
accounting and finance manager
production manager
estimator
programmer
legal role
bartender
retail executive
sales associate
account executive
personal assistant
administrative executive
development supervisor
head of shop
sales representative
surveyor
human resource
information technology programmer
administration supervisor
freight forwarding manager
branch manager
technician supervisor
sales staff
graphic designer
implementation supervisory
production supervisor
engineering supervisor
project manager
learning and development role
accounting assistant
sales engineer
manager
information technology support
bancassurance life consultant
inspector
customer relations officer
technical sales manager
executive assistant
business development manager
operations manager
live streaming host
sous chef
asset management analyst
interior drafter
implementation manager
social media specialist
hairstylist
machine learning engineer
branch supervisor
operator
car inspector
manufacturing supervisor
retail sales assistant
digital marketing officer
sales coordinator
audit manager
recruitment specialist
construction manager
research and development role
instructor
accounts payable officer
visualisation artist
finance
regional development manager
quality control manager
install technician
logistics manager
quality assurance staff
head of kitchen
accounting and tax staff
administration
human resources and general affairs manager
industrial relations role
environmental consultant
accounting staff
logistics supervisor
assistant accounting manager
personal trainer
digital marketing
architectural drafter
human capital officer
funding officer
product designer
general affairs supervisor
digital marketing manager
business development consultant
finance accounting and tax officer
human resource supervisor
chinese translator
human resources manager
risk officer
sales consultant
interior design
site coordinator
public relations manager
administration officer
restaurant manager
marketing officer
quality manager
logistics coordinator
assistant audit manager
frontend developer
accounts receivable staff
outlet manager
business support specialist
marketing supervisor
partnership specialist
general practitioner
accounting and tax supervisor
business assistant
bancassurance advisor
production planning and inventory control manager
health safety and environment officer
technician
purchasing role
distribution coordinator
information technology specialist
informatics engineering lecturer
store crew
key account executive
functional consultant
sales administrator
customer service representative csr
marketing manager
architect
foreperson
brand manager
control supervisor
chef
purchasing analyst
social media content creator
secretary to the director
executive personal assistant
corporate secretary
sales promoter
building manager
delivery coordinator
designer
quality control role
human resources staff
human resources generalist
web developer
barista
production planning and inventory control staff
head of department
key opinion leaders specialist
legal supervisor
b2b sales executive
teacher
project supervisor
human resources administration officer
contracts engineer
property manager
revit architect
electrical role
boutique manager
analyst manager
travel consultant
platform specialist
sales administration executive
site supervisor
presales engineer
supply chain manager
freight forwarding
engineer civil structural
budget controller
head of warehouse
interior designer
quality control officer
heating ventilation and air conditioning technician
maintenance supervisor
quantity surveyor
legal counsel
marketing communications supervisor
specialist
human resources assistant
project engineer
logistics staff
network technician
clinic manager
accounts role
draftperson_2
general manager
sales motorist
engineering draftsperson
human resources and general affairs staff
nurse
special educational needs teacher
associate lawyer
english teacher
property assessor
quality control analyst
area coordinator
recruitment
quality control staff
regional manager
technical support
housekeeping supervisor
housekeeping
business analyst
corporate account manager
internal audit staff
scrum master
relationship manager
assistant accounts officer
design
accounts payable
travel adviser
engineering manager
head of administration
full stack java developer
human resources director
classroom teacher
guest relations officer
salesperson
assistant project manager
taxation manager
japanese interpreter
net software developer
accounting supervisor
merchandise manager
pneumatic technician
machine technician
sales canvasser
assistant manager
marketing communications manager
administration support officer
product manager
risk engineer
product developer
finance supervisor
engineer
high school teacher
business development
translator
tax staff
branch head
butcher
relationship officer
video editor
marketing coordinator
repair technician
platform operator
staff supervisor
area supervisor
accounting manager
power engineer
sales supervisor
research and development staff
project development manager
information technology network engineer
accounting and finance officer
plant manager
doctor
crewing supervisor
physiotherapist
chief engineer
quality control supervisor
technical superintendent
finance accounting and tax manager
purchasing manager
mechanical design engineer
consultant project manager
sales specialist
mechanical engineer
agent
construction engineer
business manager
music teacher
human resources and administration manager
go software developer
call centre sales representative
clinical psychologist
regional sales manager
mathematics teacher
trader
human resources development supervisor
financial assistant
reservation staff
information systems lecturer
private driver
finance accounting and tax supervisor
mechanical electrical and plumbing supervisor
floor staff
marketing project manager
english translator
sales and marketing manager
innovation manager
service specialist
teacher aide
artificial intelligence developer
laundry attendant
finance and accounting staff
growth marketing manager
purchasing staff
system implementor
information technology manager
reservations agent
ecommerce specialist
advertiser
design director
digital specialist
organisational development specialist
villa manager
project coordinator
personal assistant to director
renderer
campaign analyst
construction project manager
area sales supervisor
secretary
gardener
project executive
horeca sales executive
facilities and infrastructure staff
tax supervisor
trainer
structural engineer
helper
credit marketing officer
mandarin teacher
finance and accounting supervisor
store leader
supply chain supervisor
administrative staff
canvasser
information technology sales specialist
promoter
pharmacist assistant
cook
nurse executive
pharmacist in charge
waitstaff
marketing staff
finance manager
visual merchandiser
executive chef
assistant sales manager
enterprise resource planning consultant
liaison officer
elevator technician
marketing specialist
product development supervisor
procurement specialist
key account supervisor
manufacturing execution system engineer
personal driver
school counsellor
vet
business development executive
customer realtionship management specialist
manufacturing manager
operations assistant
technical sales representative
team leader
mediator
medical device representative
drafter staff
field assistant
bancassurance consultant
frontliner
business development staff
software developer
helpdesk technician
data centre operator
data analyst
information technology infrastructure engineer
promotions manager
accounting and taxation manager
account officer
executive director
field engineer
head of sales
heating ventilation and air conditioning estimator
assistant office manager
process engineer
maintenance
refrigeration role
marketing representative
assistant civil engineer
site engineer
welder
business development director
beauty consultant
teaching
android developer
financial accountant
finance accounting staff
assistant director
information technology project manager
legal staff
channel manager
country manager
java developer
quality tester
computer numerical control milling operator
promotions specialist
cost control supervisor
digital content creator
store staff
field collector
legal manager
electrical and instrumentation engineer
sales leader
audit staff
printing officer
external auditor
taxation specialist
distributor
education consultant
mechanical electrical engineer
systems analyst
recruitment consultant
chef de partie
executive assistant manager
chairperson
customer service leader
solutions consultant
store supervisor
medical representative
product consultant
business development general manager
team member
travel sales manager
consultant
procurement
therapist
mechanical electrical and plumbing manager
maintenance operator
operations lead
operations associate
corporate legal officer
media planner
compliance manager
data warehouse engineer
prep chef
maintenance technician
crane operator
head of production
security engineer
information technology sales executive
back end java developer
taxation consultant
butler
online driver
asset management specialist
integration analyst
assistant_2
mechanical engineering
talent manager
funding relationship manager
human resources officer
server engineer
channel sales manager
primary teacher
regional sales representative
principal
executive assistant to chief executive officer
human resources and general affairs supervisor
pastrychef
human resources development staff
customer services manager
human capital manager
procurement manager
plantation staff
marketing engineer
devops engineer
electrical engineer
operations supervisor
warehouse coordinator
strategy specialist
service adviser
controller
laundry operator
development manager
retail sales associate
financial staff
cyber security analyst
online administration staff
marketing executive
sap manager
commis chef
makeup artist
automotive sales manager
cloud engineer
specialist doctor
pilates instructor
architectural technician
operational driver
credit controller
presales consultant
mechanical supervisor
education executive
refrigeration specialist
automation manager
interpreter
information technology developer
head of laboratory
people development manager
business development representative
design engineer
warehouse manager
sales and marketing executive
photographer
bancassurance manager
ios developer
head chef
digital marketer
production specialist
operations engineer
seller
head of legal
representative_2
sales support
operations director
editor
assistant finance manager
backend developer
business executive
bookkeeper
patternmaker
odoo developer
key account manager
sales trainer
assistant supervisor
brand marketing manager
japanese teacher
accounting associate
beauty clinic manager
chief financial officer
school administration officer
mobile developer
accounting consultant
technical service representative
maintenance engineer
regional sales executive
event planner
business relationship officer
mechanic
digital director
engineering staff
sales merchandiser
brand strategist
driver director
corporate sales manager
mathematics and science teacher
accounts executive
operations support_2
customer care manager
executive secretary
enterprise resource planning manager
heavy equipment mechanic
production planning control staff
bookkeeping
crewing staff
lead manager
human resources development manager
operations officer
investment director
export and import executive
project specifier
brand specialist
officer
field executive
dealer
reception
digital strategist
strategy manager
machinery mechanic
control systems engineer
payroll
research and development manager
landscape architect
beauty sales consultant
interior supervisor
regional director
head of finance
3d draughtsperson
ship mechanic
coordinator
environmental social and governance assurance manager
medical device executive
information technology staff
formulator
office administrator
development staff
health safety and environment staff
insurance adviser
division staff
finance and accounting analyst
media designer
workshop supervisor
car mechanic
digital advertiser
science technician
japanese translator
cashier
cost accounting officer
product specialist
design staff
warehouse checker
progress advisor
total rewards manager
procurement lead
information technology administration staff
graphic design staff
warehouse supervisor
ecommerce manager
group finance manager
logistics specialist
health safety and environment supervisor
technical support specialist
production planning and inventory control supervisor
audit
speech therapist
supervising engineer
technical engineer
head of store
production control staff
export staff
accounts receivable
middleware engineer
investment analyst
marketing and administration staff
technical person in charge
human resources and general affairs executive
social media manager
assistant accountant
sales support staff
director
mechanical technician
project architect
field officer
systems administrator
head of business development
refractionist optician
assistant secretary
airconditioning role
information technology support consultant
cost accounting manager
office assistant
auditor
information technology helpdesk
massage therapist
fleet operations manager
maintenance engineering manager
maintenance planner
import supervisor
kitchen crew
general affairs staff
leader
superintendent
assistant taxation manager
accounts payables staff
3d modeller
specialist team leader
analyst programmer
site manager
direct sales
human resources business partner
tender specialist
head of accounting
product executive
mining manager
captain
warehouse administration officer
outlet supervisor
legal associate
contact centre team leader
construction supervisor
mechanical electrical and plumbing drafter
telemarketing specialist
compliance administration officer
production machine operator
finance and tax staff
applications engineer
floor supervisor
project draftsman
guest services agent
property consultant
audio engineer
partnerships coordinator
student counsellor
production foreman
office manager
finance and administration staff
machine operator
recruitment hr
head of branch operations
cafe manager
program director
computer numerical control operator
secretary general
technical manager
business development manager it
technical support engineer
motorbike courier
mathematics tutor
vice president of sales
planner
collections officer
business development supervisor
document controller
recruitment manager
information technology executive
cook helper
information technology trainer
quality assurance engineer
company secretary
civil site manager
direct sales supervisor
import specialist
finance administrative staff
civil draftsperson
cost estimator
aesthetic clinic supervisor
assistant marketing manager
reporting analyst
production analyst
office staff
payroll specialist
outlet server
ux ui designer
digital advertising specialist
restaurant crew
cruise sales consultant
information technology account manager
beauty therapist
field sales executive
automation specialist
eyelash technician
japanese teaching staff
assistant branch manager
farm manager
courier
creative designer
major account manager
procurement supervisor
flutter developer
geotechnical engineer
internal auditor
internal audit manager
technical account manager
property sales executive
data engineer
content strategist
executive
facilities technician
internal audit officer
estimator supervisor
air compressor technician
quality assurance role
asset manager
quality assurance lead
factory mechanic
c software developer
assistant human resources manager
contracts manager
digital marketing specialist
support coordinator
procurement officer
digital marketing strategist
corporate trainer
general administration officer
telecommunications manager
finance and administration executive
security officer
digital marketing staff
information technology consultant
floor manager
health safety and environment coordindator
floor captain
project management officer
bancassurance financial advisor
key account specialist
interior site manager
sales officer
field sales manager
security guard
field staff
quality management system staff
purchasing supervisor
ecommerce staff
backend engineer
activation manager
account assistant
business consultant
relationship executive
research and development supervisor
registration staff
finance accounting and tax staff
air freight manager
technical support supervisor
fashion designer
warehouse staff
general affairs executive
finance executive
sales team leader
implementation consultant
research and development chemist
notary
technical sales engineer
korean translator
utility technician
operation and maintenance engineer
department assistant
maintenance manager
production staff
urban planning
assistant to the director
live streaming supervisor
freight supervisor
studio manager
content moderator
substitute teacher
sales account executive
human resources and administration executive
membership adviser
sales and marketing assistant
banking officer
quality control lead
copywriter
quality control engineer
pricing staff
tiktok content creator
solar engineer
invoicing
sales data analyst
printing manager
store planner
building officer
project manager solar
procurement staff
fit out supervisor
compliance officer
executive officer
quality control inspector
forklift driver
management specialist
service crew
electrical technician
warehouse officer
regulatory officer
financial director
business development officer
analyst
sales adviser
tea maker
warehouse lead
tenant relations staff
head of production planning and inventory control
civil estimator
marketing and social media specialist
tutor
pest control technician
equipment maintenance technician
account manager food service
full stack software engineer
remedial officer
kitchen staff
utility supervisor
customer service executive
business support assistant
technical lead
computer numerical control machine operator
sales account manager
head barista
production leader
food and beverage supervisor
sales assistant
regulatory affairs executive
accounting officer
truck mechanic
performance analyst
workshop mechanic
automation engineer
training specialist
english language teacher
financial analyst
java web developer
service staff
store specialist
inside sales
area sales manager
management consultant
human resources specialist
quality control specialist
senior high school physics teacher
verifier
beauty adviser
sales and marketing supervisor
wedding planner
taxation analyst
tax accounting staff
dancer
baker
human resources recruiter
appraiser
social studies teacher
mine planning engineer
facility engineer
recruitment staff
head of human resources and general affairs
digital marketing executive
mep engineer
junior high school teacher
maintenance administration officer
information technology officer
maintenance welder
operations coordinator
talent acquisition manager
project sales engineer
onsite engineer

In [42]:
df.loc[df['role'] == 'assistant_2', 'role'] = 'assistant'
df.loc[df['role'] == 'draftperson_2', 'role'] = 'draftperson'

# Company Name

In [43]:
df.head(2)

,title,role,company_name,category,location,jobId,type,benefit,salary,url,description,title_translated,description_translated,category_translated,role_translated
0,penerjemah bahasa mandarinasisten manajer umum,mandarin translator,pt onemate aksesoris mobil,"administrasi dan dukungan perkantoran, asisten...","tangerang, banten",79976110,full time,NaN,rp 8.500.000 – rp 12.500.000 per month,https:atauatauid.jobstreet.comataujobatau79976110,asisten manajer umum: • membantu manajer umum ...,penerjemah bahasa mandarin，asisten manajer umum,asisten manajer umum: • membantu manajer umum ...,"administrasi dan dukungan perkantoran, asisten...",mandarin-translator
1,it business analyst,information technology business analyst,pt nextalent talenta nusantara,"teknologi informasi dan komunikasi, analis bis...",jakarta raya,80187093,full time,NaN,rp 10.000.000 – rp 14.000.000 per month,https:atauatauid.jobstreet.comataujobatau80187093,qualification : candidate must possess at leas...,analis bisnis ti,error: [errno 11001] getaddrinfo failed,"teknolog informasi dan komununasi, anis bisnis...",informasi-teknologi-business-analyst

In [44]:
df['company_name'].isna().sum()

0

In [45]:
df['company_name'] = df['company_name'].str.replace('pt', '').str.replace('cv', '').str.replace('ltd', '').str.replace('inc', '')

In [46]:
df['company_name'] = df['company_name'].str.replace(r'[^\x00-\x7F]+', '', regex=True) #menghapus karakter yang non-atin

In [47]:
df['company_name'].isna().sum()

0

In [48]:
df['company_name'] = df['company_name'].str.strip()  #menghapus spasi di awal/akhir
df['company_name'] = df['company_name'].str.replace(r'\s+', ' ', regex=True)  #menghilangkan spasi berlebih
df['company_name'] = df['company_name'].str.replace(r'[^\w\s]', '', regex=True)

In [49]:
df['company_name'].isna().sum()

0

In [50]:
df.head()

,title,role,company_name,category,location,jobId,type,benefit,salary,url,description,title_translated,description_translated,category_translated,role_translated
0,penerjemah bahasa mandarinasisten manajer umum,mandarin translator,onemate aksesoris mobil,"administrasi dan dukungan perkantoran, asisten...","tangerang, banten",79976110,full time,NaN,rp 8.500.000 – rp 12.500.000 per month,https:atauatauid.jobstreet.comataujobatau79976110,asisten manajer umum: • membantu manajer umum ...,penerjemah bahasa mandarin，asisten manajer umum,asisten manajer umum: • membantu manajer umum ...,"administrasi dan dukungan perkantoran, asisten...",mandarin-translator
1,it business analyst,information technology business analyst,nextalent talenta nusantara,"teknologi informasi dan komunikasi, analis bis...",jakarta raya,80187093,full time,NaN,rp 10.000.000 – rp 14.000.000 per month,https:atauatauid.jobstreet.comataujobatau80187093,qualification : candidate must possess at leas...,analis bisnis ti,error: [errno 11001] getaddrinfo failed,"teknolog informasi dan komununasi, anis bisnis...",informasi-teknologi-business-analyst
2,it business analyst,information technology business analyst,nextalent talenta nusantara,"teknologi informasi dan komunikasi, analis bis...",jakarta raya,80187093,full time,NaN,rp 10.000.000 – rp 14.000.000 per month,https:atauatauid.jobstreet.comataujobatau80187093,qualification : candidate must possess at leas...,analis bisnis ti,error: [errno 11001] getaddrinfo failed,"teknologi informasi dan komunikasi, analis bis...",informasi-teknologi-business-analyst
3,sales executive,sales executive,laxmi utama,"ritel dan produk konsumen, asisten ritel","surabaya, jawa timur",79645321,full time,"gaji pokok dan insentif, bpjs ketenaga kerjaan...",rp 6.000.000 – rp 9.000.000 per month,https:atauatauid.jobstreet.comataujobatau79645321,a retail garment sales executive plays a vital...,eksekutif penjualan,error: [errno 11001] getaddrinfo failed,"ritel dan produk mengkonsumsi, asist ritel",eksekutif penjualan
4,site project staff,project staff,vnv mandiri valve,"konstruksi, manajemen proyek","kabupaten bekasi, jawa barat",79912142,kontrak,NaN,rp 4.500.000 – rp 5.500.000 per month,https:atauatauid.jobstreet.comataujobatau79912142,"uraian tugas : menyusun rencana proyek, termas...",staf proyek situs,"uraian tugas : menyusun rencana proyek, termas...","konstruksi, manajemen proyek",staf proyek

In [51]:
df.drop_duplicates(subset="jobId", inplace=True)

In [52]:
df.head()

,title,role,company_name,category,location,jobId,type,benefit,salary,url,description,title_translated,description_translated,category_translated,role_translated
0,penerjemah bahasa mandarinasisten manajer umum,mandarin translator,onemate aksesoris mobil,"administrasi dan dukungan perkantoran, asisten...","tangerang, banten",79976110,full time,NaN,rp 8.500.000 – rp 12.500.000 per month,https:atauatauid.jobstreet.comataujobatau79976110,asisten manajer umum: • membantu manajer umum ...,penerjemah bahasa mandarin，asisten manajer umum,asisten manajer umum: • membantu manajer umum ...,"administrasi dan dukungan perkantoran, asisten...",mandarin-translator
1,it business analyst,information technology business analyst,nextalent talenta nusantara,"teknologi informasi dan komunikasi, analis bis...",jakarta raya,80187093,full time,NaN,rp 10.000.000 – rp 14.000.000 per month,https:atauatauid.jobstreet.comataujobatau80187093,qualification : candidate must possess at leas...,analis bisnis ti,error: [errno 11001] getaddrinfo failed,"teknolog informasi dan komununasi, anis bisnis...",informasi-teknologi-business-analyst
3,sales executive,sales executive,laxmi utama,"ritel dan produk konsumen, asisten ritel","surabaya, jawa timur",79645321,full time,"gaji pokok dan insentif, bpjs ketenaga kerjaan...",rp 6.000.000 – rp 9.000.000 per month,https:atauatauid.jobstreet.comataujobatau79645321,a retail garment sales executive plays a vital...,eksekutif penjualan,error: [errno 11001] getaddrinfo failed,"ritel dan produk mengkonsumsi, asist ritel",eksekutif penjualan
4,site project staff,project staff,vnv mandiri valve,"konstruksi, manajemen proyek","kabupaten bekasi, jawa barat",79912142,kontrak,NaN,rp 4.500.000 – rp 5.500.000 per month,https:atauatauid.jobstreet.comataujobatau79912142,"uraian tugas : menyusun rencana proyek, termas...",staf proyek situs,"uraian tugas : menyusun rencana proyek, termas...","konstruksi, manajemen proyek",staf proyek
5,kepala sipil struktur engineering,engineering,renon property emporio architect,"teknik, teknik sipilataustruktural","jakarta pusat, jakarta raya",80181996,full time,NaN,rp 8.000.000 – rp 8.100.000 per month,https:atauatauid.jobstreet.comataujobatau80181996,"kami, emporio architect . firma arsitektur yan...",kepala sipil atau struktur engineering,"kami, emporio architect . firma arsitektur yan...","teknik, teknik sipilataustruktural",rekayasa

# Category

In [53]:
#split kolom 'category' berdasarkan tanda koma (',')
categories_split = df['category'].str.split(',', expand=True)
categories_split.columns = [f'category_{i+1}' for i in range(categories_split.shape[1])]
df = pd.concat([df, categories_split], axis=1)
df.head()

,title,role,company_name,category,location,jobId,type,benefit,salary,url,description,title_translated,description_translated,category_translated,role_translated,category_1,category_2,category_3,category_4
0,penerjemah bahasa mandarinasisten manajer umum,mandarin translator,onemate aksesoris mobil,"administrasi dan dukungan perkantoran, asisten...","tangerang, banten",79976110,full time,NaN,rp 8.500.000 – rp 12.500.000 per month,https:atauatauid.jobstreet.comataujobatau79976110,asisten manajer umum: • membantu manajer umum ...,penerjemah bahasa mandarin，asisten manajer umum,asisten manajer umum: • membantu manajer umum ...,"administrasi dan dukungan perkantoran, asisten...",mandarin-translator,administrasi dan dukungan perkantoran,asisten administratif,None,None
1,it business analyst,information technology business analyst,nextalent talenta nusantara,"teknologi informasi dan komunikasi, analis bis...",jakarta raya,80187093,full time,NaN,rp 10.000.000 – rp 14.000.000 per month,https:atauatauid.jobstreet.comataujobatau80187093,qualification : candidate must possess at leas...,analis bisnis ti,error: [errno 11001] getaddrinfo failed,"teknolog informasi dan komununasi, anis bisnis...",informasi-teknologi-business-analyst,teknologi informasi dan komunikasi,analis bisnisatausistem,None,None
3,sales executive,sales executive,laxmi utama,"ritel dan produk konsumen, asisten ritel","surabaya, jawa timur",79645321,full time,"gaji pokok dan insentif, bpjs ketenaga kerjaan...",rp 6.000.000 – rp 9.000.000 per month,https:atauatauid.jobstreet.comataujobatau79645321,a retail garment sales executive plays a vital...,eksekutif penjualan,error: [errno 11001] getaddrinfo failed,"ritel dan produk mengkonsumsi, asist ritel",eksekutif penjualan,ritel dan produk konsumen,asisten ritel,None,None
4,site project staff,project staff,vnv mandiri valve,"konstruksi, manajemen proyek","kabupaten bekasi, jawa barat",79912142,kontrak,NaN,rp 4.500.000 – rp 5.500.000 per month,https:atauatauid.jobstreet.comataujobatau79912142,"uraian tugas : menyusun rencana proyek, termas...",staf proyek situs,"uraian tugas : menyusun rencana proyek, termas...","konstruksi, manajemen proyek",staf proyek,konstruksi,manajemen proyek,None,None
5,kepala sipil struktur engineering,engineering,renon property emporio architect,"teknik, teknik sipilataustruktural","jakarta pusat, jakarta raya",80181996,full time,NaN,rp 8.000.000 – rp 8.100.000 per month,https:atauatauid.jobstreet.comataujobatau80181996,"kami, emporio architect . firma arsitektur yan...",kepala sipil atau struktur engineering,"kami, emporio architect . firma arsitektur yan...","teknik, teknik sipilataustruktural",rekayasa,teknik,teknik sipilataustruktural,None,None

In [54]:
null_counts = df[['category_1', 'category_2', 'category_3', 'category_4']].isnull().sum()
print(null_counts)

category_1       0
category_2       0
category_3    5247
category_4    5843
dtype: int64

In [55]:
df.shape

(6128, 19)

In [56]:
columns_to_drop = ['category_3', 'category_4']
df.drop(columns=columns_to_drop, inplace=True)

In [57]:
df.head()

,title,role,company_name,category,location,jobId,type,benefit,salary,url,description,title_translated,description_translated,category_translated,role_translated,category_1,category_2
0,penerjemah bahasa mandarinasisten manajer umum,mandarin translator,onemate aksesoris mobil,"administrasi dan dukungan perkantoran, asisten...","tangerang, banten",79976110,full time,NaN,rp 8.500.000 – rp 12.500.000 per month,https:atauatauid.jobstreet.comataujobatau79976110,asisten manajer umum: • membantu manajer umum ...,penerjemah bahasa mandarin，asisten manajer umum,asisten manajer umum: • membantu manajer umum ...,"administrasi dan dukungan perkantoran, asisten...",mandarin-translator,administrasi dan dukungan perkantoran,asisten administratif
1,it business analyst,information technology business analyst,nextalent talenta nusantara,"teknologi informasi dan komunikasi, analis bis...",jakarta raya,80187093,full time,NaN,rp 10.000.000 – rp 14.000.000 per month,https:atauatauid.jobstreet.comataujobatau80187093,qualification : candidate must possess at leas...,analis bisnis ti,error: [errno 11001] getaddrinfo failed,"teknolog informasi dan komununasi, anis bisnis...",informasi-teknologi-business-analyst,teknologi informasi dan komunikasi,analis bisnisatausistem
3,sales executive,sales executive,laxmi utama,"ritel dan produk konsumen, asisten ritel","surabaya, jawa timur",79645321,full time,"gaji pokok dan insentif, bpjs ketenaga kerjaan...",rp 6.000.000 – rp 9.000.000 per month,https:atauatauid.jobstreet.comataujobatau79645321,a retail garment sales executive plays a vital...,eksekutif penjualan,error: [errno 11001] getaddrinfo failed,"ritel dan produk mengkonsumsi, asist ritel",eksekutif penjualan,ritel dan produk konsumen,asisten ritel
4,site project staff,project staff,vnv mandiri valve,"konstruksi, manajemen proyek","kabupaten bekasi, jawa barat",79912142,kontrak,NaN,rp 4.500.000 – rp 5.500.000 per month,https:atauatauid.jobstreet.comataujobatau79912142,"uraian tugas : menyusun rencana proyek, termas...",staf proyek situs,"uraian tugas : menyusun rencana proyek, termas...","konstruksi, manajemen proyek",staf proyek,konstruksi,manajemen proyek
5,kepala sipil struktur engineering,engineering,renon property emporio architect,"teknik, teknik sipilataustruktural","jakarta pusat, jakarta raya",80181996,full time,NaN,rp 8.000.000 – rp 8.100.000 per month,https:atauatauid.jobstreet.comataujobatau80181996,"kami, emporio architect . firma arsitektur yan...",kepala sipil atau struktur engineering,"kami, emporio architect . firma arsitektur yan...","teknik, teknik sipilataustruktural",rekayasa,teknik,teknik sipilataustruktural

In [58]:
df[['category_1', 'category_2']] = df[['category_1', 'category_2']].replace({'&': 'dan', '/': 'atau'}, regex=True)
df['category_2'] = df['category_2'].str.split('-', n=1).str[0] #ambil hanya kata sebelum -

# Location

In [59]:
unique_locations = df['location'].unique()
for location in unique_locations:
    print(location)

tangerang, banten
jakarta raya
surabaya, jawa timur
kabupaten bekasi, jawa barat
jakarta pusat, jakarta raya
jakarta selatan, jakarta raya
badung, bali
cikarang
jakarta barat, jakarta raya
bali
bekasi, jawa barat
pamulang, banten
jawa barat
cikarang pusat, jawa barat
jakarta utara, jakarta raya
parung, jawa barat
pekanbaru, riau
sidoarjo, jawa timur
makassar, sulawesi selatan
palembang, sumatera selatan
banyumas, jawa tengah
denpasar, bali
batam, kepulauan riau
salatiga, jawa tengah
bantul, di yogyakarta
bandung, jawa barat
tangerang selatan, banten
jakarta timur, jakarta raya
pasuruan, jawa timur
karang tengah, banten
tanah abang, jakarta raya
di yogyakarta
kabupaten tangerang, banten
jawa timur
samarinda, kalimantan timur
balikpapan timur, kalimantan timur
semarang, jawa tengah
kabupaten bantul, di yogyakarta
driyorejo, jawa timur
sukoharjo, jawa tengah
yogyakarta, di yogyakarta
timika, papua tengah
serang, banten
cikarang selatan, jawa barat
sleman, di yogyakarta
bogor, jawa barat
kebon jeruk, jakarta raya
kota kediri, jawa timur
kuta selatan, bali
depok, jawa barat
kelapa gading, jakarta raya
denpasar utara, bali
jawa tengah
waru, jawa timur
bandar lampung, lampung
kalideres, jakarta raya
balikpapan, kalimantan timur
tegal, jawa tengah
pulo gadung, jakarta raya
manado, sulawesi utara
maluku utara
morowali, sulawesi tengah
karawang, jawa barat
pancoran, jakarta raya
cileungsi, jawa barat
gambir, jakarta raya
ngawi, jawa timur
penjaringan, jakarta raya
cengkareng, jakarta raya
karawaci, banten
kalimantan timur
pematangsiantar, sumatera utara
sumatera utara
ciracas, jakarta raya
tabanan, bali
kutai barat, kalimantan timur
pontianak, kalimantan barat
gunung putri, jawa barat
teluknaga, banten
banjaran, jawa barat
klaten, jawa tengah
prambanan, jawa tengah
curug, banten
balaraja, banten
cipondoh, banten
boyolali, jawa tengah
bantaeng, sulawesi selatan
medan, sumatera utara
demak, jawa tengah
kutai timur, kalimantan timur
kupang, nusa tenggara timur
sumatera selatan
kabupaten pasuruan, jawa timur
kalijati, jawa barat
gedangan, jawa timur
cilandak, jakarta raya
cimanggis, jawa barat
sulawesi tengah
sulawesi utara
kabupaten bogor, jawa barat
pangkal pinang, bangka belitung
karawang timur, jawa barat
musi banyuasin, sumatera selatan
bintan, kepulauan riau
denpasar timur, bali
gorontalo
teluk bintuni, papua barat
kalimantan selatan
nusa tenggara timur
serpong, banten
cianjur, jawa barat
malang, jawa timur
genteng, jawa timur
banten
bogor timur, jawa barat
batam kota, kepulauan riau
cibinong, jawa barat
kembangan, jakarta raya
kabupaten semarang, jawa tengah
pare-pare, sulawesi selatan
obi, maluku utara
benda, banten
indragiri hilir, riau
banjarmasin, kalimantan selatan
purwakarta, jawa barat
cilacap, jawa tengah
cinere, jawa barat
cilodong, jawa barat
sikka, nusa tenggara timur
surakarta, jawa tengah
seminyak, bali
tayan hilir, kalimantan barat
plumbon, jawa barat
sragen, jawa tengah
kendal, jawa tengah
jombang, jawa timur
tarakan, kalimantan utara
abiansemal, bali
mojokerto, jawa timur
kuta, bali
brebes, jawa tengah
sangatta utara, kalimantan timur
palopo, sulawesi selatan
wiyung, jawa timur
padang, sumatera barat
sumbawa
cirebon, jawa barat
sukabumi, jawa barat
tanjung priok, jakarta raya
cilegon, banten
bangka
indonesia
singkawang, kalimantan barat
cibitung, jawa barat
cakung, jakarta raya
kecamatan tangerang, banten
gombong, jawa tengah
pasar minggu, jakarta raya
kalimantan barat
lampung tengah, lampung
pakuhaji, banten
garut, jawa barat
kabupaten malang, jawa timur
jember, jawa timur
balikpapan selatan, kalimantan timur
subang, jawa barat
gresik, jawa timur
cikupa, banten
dukuh pakis, jawa timur
cimahi, jawa barat
setiabudi, jakarta raya
grogol petamburan, jakarta raya
banjarbaru, kalimantan selatan
jepara, jawa tengah
kabupaten cianjur, jawa barat
kalimantan tengah
bantargebang, jawa barat
karanganyar, jawa tengah
bandung barat, jawa barat
sumedang, jawa barat
batang, jawa tengah
wonosobo, jawa tengah
blitar, jawa timur
wajo, sulawesi selatan
kosambi, banten
prambon, jawa timur
batuceper, banten
kabupaten kendal, jawa tengah
pekalongan, jawa tengah
denpasar selatan, bali
semarang timur, jawa tengah
rajeg, banten
cikande, banten
pondokgede, jawa barat
denpasar barat, bali
kabupaten bandung, jawa barat
kabupaten serang, banten
tegal timur, jawa tengah
jawilan, banten
singosari, jawa timur
tebing tinggi, sumatera utara
percut sei tuan, sumatera utara
serpong utara, banten
sekongkang, nusa tenggara barat
semarang tengah, jawa tengah
gempol, jawa timur
balikpapan kota, kalimantan timur
bekasi barat, jawa barat
lumajang, jawa timur
sorong, papua barat
nusa tenggara barat
medan kota, sumatera utara
sambikerep, jawa timur
mamuju, sulawesi barat
ternate, maluku utara
labuhan ratu, lampung
arut selatan, kalimantan tengah
lampung
magelang tengah, jawa tengah
kisaran
cisalak, jawa barat
tebet, jakarta raya
gianyar, bali
menteng, jakarta raya
lombok
mijen, jawa tengah
gunungsitoli, sumatera utara
sulawesi selatan
caringin, jawa barat
kediri, jawa timur
pati, jawa tengah
pataruman, jawa barat
lampung selatan, lampung
kabupaten probolinggo, jawa timur
indramayu, jawa barat
ambon, maluku
batu licin, kalimantan selatan
dumai, riau
kemayoran, jakarta raya
jayapura, papua
jonggol, jawa barat
kalimantan utara
ogan komering ilir, sumatera selatan
magelang, jawa tengah
krembangan, jawa timur
ranca bungur, jawa barat
balige, sumatera utara
kabupaten purwakarta, jawa barat
bandung wetan, jawa barat
pekanbaru kota, riau
banjarsari, jawa tengah
cisauk, banten
tigaraksa, banten
babelan, jawa barat
palangkaraya, kalimantan tengah
beji, jawa timur
rembang, jawa tengah
tapos, jawa barat
stabat, sumatera utara
bogor tengah, jawa barat
tasikmalaya, jawa barat
kendari, sulawesi tenggara
karimun, kepulauan riau
kabupaten cirebon, jawa barat
klungkung, bali
kuala kencana, papua tengah
gamping, di yogyakarta
semarang barat, jawa tengah
sumba barat, nusa tenggara timur
riau
pesanggrahan, jakarta raya
palu, sulawesi tengah
dayeuhkolot, jawa barat
kota gorontalo, gorontalo
bungursari, jawa barat
banyuwangi, jawa timur
trenggalek, jawa timur
kulon progo, di yogyakarta
kudus, jawa tengah
rancaekek, jawa barat
majalengka, jawa barat
ciledug, banten
lubuk linggau, sumatera selatan
kaliwungu, jawa tengah
depok, di yogyakarta
lamongan, jawa timur
tanggeung, jawa barat
karawang barat, jawa barat
bogor barat, jawa barat
parung panjang, jawa barat
tanjung morawa, sumatera utara
plered, jawa barat
medan belawan, sumatera utara
bojongsoang, jawa barat
bengkulu
madiun, jawa timur
kabupaten batang, jawa tengah
kabupaten magelang, jawa tengah
sumbawa barat, nusa tenggara barat
bekasi utara, jawa barat
manokwari, papua barat
suppa, sulawesi selatan
prabumulih, sumatera selatan
teweh tengah, kalimantan tengah
balong bendo, jawa timur
samarinda kota, kalimantan timur
ngadiluwih, jawa timur
sipora selatan, sumatera barat
purbalingga, jawa tengah
musi rawas utara, sumatera selatan
serang baru, jawa barat
taman sari, jakarta raya
pinrang, sulawesi selatan
kabupaten jepara, jawa tengah
batang kuis, sumatera utara
sawahan, jawa timur
tambora, jakarta raya
medan area, sumatera utara
ubud, bali
kabupaten indramayu, jawa barat
cempaka putih, jakarta raya
kota atambua, nusa tenggara timur
ciputat, banten
bogor selatan, jawa barat
gowa, sulawesi selatan
pemalang, jawa tengah
kabupaten demak, jawa tengah
kebayoran lama, jakarta raya
bangka belitung
medan deli, sumatera utara
jambi
umbulharjo, di yogyakarta
pal merah, jakarta raya
citeureup, jawa barat
labuhanbatu, sumatera utara
berastagi, sumatera utara
probolinggo, jawa timur
ngamprah, jawa barat
jayapura utara, papua
kupang timur, nusa tenggara timur
pademangan, jakarta raya
batu, jawa timur
suko manunggal, jawa timur
kuta utara, bali
medan johor, sumatera utara
bontang, kalimantan timur
tarumajaya, jawa barat
buleleng, bali
maros, sulawesi selatan
duren sawit, jakarta raya
ciparay, jawa barat
binjai, sumatera utara
gunung sindur, jawa barat
sulawesi barat
kabupaten gianyar, bali
kabupaten sragen, jawa tengah
garut kota, jawa barat
kota jambi, jambi
kepulauan riau
matraman, jakarta raya
ngantru, jawa timur
tegalsari, jawa timur
legok, banten
kabupaten karanganyar, jawa tengah
selagai lingga, lampung
karangasem, bali
kabupaten gorontalo, gorontalo
sawah besar, jakarta raya
minahasa, sulawesi utara
pasaman, sumatera barat
luwu, sulawesi selatan

In [60]:
#ambil bagian setelah koma saja
df['location'] = df['location'].apply(lambda x: x.split(',', 1)[1] if ',' in str(x) else x)

In [61]:
unique_locations = df['location'].unique()
for location in unique_locations:
    print(location)

 banten
jakarta raya
 jawa timur
 jawa barat
 jakarta raya
 bali
cikarang
bali
jawa barat
 riau
 sulawesi selatan
 sumatera selatan
 jawa tengah
 kepulauan riau
 di yogyakarta
di yogyakarta
jawa timur
 kalimantan timur
 papua tengah
jawa tengah
 lampung
 sulawesi utara
maluku utara
 sulawesi tengah
kalimantan timur
 sumatera utara
sumatera utara
 kalimantan barat
 nusa tenggara timur
sumatera selatan
sulawesi tengah
sulawesi utara
 bangka belitung
gorontalo
 papua barat
kalimantan selatan
nusa tenggara timur
banten
 maluku utara
 kalimantan selatan
 kalimantan utara
 sumatera barat
sumbawa
bangka
indonesia
kalimantan barat
kalimantan tengah
 nusa tenggara barat
nusa tenggara barat
 sulawesi barat
 kalimantan tengah
lampung
kisaran
lombok
sulawesi selatan
 maluku
 papua
kalimantan utara
 sulawesi tenggara
riau
 gorontalo
bengkulu
bangka belitung
jambi
sulawesi barat
 jambi
kepulauan riau

In [62]:
df['location'].isnull().sum()

0

In [63]:
df['location'] = df['location'].str.replace('cikarang', 'jawa barat')
df['location'] = df['location'].str.replace('lombok', 'nusa tenggara barat')
df['location'] = df['location'].str.replace('bangka', 'bangka belitung')
df['location'] = df['location'].str.replace('kisaran', 'sumatra utara')
df['location'] = df['location'].str.replace('sumbawa', 'nusa tenggara barat')

In [64]:
unique_locations = df['location'].unique()
for location in unique_locations:
    print(location)

 banten
jakarta raya
 jawa timur
 jawa barat
 jakarta raya
 bali
jawa barat
bali
 riau
 sulawesi selatan
 sumatera selatan
 jawa tengah
 kepulauan riau
 di yogyakarta
di yogyakarta
jawa timur
 kalimantan timur
 papua tengah
jawa tengah
 lampung
 sulawesi utara
maluku utara
 sulawesi tengah
kalimantan timur
 sumatera utara
sumatera utara
 kalimantan barat
 nusa tenggara timur
sumatera selatan
sulawesi tengah
sulawesi utara
 bangka belitung belitung
gorontalo
 papua barat
kalimantan selatan
nusa tenggara timur
banten
 maluku utara
 kalimantan selatan
 kalimantan utara
 sumatera barat
nusa tenggara barat
bangka belitung
indonesia
kalimantan barat
kalimantan tengah
 nusa tenggara barat
 sulawesi barat
 kalimantan tengah
lampung
sumatra utara
sulawesi selatan
 maluku
 papua
kalimantan utara
 sulawesi tenggara
riau
 gorontalo
bengkulu
bangka belitung belitung
jambi
sulawesi barat
 jambi
kepulauan riau

In [65]:
df['location'] = df['location'].str.replace('bangka belitung belitung', 'bangka belitung')

In [66]:
unique_locations = df['location'].unique()
for location in unique_locations:
    print(location)

 banten
jakarta raya
 jawa timur
 jawa barat
 jakarta raya
 bali
jawa barat
bali
 riau
 sulawesi selatan
 sumatera selatan
 jawa tengah
 kepulauan riau
 di yogyakarta
di yogyakarta
jawa timur
 kalimantan timur
 papua tengah
jawa tengah
 lampung
 sulawesi utara
maluku utara
 sulawesi tengah
kalimantan timur
 sumatera utara
sumatera utara
 kalimantan barat
 nusa tenggara timur
sumatera selatan
sulawesi tengah
sulawesi utara
 bangka belitung
gorontalo
 papua barat
kalimantan selatan
nusa tenggara timur
banten
 maluku utara
 kalimantan selatan
 kalimantan utara
 sumatera barat
nusa tenggara barat
bangka belitung
indonesia
kalimantan barat
kalimantan tengah
 nusa tenggara barat
 sulawesi barat
 kalimantan tengah
lampung
sumatra utara
sulawesi selatan
 maluku
 papua
kalimantan utara
 sulawesi tenggara
riau
 gorontalo
bengkulu
jambi
sulawesi barat
 jambi
kepulauan riau

In [67]:
df['location'] = df['location'].str.strip().str.replace(r'\s+', ' ', regex=True)
location_counts = df['location'].value_counts()
for location, count in location_counts.items():
    print(f'{location}: {count}')

jakarta raya: 2887
jawa barat: 725
banten: 646
jawa timur: 554
bali: 398
jawa tengah: 244
di yogyakarta: 117
sumatera utara: 106
kepulauan riau: 68
kalimantan timur: 59
sulawesi selatan: 46
sumatera selatan: 43
riau: 32
kalimantan selatan: 29
sulawesi utara: 20
nusa tenggara barat: 17
kalimantan barat: 17
sulawesi tengah: 15
lampung: 13
kalimantan tengah: 13
nusa tenggara timur: 11
maluku utara: 9
kalimantan utara: 8
bangka belitung: 7
sumatera barat: 7
papua barat: 6
gorontalo: 5
maluku: 4
papua: 4
bengkulu: 3
sulawesi tenggara: 3
papua tengah: 3
indonesia: 3
sumatra utara: 2
sulawesi barat: 2
jambi: 2

In [68]:
df.head()

,title,role,company_name,category,location,jobId,type,benefit,salary,url,description,title_translated,description_translated,category_translated,role_translated,category_1,category_2
0,penerjemah bahasa mandarinasisten manajer umum,mandarin translator,onemate aksesoris mobil,"administrasi dan dukungan perkantoran, asisten...",banten,79976110,full time,NaN,rp 8.500.000 – rp 12.500.000 per month,https:atauatauid.jobstreet.comataujobatau79976110,asisten manajer umum: • membantu manajer umum ...,penerjemah bahasa mandarin，asisten manajer umum,asisten manajer umum: • membantu manajer umum ...,"administrasi dan dukungan perkantoran, asisten...",mandarin-translator,administrasi dan dukungan perkantoran,asisten administratif
1,it business analyst,information technology business analyst,nextalent talenta nusantara,"teknologi informasi dan komunikasi, analis bis...",jakarta raya,80187093,full time,NaN,rp 10.000.000 – rp 14.000.000 per month,https:atauatauid.jobstreet.comataujobatau80187093,qualification : candidate must possess at leas...,analis bisnis ti,error: [errno 11001] getaddrinfo failed,"teknolog informasi dan komununasi, anis bisnis...",informasi-teknologi-business-analyst,teknologi informasi dan komunikasi,analis bisnisatausistem
3,sales executive,sales executive,laxmi utama,"ritel dan produk konsumen, asisten ritel",jawa timur,79645321,full time,"gaji pokok dan insentif, bpjs ketenaga kerjaan...",rp 6.000.000 – rp 9.000.000 per month,https:atauatauid.jobstreet.comataujobatau79645321,a retail garment sales executive plays a vital...,eksekutif penjualan,error: [errno 11001] getaddrinfo failed,"ritel dan produk mengkonsumsi, asist ritel",eksekutif penjualan,ritel dan produk konsumen,asisten ritel
4,site project staff,project staff,vnv mandiri valve,"konstruksi, manajemen proyek",jawa barat,79912142,kontrak,NaN,rp 4.500.000 – rp 5.500.000 per month,https:atauatauid.jobstreet.comataujobatau79912142,"uraian tugas : menyusun rencana proyek, termas...",staf proyek situs,"uraian tugas : menyusun rencana proyek, termas...","konstruksi, manajemen proyek",staf proyek,konstruksi,manajemen proyek
5,kepala sipil struktur engineering,engineering,renon property emporio architect,"teknik, teknik sipilataustruktural",jakarta raya,80181996,full time,NaN,rp 8.000.000 – rp 8.100.000 per month,https:atauatauid.jobstreet.comataujobatau80181996,"kami, emporio architect . firma arsitektur yan...",kepala sipil atau struktur engineering,"kami, emporio architect . firma arsitektur yan...","teknik, teknik sipilataustruktural",rekayasa,teknik,teknik sipilataustruktural

# JobId

In [69]:
#tidak di apa-apakan

# Benefit

In [70]:
df['benefit'].isnull().sum()

3906

In [71]:
df.shape

(6128, 17)

In [72]:
#lebih dari 50% missing value sehingga kolom benefit dihapus

df.drop(columns='benefit', inplace=True)

In [73]:
df.head(2)

,title,role,company_name,category,location,jobId,type,salary,url,description,title_translated,description_translated,category_translated,role_translated,category_1,category_2
0,penerjemah bahasa mandarinasisten manajer umum,mandarin translator,onemate aksesoris mobil,"administrasi dan dukungan perkantoran, asisten...",banten,79976110,full time,rp 8.500.000 – rp 12.500.000 per month,https:atauatauid.jobstreet.comataujobatau79976110,asisten manajer umum: • membantu manajer umum ...,penerjemah bahasa mandarin，asisten manajer umum,asisten manajer umum: • membantu manajer umum ...,"administrasi dan dukungan perkantoran, asisten...",mandarin-translator,administrasi dan dukungan perkantoran,asisten administratif
1,it business analyst,information technology business analyst,nextalent talenta nusantara,"teknologi informasi dan komunikasi, analis bis...",jakarta raya,80187093,full time,rp 10.000.000 – rp 14.000.000 per month,https:atauatauid.jobstreet.comataujobatau80187093,qualification : candidate must possess at leas...,analis bisnis ti,error: [errno 11001] getaddrinfo failed,"teknolog informasi dan komununasi, anis bisnis...",informasi-teknologi-business-analyst,teknologi informasi dan komunikasi,analis bisnisatausistem

# Salary

In [97]:
salary_counts = df['salary'].value_counts()
for salary, count in salary_counts.items():
    print(f'{salary}: {count}')

rp 5.000.000 – rp 7.000.000 per month: 236
rp 4.000.000 – rp 6.000.000 per month: 198
rp 5.000.000 – rp 6.000.000 per month: 197
rp 10.000.000 – rp 15.000.000 per month: 170
rp 6.000.000 – rp 8.000.000 per month: 163
rp 4.000.000 – rp 5.000.000 per month: 163
rp 7.000.000 – rp 10.000.000 per month: 143
rp 8.000.000 – rp 12.000.000 per month: 128
rp 6.000.000 – rp 7.000.000 per month: 103
rp 6.000.000 – rp 9.000.000 per month: 102
rp 5.000.000 – rp 7.500.000 per month: 99
rp 8.000.000 – rp 10.000.000 per month: 99
rp 3.500.000 – rp 5.000.000 per month: 97
rp 3.000.000 – rp 4.000.000 per month: 75
rp 3.000.000 – rp 4.500.000 per month: 73
rp 15.000.000 – rp 20.000.000 per month: 65
rp 5.500.000 – rp 8.000.000 per month: 65
rp 4.500.000 – rp 6.000.000 per month: 64
rp 7.000.000 – rp 9.000.000 per month: 63
rp 3.500.000 – rp 4.500.000 per month: 62
rp 4.500.000 – rp 5.500.000 per month: 60
rp 4.500.000 – rp 5.000.000 per month: 58
rp 3.500.000 – rp 4.000.000 per month: 56
rp 10.000.000 – rp 12.000.000 per month: 56
rp 5.000.000 – rp 6.500.000 per month: 56
rp 5.000.000 – rp 5.500.000 per month: 52
rp 4.500.000 – rp 6.500.000 per month: 52
rp 4.000.000 – rp 4.500.000 per month: 51
rp 5.500.000 – rp 6.500.000 per month: 48
rp 5.500.000 – rp 7.000.000 per month: 48
rp 7.000.000 – rp 8.000.000 per month: 46
rp 5,000,000 – rp 7,000,000 per month: 43
rp 2.500.000 – rp 3.000.000 per month: 42
rp 3.000.000 – rp 3.500.000 per month: 41
rp 4.000.000 – rp 5.500.000 per month: 37
rp 4,000,000 – rp 6,000,000 per month: 35
rp 6.000.000 – rp 7.500.000 per month: 35
rp 5,000,000 – rp 6,000,000 per month: 35
rp 12.000.000 – rp 15.000.000 per month: 33
rp 9.000.000 – rp 12.000.000 per month: 31
rp 20.000.000 – rp 25.000.000 per month: 31
rp 5.500.000 – rp 6.000.000 per month: 30
rp 20.000.000 – rp 30.000.000 per month: 30
rp 9.000.000 – rp 13.000.000 per month: 30
rp 2.500.000 – rp 3.500.000 per month: 29
rp 8.000.000 – rp 11.000.000 per month: 29
rp 2.000.000 – rp 3.000.000 per month: 27
rp 10.000.000 – rp 13.000.000 per month: 26
rp 7,000,000 – rp 10,000,000 per month: 26
rp 10,000,000 – rp 15,000,000 per month: 26
rp 12.000.000 – rp 18.000.000 per month: 26
rp 8,000,000 – rp 12,000,000 per month: 23
rp 5.500.000 – rp 7.500.000 per month: 22
rp 6,000,000 – rp 8,000,000 per month: 22
rp 6.500.000 – rp 8.000.000 per month: 21
rp 6.500.000 – rp 7.500.000 per month: 20
rp 2.000.000 – rp 2.500.000 per month: 18
rp 8,000,000 – rp 10,000,000 per month: 18
rp 9.000.000 – rp 11.000.000 per month: 18
rp 4,000,000 – rp 5,000,000 per month: 17
rp 3,000,000 – rp 4,000,000 per month: 17
rp 7.500.000 – rp 10.000.000 per month: 17
rp 8.000.000 – rp 9.000.000 per month: 16
rp 6.000.000 – rp 6.500.000 per month: 16
rp 7.000.000 – rp 8.500.000 per month: 16
rp 4,500,000 – rp 5,000,000 per month: 15
rp 14.000.000 – rp 20.000.000 per month: 15
rp 6.000.000 – rp 8.500.000 per month: 15
rp 10.000.000 – rp 14.000.000 per month: 14
rp 6.700.000 – rp 10.000.000 per month: 14
rp 4.700.000 – rp 7.000.000 per month: 13
rp 7.000.000 – rp 10.500.000 per month: 13
rp 6.500.000 – rp 9.000.000 per month: 12
rp 15.000.000 – rp 22.000.000 per month: 12
rp 6,000,000 – rp 9,000,000 per month: 12
rp 6,000,000 – rp 7,000,000 per month: 11
rp 12.000.000 – rp 17.000.000 per month: 11
rp 9.000.000 – rp 13.500.000 per month: 11
rp 18.000.000 – rp 25.000.000 per month: 11
rp 5,500,000 – rp 7,000,000 per month: 11
rp 5,500,000 – rp 8,000,000 per month: 11
rp 3,500,000 – rp 4,500,000 per month: 11
rp 17.000.000 – rp 25.000.000 per month: 10
rp 30.000.000 – rp 40.000.000 per month: 10
rp 4.800.000 – rp 5.500.000 per month: 10
rp 2,500,000 – rp 3,250,000 per month: 10
rp 7.500.000 – rp 11.000.000 per month: 10
rp 15,000,000 – rp 20,000,000 per month: 10
rp 25.000.000 – rp 30.000.000 per month: 10
rp 7.500.000 – rp 9.000.000 per month: 10
rp 4,500,000 – rp 5,500,000 per month: 10
rp 5.000.000 per month: 10
rp 3,000,000 – rp 4,500,000 per month: 10
rp 6.500.000 – rp 9.500.000 per month: 10
rp 15.000.000 – rp 22.500.000 per month: 9
rp 10,000,000 – rp 13,000,000 per month: 9
rp 4,500,000 – rp 6,500,000 per month: 9
rp 13.000.000 – rp 18.000.000 per month: 9
rp 3.500.000 – rp 5.250.000 per month: 9
rp 5.000.000 – rp 5.200.000 per month: 9
rp 2.700.000 – rp 4.000.000 per month: 9
rp 7,000,000 – rp 9,000,000 per month: 9
rp 2,000,000 – rp 3,000,000 per month: 9
rp 9.000.000 – rp 10.000.000 per month: 9
rp 3,500,000 – rp 4,000,000 per month: 8
rp 12.000.000 – rp 14.000.000 per month: 8
rp 7.000.000 – rp 9.500.000 per month: 8
rp 5.100.000 – rp 7.000.000 per month: 8
rp 11.000.000 – rp 14.000.000 per month: 8
rp 3,500,000 – rp 5,000,000 per month: 8
rp 2.500.000 – rp 3.200.000 per month: 8
rp 3,600,000 – rp 5,400,000 per month: 8
rp 7.500.000 – rp 8.500.000 per month: 8
rp 4,500,000 – rp 6,000,000 per month: 7
rp 13.500.000 – rp 20.000.000 per month: 7
rp 4.600.000 – rp 6.000.000 per month: 7
rp 6.500.000 – rp 8.500.000 per month: 7
rp 5,000,000 – rp 5,500,000 per month: 7
rp 11.000.000 – rp 16.000.000 per month: 7
rp 14.000.000 – rp 17.000.000 per month: 7
rp 15.000.000 – rp 17.000.000 per month: 7
rp 5.100.000 – rp 6.000.000 per month: 7
rp 3.000.000 – rp 3.300.000 per month: 7
rp 4.600.000 – rp 5.000.000 per month: 7
rp 10,000,000 – rp 14,000,000 per month: 7
rp 5.200.000 – rp 6.500.000 per month: 7
rp 2.500.000 – rp 3.750.000 per month: 7
rp 6.000.000 per month: 6
rp 10.000.000 – rp 11.000.000 per month: 6
rp 4.500.000 – rp 6.750.000 per month: 6
rp 4.800.000 – rp 7.000.000 per month: 6
rp 11.000.000 – rp 15.000.000 per month: 6
rp 15.000.000 – rp 18.000.000 per month: 6
rp 3,000,000 – rp 3,500,000 per month: 6
rp 12.000.000 – rp 16.000.000 per month: 6
rp 10.000.000 – rp 12.500.000 per month: 6
rp 4.700.000 – rp 6.000.000 per month: 6
rp 5.333.333 – rp 8.000.000 per month: 6
rp 1.500.000 – rp 2.000.000 per month: 6
rp 25.000.000 – rp 35.000.000 per month: 6
rp 13.000.000 – rp 17.000.000 per month: 6
rp 5.100.000 – rp 5.500.000 per month: 6
rp 4,000,000 – rp 4,500,000 per month: 6
rp 5,000,000 – rp 7,500,000 per month: 6
rp 9.500.000 – rp 14.000.000 per month: 6
rp 8,000,000 – rp 11,000,000 per month: 6
rp 3.400.000 – rp 5.000.000 per month: 6
idr 5,000,000 - 7,000,000: 6
rp 5,500,000 – rp 6,500,000 per month: 6
rp 4,000,000 – rp 5,600,000 per month: 6
rp 4,000,000 – rp 5,500,000 per month: 5
rp 2.800.000 – rp 3.500.000 per month: 5
rp 3.300.000 – rp 4.950.000 per month: 5
rp 10,000,000 – rp 12,000,000 per month: 5
rp 6.500.000 – rp 7.000.000 per month: 5
rp6.000.000 – rp9.000.000 per month: 5
rp 15,000,000 – rp 22,000,000 per month: 5
rp 4.000.000 per month: 5
rp 5.067.381 – rp 5.500.000 per month: 5
rp 5.200.000 – rp 6.000.000 per month: 5
rp 3.750.000 – rp 4.500.000 per month: 5
rp 4.000.000 – rp 4.800.000 per month: 5
rp 4.500.000 – rp 5.300.000 per month: 5
rp 2.800.000 – rp 4.000.000 per month: 5
idr 4,500,000 - 5,500,000: 5
rp 4.000.000 – rp 4.200.000 per month: 5
rp 3.700.000 – rp 5.000.000 per month: 5
rp 8.500.000 – rp 12.500.000 per month: 5
rp 5,500,000 – rp 6,000,000 per month: 5
rp 5.400.000 – rp 8.000.000 per month: 5
rp 5.000.000 – rp 5.067.381 per month: 5
rp 18.000.000 – rp 20.000.000 per month: 5
idr 5,500,000 - 6,500,000: 5
idr 4,000,000 - 5,600,000: 5
rp5.000.000 – rp7.000.000 per month: 5
rp 4.800.000 – rp 6.000.000 per month: 5
rp 4.700.000 – rp 5.500.000 per month: 5
rp 16.000.000 – rp 20.000.000 per month: 5
rp 8.500.000 – rp 12.000.000 per month: 5
rp 5.100.000 – rp 6.500.000 per month: 5
rp 12,000,000 – rp 18,000,000 per month: 4
rp 4.200.000 – rp 4.500.000 per month: 4
rp 3.800.000 – rp 5.000.000 per month: 4
rp 13.000.000 – rp 15.000.000 per month: 4
rp 5.000.000 – rp 5.100.000 per month: 4
rp 3,000,000 – rp 4,200,000 per month: 4
rp 18.000.000 – rp 23.000.000 per month: 4
rp 5.068.000 – rp 5.500.000 per month: 4
rp 8.500.000 – rp 11.500.000 per month: 4
rp 6.666.667 – rp 10.000.000 per month: 4
idr 5,000,000 - 6,000,000: 4
rp 17.000.000 – rp 20.000.000 per month: 4
rp 2,500,000 – rp 3,500,000 per month: 4
rp 7.000.000 – rp 7.500.000 per month: 4
rp 3.452.000 – rp 5.000.000 per month: 4
rp 4.700.000 – rp 5.000.000 per month: 4
rp 7.500.000 – rp 8.000.000 per month: 4
rp 5.500.000 – rp 8.250.000 per month: 4
rp 2.800.000 – rp 4.200.000 per month: 4
rp 2.000.000 per month: 4
rp 7,000,000 – rp 8,000,000 per month: 4
rp 5,000,000 – rp 6,500,000 per month: 4
rp 8.000.000 – rp 8.500.000 per month: 4
rp 3.500.000 – rp 4.200.000 per month: 4
rp 14,000,000 – rp 20,000,000 per month: 4
rp 3.000.000 per month: 4
rp 13.333.333 – rp 20.000.000 per month: 4
rp 3,200,000 – rp 4,800,000 per month: 4
rp 6,000,000 – rp 7,500,000 per month: 4
rp 10.000.000 per month: 4
rp 4.000.000 – rp 4.600.000 per month: 4
rp 3.200.000 – rp 4.800.000 per month: 4
rp 5.200.000 – rp 5.500.000 per month: 4
rp 5.000.000 – rp 6.200.000 per month: 3
rp 4.750.000 – rp 7.000.000 per month: 3
rp 2.200.000 – rp 3.000.000 per month: 3
rp 6,500,000 – rp 9,500,000 per month: 3
rp 3.750.000 – rp 5.500.000 per month: 3
rp 11,000,000 – rp 15,000,000 per month: 3
rp 9,000,000 – rp 12,000,000 per month: 3
rp 6,000,000 – rp 8,500,000 per month: 3
rp 7,500,000 – rp 10,000,000 per month: 3
rp 8.700.000 – rp 13.000.000 per month: 3
rp 5,000,000 per month: 3
rp 5.067.381 – rp 6.000.000 per month: 3
rp 12,000,000 – rp 15,000,000 per month: 3
rp 2,500,000 – rp 3,200,000 per month: 3
rp 16.000.000 – rp 18.000.000 per month: 3
rp 100.000 – rp 150.000 per hour: 3
idr 4,000,000 - 5,000,000: 3
rp 8.666.667 – rp 13.000.000 per month: 3
rp 3.000.000 – rp 3.200.000 per month: 3
idr 4,000,000 - 6,000,000: 3
idr 7,000,000 - 9,000,000: 3
idr 7,000,000 - 9,100,000: 3
rp 6,500,000 – rp 8,000,000 per month: 3
rp 6,500,000 – rp 8,500,000 per month: 3
rp 4.000.000 – rp 5.200.000 per month: 3
rp 3.100.000 – rp 4.000.000 per month: 3
rp 13,000,000 – rp 18,000,000 per month: 3
rp 4.400.000 – rp 4.500.000 per month: 3
rp 8,000,000 – rp 9,000,000 per month: 3
rp 4.250.000 – rp 6.375.000 per month: 3
rp 4.600.000 – rp 5.500.000 per month: 3
rp 14.000.000 – rp 16.000.000 per month: 3
rp 3.500.000 per month: 3
rp 8.500.000 – rp 9.000.000 per month: 3
rp 3.800.000 – rp 4.300.000 per month: 3
rp 3.800.000 – rp 5.500.000 per month: 3
rp 5,500,000 – rp 7,500,000 per month: 3
rp 8.000.000 – rp 9.500.000 per month: 3
rp 3.300.000 – rp 4.000.000 per month: 3
rp 9.000.000 – rp 11.500.000 per month: 3
rp 5.000.000 – rp 5.300.000 per month: 3
rp 15.000.000 – rp 19.000.000 per month: 3
rp 3,500,000 – rp 4,900,000 per month: 3
$70,000 – $100,000 per month: 3
rp 2.900.000 – rp 3.500.000 per month: 3
rp 4.750.000 – rp 5.500.000 per month: 3
rp 3.500.000 – rp 5.200.000 per month: 3
rp 2.200.000 – rp 3.300.000 per month: 3
rp 7.500.000 – rp 9.500.000 per month: 3
rp 3.500.000 – rp 4.700.000 per month: 3
rp 3.700.000 – rp 4.500.000 per month: 3
rp 35.000.000 – rp 50.000.000 per month: 3
rp7.000.000 – rp10.000.000 per month: 3
rp 3.000.000 – rp 4.200.000 per month: 3
rp 20,000,000 – rp 30,000,000 per month: 3
rp 9,000,000 – rp 13,000,000 per month: 3
rp 3.300.000 – rp 3.500.000 per month: 3
rp 3.900.000 – rp 4.200.000 per month: 3
rp 9.000.000 – rp 12.500.000 per month: 3
rp 11.000.000 – rp 13.000.000 per month: 2
rp 2.700.000 – rp 3.500.000 per month: 2
rp 5.067.381 – rp 6.500.000 per month: 2
rp 18,000,000 – rp 25,000,000 per month: 2
rp 3.600.000 – rp 4.500.000 per month: 2
rp 5.800.000 – rp 7.500.000 per month: 2
rp 40.000.000 – rp 60.000.000 per month: 2
rp 16.000.000 – rp 24.000.000 per month: 2
rp 16.000.000 – rp 19.000.000 per month: 2
rp 6.500.000 – rp 7.800.000 per month: 2
rp 5.200.000 – rp 7.000.000 per month: 2
rp 5,100,000 – rp 7,650,000 per month: 2
rp 4.800.000 – rp 7.200.000 per month: 2
rp 4,700,000 – rp 7,000,000 per month: 2
rp 15.000.000 per month: 2
rp 10.500.000 – rp 13.000.000 per month: 2
rp 3.300.000 – rp 4.500.000 per month: 2
rp 18.000.000 – rp 22.000.000 per month: 2
rp 5.070.000 – rp 6.740.000 per month: 2
rp 2.750.000 – rp 4.000.000 per month: 2
rp 3.650.000 – rp 5.000.000 per month: 2
rp 5.200.000 – rp 5.300.000 per month: 2
rp 9,400,000 – rp 14,000,000 per month: 2
rp 60.000.000 – rp 70.000.000 per month: 2
rp 6.500.000 – rp 7.200.000 per month: 2
rp 16.666.667 – rp 25.000.000 per month: 2
rp 4,300,000 – rp 5,000,000 per month: 2
rp 4,200,000 – rp 6,000,000 per month: 2
rp 3.500.000 – rp 3.800.000 per month: 2
rp 4.300.000 – rp 6.450.000 per month: 2
rp 3.500.000 – rp 4.250.000 per month: 2
rp 2.400.000 – rp 2.600.000 per month: 2
rp 13,000,000 – rp 16,000,000 per month: 2
rp 25.000.000 – rp 34.000.000 per month: 2
rp 3.700.000 – rp 4.000.000 per month: 2
rp 4,666,667 – rp 7,000,000 per month: 2
rp 9.000.000 – rp 10.500.000 per month: 2
rp 9,000,000 – rp 11,700,000 per month: 2
rp 5.258.000 – rp 6.000.000 per month: 2
rp 4.700.000 – rp 6.500.000 per month: 2
$2,000 – $3,000 per month: 2
rp 6.000.000 – rp 7.700.000 per month: 2
rp 7.000.000 – rp 9.800.000 per month: 2
rp 2.250.300 – rp 2.700.000 per month: 2
rp 3.300.000 – rp 3.600.000 per month: 2
rp 2,500,000 – rp 3,000,000 per month: 2
rp 3.400.000 – rp 4.000.000 per month: 2
rp 5.300.000 – rp 6.000.000 per month: 2
rp 15,000,000 – rp 22,500,000 per month: 2
rp2.000.000 – rp3.000.000 per month: 2
rp7.000.000 – rp9.000.000 per month: 2
rp 3.300.000 – rp 4.800.000 per month: 2
rp 2.900.000 – rp 4.000.000 per month: 2
rp 5.219.263 – rp 7.000.000 per month: 2
rp 4.750.000 – rp 5.000.000 per month: 2
rp 4.300.000 – rp 6.000.000 per month: 2
rp 4.500.000 – rp 4.900.000 per month: 2
rp 5.000.000 – rp 5.700.000 per month: 2
rp 3.000.000 – rp 3.700.000 per month: 2
rp 3.300.000 – rp 3.800.000 per month: 2
rp 12.000.000 – rp 13.000.000 per month: 2
rp 5.100.000 – rp 5.200.000 per month: 2
rp 5.100.000 – rp 6.800.000 per month: 2
rp 8.500.000 – rp 10.000.000 per month: 2
rp 2.400.000 – rp 3.000.000 per month: 2
rp 3.000.000 – rp 3.800.000 per month: 2
rp 5,100,000 – rp 7,500,000 per month: 2
rp 4,500,000 – rp 5,100,000 per month: 2
rp 4.000.000 – rp 5.600.000 per month: 2
rp 2.492.997 per month: 2
rp5.500.000 – rp6.500.000 per month: 2
rp 4.800.000 – rp 5.800.000 per month: 2
rp 4.900.000 – rp 5.000.000 per month: 2
rp 2.750.000 – rp 3.000.000 per month: 2
rp 5.800.000 – rp 7.000.000 per month: 2
rp 3.750.000 – rp 5.000.000 per month: 2
rp 4,600,000 – rp 5,000,000 per month: 2
rp 4.200.000 – rp 5.000.000 per month: 2
rp 7,000,000 – rp 8,500,000 per month: 2
rp 12.500.000 – rp 18.000.000 per month: 2
rp 20.000.000 – rp 23.000.000 per month: 2
rp 5.250.000 – rp 6.500.000 per month: 2
rp3.000.000 – rp4.000.000 per month: 2
rp 2.233.000 – rp 3.300.000 per month: 2
rp 5.067.381 – rp 5.200.000 per month: 2
9.000.000 - 12.000.000: 2
rp 4.500.000 – rp 4.725.500 per month: 2
rp 4.300.000 – rp 5.000.000 per month: 2
rp 11.000.000 – rp 16.500.000 per month: 2
60000000: 2
rp 4.000.000 – rp 4.300.000 per month: 2
rp5.000.000 – rp7.500.000 per month: 2
rp 3.350.000 – rp 5.000.000 per month: 2
rp 3,500,000 – rp 4,700,000 per month: 2
rp 12.500.000 – rp 17.500.000 per month: 2
rp 11.000.000 – rp 12.500.000 per month: 2
rp6.000.000 – rp8.000.000 per month: 2
rp 7,500,000 – rp 10,500,000 per month: 2
idr 4,500,000 - 6,300,000: 2
rp 8,500,000 – rp 12,500,000 per month: 2
rp 3.800.000 – rp 4.000.000 per month: 2
rp 4.500.000 – rp 5.100.000 per month: 2
rp 4.500.000 per month: 2
rp 5.300.000 – rp 6.500.000 per month: 2
rp 17,000,000 – rp 25,000,000 per month: 2
rp 1.800.000 – rp 2.500.000 per month: 2
rp 8.000.000 per month: 2
rp 3.800.000 – rp 5.700.000 per month: 2
rp 4.800.000 – rp 5.100.000 per month: 2
rp 6,500,000 – rp 9,100,000 per month: 2
rp 2.800.000 – rp 3.800.000 per month: 2
rp 4,500,000 – rp 6,750,000 per month: 2
rp 13.000.000 – rp 16.000.000 per month: 2
rp 3.200.000 – rp 3.500.000 per month: 2
rp 5.600.000 – rp 8.400.000 per month: 2
rp10.000.000 – rp15.000.000 per month: 2
rp4.500.000 – rp6.000.000 per month: 2
rp 14.000.000 – rp 19.000.000 per month: 2
rp 15,000,000 – rp 18,000,000 per month: 2
rp 5.067.381 – rp 7.000.000 per month: 2
rp 4.500.000 – rp 4.800.000 per month: 2
rp 7.850.000 – rp 8.000.000 per month: 2
rp 16,000,000 – rp 24,000,000 per month: 2
rp 5.068.000 – rp 6.000.000 per month: 2
rp 4,400,000 – rp 4,800,000 per month: 2
rp 3.000.000 – rp 4.300.000 per month: 2
rp 2.333.333 – rp 3.500.000 per month: 2
idr 6,000,000 - 7,000,000: 2
rp 2.500.000 – rp 2.550.000 per month: 2
rp 11.000.000 – rp 13.500.000 per month: 2
rp 2.700.000 – rp 3.300.000 per month: 2
rp 4.800.000 – rp 5.300.000 per month: 2
rp 13.000.000 – rp 19.500.000 per month: 2
rp 3.200.000 – rp 4.000.000 per month: 2
rp 13.250.000 – rp 14.050.000 per month: 2
rp 5.000.000 – rp 5.600.000 per month: 2
rp 5.250.000 – rp 7.000.000 per month: 2
idr 6,000,000 - 8,000,000: 2
rp 14,000,000 – rp 15,000,000 per month: 2
rp 25.000.000 – rp 28.000.000 per month: 2
rp 20,000,000 – rp 25,000,000 per month: 2
rp 3.900.000 – rp 4.000.000 per month: 2
rp 27.000.000 – rp 40.000.000 per month: 2
rp4.000.000 – rp6.000.000 per month: 2
rp 7.199.000 – rp 7.571.000 per month: 2
rp 7,500,000 – rp 8,500,000 per month: 2
rp 3.800.000 – rp 4.500.000 per month: 2
rp 3.750.000 – rp 4.000.000 per month: 2
rp 4.250.000 – rp 6.300.000 per month: 2
rp 4.800.000 – rp 6.500.000 per month: 2
rp 3.600.000 – rp 3.700.000 per month: 2
rp 14.000.000 – rp 15.000.000 per month: 2
rp 2.600.000 – rp 3.000.000 per month: 2
rp2.500.000 – rp3.500.000 per month: 2
rp 12,000,000 – rp 14,000,000 per month: 2
rp 4.900.000 – rp 5.300.000 per month: 2
rp 6.750.000 – rp 10.000.000 per month: 2
rp 3.250.000 – rp 4.000.000 per month: 2
rp 3.500.000 – rp 5.100.000 per month: 2
rp 4.500.000 – rp 6.700.000 per month: 2
rp 35,000,000 – rp 50,000,000 per month: 2
rp 4.300.000 – rp 4.500.000 per month: 2
rp 40,000,000 – rp 60,000,000 per month: 2
rp 23.500.000 – rp 26.500.000 per month: 2
rp 4.500.000 – rp 4.700.000 per month: 2
rp 5.700.000 – rp 6.500.000 per month: 2
idr 4,500,000 - 5,000,000: 2
rp 3.333.333 – rp 5.000.000 per month: 2
rp 7.000.000 – rp 10.000.005 per month: 2
rp 2.600.000 – rp 3.900.000 per month: 2
rp 4.800.000 – rp 5.000.000 per month: 2
idr 3,000,000 - 4,200,000: 2
rp 30,000,000 – rp 45,000,000 per month: 2
rp 4.650.000 – rp 4.800.000 per month: 1
rp 2,000,000 – rp 2,500,000 per month: 1
rp 2,000,000 – rp 2,700,000 per month: 1
rp 2,850,000 – rp 3,750,000 per month: 1
rp 3.000.000 – rp 3.475.595 per month: 1
rp 5.067.000 – rp 6.500.000 per month: 1
rp 24.000.000 – rp 28.000.000 per month: 1
rp 5.065.000 per month: 1
rp 3.452.000 per month: 1
rp 5.400.000 – rp 6.800.000 per month: 1
rp 4.580.000 – rp 5.500.000 per month: 1
rp 5,500,000 – rp 8,100,000 per month: 1
rp5.500.000 – rp6.000.000 per month: 1
rp 2.250.000 – rp 3.350.000 per month: 1
rp3.000.000 per month: 1
idr 3,400,000 - 3,500,000: 1
rp 2,750,000 – rp 4,100,000 per month: 1
rp 4,800,000 – rp 7,000,000 per month: 1
rp 3.250.000 – rp 3.500.000 per month: 1
rp4.830.000 – rp6.759.000 per month: 1
rp 5.300.000 – rp 5.700.000 per month: 1
rp 2,200,000 – rp 2,700,000 per month: 1
rp 4.200.000 – rp 5.100.000 per month: 1
rp 4.650.000 per month: 1
rp 33.333.333 – rp 50.000.000 per month: 1
rp 28.000.000 – rp 35.000.000 per month: 1
rp 5.000.000 – rp 5.750.000 per month: 1
rp 8.500.000 – rp 11.000.000 per month: 1
rp 5.500.000 – rp 5.800.000 per month: 1
idr 3,700,000 - 4,900,000: 1
rp 4,300,000 – rp 4,725,479 per month: 1
rp 4.050.000 – rp 5.500.000 per month: 1
rp 3,250,000 – rp 4,500,000 per month: 1
rp 11.000.000 – rp 12.000.000 per month: 1
rp 3.250.000 – rp 4.500.000 per month: 1
rp 4.670.000 – rp 4.793.000 per month: 1
rp 3.243.969 – rp 4.000.000 per month: 1
rp 6.000.008 – rp 9.000.000 per month: 1
rp 3.318.628 – rp 4.000.000 per month: 1
rp 15,000,000 – rp 17,000,000 per month: 1
rp1.900.000 – rp2.300.000 per month: 1
rp20.000.000 – rp30.000.000 per month: 1
rp 500.000 – rp 750.000 per month: 1
rp 2.500.000 – rp 3.300.000 per month: 1
rp 5.750.000 – rp 8.000.000 per month: 1
rp 65,000,000 – rp 95,000,000 per month: 1
rp 4,642,031 per month: 1
rp 5.000.000 – rp 5.070.000 per month: 1

In [98]:
#menyaring baris yang mengandung tanda $, 'my', 'per year', 'per hour', 'myr' , 'rm' atau 'million'
filtered_data = df[df['salary'].str.contains(r'\$|my|per year|per hour|myr|rm|million', case=False, na=False)]
for index, row in filtered_data.iterrows():
    print(f"Index: {index}, Salary: {row['salary']}")

Index: 52, Salary: myr 3900 - myr 4900
Index: 399, Salary: rp 250.000.000 – rp 350.000.000 per year
Index: 431, Salary: $50,000 – $75,000 per month
Index: 489, Salary: rp 8.000.000 – rp 9.000.000 per year
Index: 503, Salary: rp 200.000 – rp 300.000 per hour
Index: 729, Salary: rp 216.000.000 – rp 324.000.000 per year
Index: 873, Salary: rp 5.500.000 – rp 7.500.000 per year
Index: 896, Salary: $70,000 – $100,000 per month
Index: 974, Salary: rp 30.000 per hour
Index: 1101, Salary: $1,700 – $2,500 per month
Index: 1171, Salary: $70,000 – $100,000 per month
Index: 1186, Salary: $3,000 – $4,000 per month
Index: 1255, Salary: rp 3.100.000 – rp 4.650.000 per year
Index: 1263, Salary: rp500.000.000 – rp750.000.000 per year
Index: 1283, Salary: rp 4.000.000 – rp 6.000.000 per year
Index: 1557, Salary: rp 2,500,000 – rp 3,500,000 per hour
Index: 1730, Salary: rp 100.000 – rp 150.000 per hour
Index: 1745, Salary: rp 15.000.000 – rp 20.000.000 per year
Index: 1827, Salary: rp 100.000 per year
Index: 1969, Salary: rp 100.000 – rp 150.000 per hour
Index: 2079, Salary: $500 – $600 per month
Index: 2178, Salary: rp 100.000 – rp 150.000 per hour
Index: 2283, Salary: rp 3,500,000 – rp 5,000,000 per hour
Index: 2374, Salary: shift allowance, performance bonus
Index: 2492, Salary: rp 5.000.000 – rp 7.500.000 per year
Index: 2560, Salary: $1.400 – $2.099 per month
Index: 2588, Salary: $2,000 – $3,000 per month
Index: 2843, Salary: rp 6.000.000 – rp 9.000.000 per year
Index: 2905, Salary: $800 – $1,200 per month
Index: 2973, Salary: $4.500 – $5.000 per month
Index: 3006, Salary: $500 – $750 per month
Index: 3161, Salary: $70,000 – $100,000 per month
Index: 3333, Salary: 5 - 7 million
Index: 3588, Salary: 30 - 35 net million rupiahs per month
Index: 3616, Salary: rp 20.000 – rp 30.000 per hour
Index: 3963, Salary: $550 – $800 per month
Index: 4200, Salary: rp 5.000.000 – rp 6.000.000 per hour
Index: 4360, Salary: rm 30,000 – rm 45,000 per month
Index: 4411, Salary: rp 60.000.000 – rp 80.000.000 per year
Index: 5023, Salary: rp 4.500.000 – rp 6.750.000 per year
Index: 5047, Salary: $2,000 – $3,000 per month
Index: 5219, Salary: $600 – $900 per month
Index: 6084, Salary: $3.000 – $3.500 per month

In [99]:
filtered_data.shape

(43, 16)

In [100]:
# Menyaring baris yang mengandung tanda $, 'my', 'per year', 'per hour', 'myr', 'rm', atau 'million' dan menghapusnya
df = df[~df['salary'].str.contains(r'\$|my|per year|per hour|myr|rm|million', case=False, na=False)]

In [101]:
for index, row in df.iterrows():
    print(f"Index: {index}, Salary: {row['salary']}")

Index: 0, Salary: rp 8.500.000 – rp 12.500.000 per month
Index: 1, Salary: rp 10.000.000 – rp 14.000.000 per month
Index: 3, Salary: rp 6.000.000 – rp 9.000.000 per month
Index: 4, Salary: rp 4.500.000 – rp 5.500.000 per month
Index: 5, Salary: rp 8.000.000 – rp 8.100.000 per month
Index: 6, Salary: rp 4.500.000 – rp 6.500.000 per month
Index: 7, Salary: rp 6.000.000 – rp 8.000.000 per month
Index: 8, Salary: rp 3.500.000 – rp 4.200.000 per month
Index: 9, Salary: rp 4.500.000 – rp 6.500.000 per month
Index: 10, Salary: rp 7.500.000 – rp 11.000.000 per month
Index: 11, Salary: rp 3.800.000 – rp 4.602.000 per month
Index: 12, Salary: rp 5.000.000 – rp 7.000.000 per month
Index: 13, Salary: rp 3.000.000 – rp 3.096.823 per month
Index: 14, Salary: rp 3.500.000 – rp 4.500.000 per month
Index: 15, Salary: rp 11.500.000 – rp 15.000.000 per month
Index: 16, Salary: rp 23.500.000 – rp 26.500.000 per month
Index: 17, Salary: rp 5.500.000 – rp 6.500.000 per month
Index: 18, Salary: rp 5,000,000 – rp 5,500,000 per month
Index: 19, Salary: rp 7.000.000 – rp 8.000.000 per month
Index: 20, Salary: rp 5.000.000 – rp 7.000.000 per month
Index: 21, Salary: rp 4.500.000 – rp 6.750.000 per month
Index: 22, Salary: rp 5.200.000 – rp 5.500.000 per month
Index: 23, Salary: rp 5,500,000 – rp 6,200,000 per month
Index: 24, Salary: rp 2,000,000 – rp 3,000,000 per month
Index: 25, Salary: rp 3.500.000 – rp 4.500.000 per month
Index: 26, Salary: rp 6,500,000 – rp 7,000,000 per month
Index: 27, Salary: rp 7.500.000 – rp 11.000.000 per month
Index: 28, Salary: rp 4.500.000 – rp 5.000.000 per month
Index: 29, Salary: rp 4.500.000 – rp 6.500.000 per month
Index: 30, Salary: rp 20.000.000 – rp 25.000.000 per month
Index: 31, Salary: rp 5.000.000 – rp 6.000.000 per month
Index: 32, Salary: rp 3.500.000 – rp 4.000.000 per month
Index: 33, Salary: rp 6.500.000 – rp 8.000.000 per month
Index: 34, Salary: rp 10.000.000 – rp 15.000.000 per month
Index: 35, Salary: rp 2.200.000 – rp 2.500.000 per month
Index: 36, Salary: rp 4.500.000 – rp 4.700.000 per month
Index: 37, Salary: rp 7.500.000 – rp 11.000.000 per month
Index: 38, Salary: rp 4.700.000 – rp 7.000.000 per month
Index: 39, Salary: rp 18.000.000 – rp 25.000.000 per month
Index: 40, Salary: rp 3.500.000 – rp 5.000.000 per month
Index: 41, Salary: rp 5.000.000 per month
Index: 42, Salary: rp 6.000.000 – rp 8.000.000 per month
Index: 43, Salary: rp 7.000.000 – rp 9.000.000 per month
Index: 44, Salary: rp 5.700.000 – rp 6.500.000 per month
Index: 45, Salary: rp 6,000,000 – rp 8,500,000 per month
Index: 46, Salary: rp 10.000.000 – rp 15.000.000 per month
Index: 47, Salary: rp 12.000.000 – rp 18.000.000 per month
Index: 48, Salary: rp 2.600.000 – rp 3.900.000 per month
Index: 49, Salary: rp 4.700.000 – rp 6.000.000 per month
Index: 50, Salary: rp 4.600.000 – rp 5.750.000 per month
Index: 51, Salary: rp 6.000.000 – rp 7.000.000 per month
Index: 53, Salary: rp 4.000.000 – rp 5.000.000 per month
Index: 54, Salary: rp 4,000,000 – rp 5,000,000 per month
Index: 55, Salary: rp 30,000,000 – rp 45,000,000 per month
Index: 56, Salary: rp 5.000.000 – rp 6.000.000 per month
Index: 57, Salary: rp 5.400.000 – rp 8.000.000 per month
Index: 58, Salary: rp 8,000,000 – rp 10,000,000 per month
Index: 59, Salary: rp 5.250.000 – rp 7.000.000 per month
Index: 60, Salary: rp 4.120.000 – rp 5.500.000 per month
Index: 61, Salary: rp 8,000,000 – rp 10,000,000 per month
Index: 62, Salary: rp 14,000,000 – rp 19,000,000 per month
Index: 63, Salary: rp 3.200.000 – rp 4.000.000 per month
Index: 64, Salary: rp 7,000,000 – rp 9,000,000 per month
Index: 65, Salary: rp 8.000.000 – rp 9.000.000 per month
Index: 66, Salary: rp 5.500.000 – rp 6.000.000 per month
Index: 67, Salary: rp 18.000.000 – rp 25.000.000 per month
Index: 68, Salary: rp 3.500.000 – rp 4.500.000 per month
Index: 69, Salary: rp 5.400.000 – rp 8.000.000 per month
Index: 70, Salary: rp 9,000,000 – rp 12,000,000 per month
Index: 71, Salary: rp 4.500.000 – rp 6.500.000 per month
Index: 72, Salary: rp 8.000.000 – rp 11.000.000 per month
Index: 73, Salary: idr 5,000,000 - 6,000,000
Index: 74, Salary: rp 3.400.000 – rp 5.000.000 per month
Index: 75, Salary: rp 5.000.000 – rp 7.000.000 per month
Index: 76, Salary: rp 4.800.000 – rp 5.500.000 per month
Index: 77, Salary: rp 20.000.000 – rp 30.000.000 per month
Index: 78, Salary: rp 6.000.000 – rp 7.000.000 per month
Index: 79, Salary: rp 6.500.000 – rp 7.500.000 per month
Index: 80, Salary: rp 17,000,000 – rp 19,000,000 per month
Index: 81, Salary: rp 8,000,000 – rp 12,000,000 per month
Index: 82, Salary: rp 16.000.000 – rp 20.000.000 per month
Index: 83, Salary: rp 2.500.000 – rp 3.000.000 per month
Index: 84, Salary: rp 13.000.000 – rp 19.500.000 per month
Index: 85, Salary: rp 5.000.000 – rp 7.000.000 per month
Index: 86, Salary: rp 5,100,000 – rp 5,300,000 per month
Index: 87, Salary: rp 6.000.000 – rp 7.000.000 per month
Index: 88, Salary: rp 3.500.000 – rp 5.250.000 per month
Index: 89, Salary: rp 4,000,000 – rp 6,000,000 per month
Index: 90, Salary: rp 6.000.000 – rp 7.000.000 per month
Index: 91, Salary: rp 10,000,000 – rp 14,000,000 per month
Index: 92, Salary: rp 6.500.000 – rp 9.000.000 per month
Index: 93, Salary: rp 4.100.000 – rp 4.600.000 per month
Index: 94, Salary: rp 3.000.000 – rp 4.500.000 per month
Index: 95, Salary: rp 2.350.000 – rp 2.500.000 per month
Index: 96, Salary: rp 12.000.000 – rp 18.000.000 per month
Index: 97, Salary: rp 8.000.000 – rp 12.000.000 per month
Index: 98, Salary: rp 4.000.000 – rp 6.000.000 per month
Index: 99, Salary: rp 5.000.000 – rp 7.000.000 per month
Index: 100, Salary: rp 3.000.000 – rp 4.000.000 per month
Index: 101, Salary: rp 9.000.000 – rp 13.000.000 per month
Index: 102, Salary: rp 3,500,000 – rp 4,300,000 per month
Index: 103, Salary: rp 12.000.000 – rp 18.000.000 per month
Index: 104, Salary: rp 6.000.000 – rp 9.000.000 per month
Index: 105, Salary: rp 6.000.000 – rp 7.000.000 per month
Index: 106, Salary: rp 2.000.000 – rp 2.500.000 per month
Index: 107, Salary: rp 2.492.000 – rp 3.500.000 per month
Index: 108, Salary: rp 11,000,000 – rp 15,000,000 per month
Index: 109, Salary: rp 10.000.000 – rp 15.000.000 per month
Index: 110, Salary: rp 3.500.000 – rp 4.000.000 per month
Index: 111, Salary: rp 7.000.000 – rp 10.000.000 per month
Index: 112, Salary: rp 5.000.000 – rp 7.000.000 per month
Index: 113, Salary: rp 5.000.000 – rp 7.000.000 per month
Index: 114, Salary: rp 19.000.000 – rp 24.000.000 per month
Index: 115, Salary: rp 5.500.000 – rp 7.500.000 per month
Index: 116, Salary: rp 6.000.000 – rp 7.500.000 per month
Index: 117, Salary: rp 50,000,000 – rp 60,000,000 per month
Index: 118, Salary: rp 10.000.000 – rp 15.000.000 per month
Index: 119, Salary: rp 5.100.000 – rp 7.600.000 per month
Index: 120, Salary: rp 6.200.000 – rp 8.500.000 per month
Index: 121, Salary: rp 3.000.000 – rp 4.300.000 per month
Index: 122, Salary: rp 6.000.000 – rp 9.000.000 per month
Index: 123, Salary: rp 3.000.000 – rp 4.000.000 per month
Index: 124, Salary: rp 20,000,000 – rp 30,000,000 per month
Index: 125, Salary: rp 3.500.000 – rp 5.000.000 per month
Index: 126, Salary: rp 3.500.000 – rp 5.000.000 per month
Index: 127, Salary: rp 4,400,000 – rp 4,800,000 per month
Index: 128, Salary: rp 16,000,000 – rp 24,000,000 per month
Index: 129, Salary: rp 4.000.000 – rp 4.500.000 per month
Index: 130, Salary: rp 4.500.000 – rp 5.500.000 per month
Index: 131, Salary: rp5.000.000 – rp7.000.000 per month
Index: 132, Salary: rp 3.500.000 – rp 4.000.000 per month
Index: 133, Salary: rp 5.500.000 – rp 8.000.000 per month
Index: 134, Salary: rp 3.500.000 – rp 4.500.000 per month
Index: 135, Salary: rp 8,000,000 – rp 12,000,000 per month
Index: 136, Salary: rp 5.510.000 – rp 8.110.000 per month
Index: 137, Salary: rp 4.000.000 – rp 6.000.000 per month
Index: 138, Salary: rp 10.000.000 – rp 13.000.000 per month
Index: 139, Salary: rp 10.000.000 – rp 15.000.000 per month
Index: 140, Salary: rp 3,000,000 – rp 4,200,000 per month
Index: 141, Salary: rp 3.310.000 – rp 3.500.000 per month
Index: 142, Salary: rp 6.500.000 – rp 8.000.000 per month
Index: 143, Salary: rp 9.000.000 – rp 12.000.000 per month
Index: 144, Salary: rp 6,350,000 – rp 8,275,000 per month
Index: 145, Salary: rp 25.000.000 – rp 35.000.000 per month
Index: 146, Salary: rp 7.000.000 – rp 8.500.000 per month
Index: 147, Salary: rp 18.000.000 – rp 25.000.000 per month
Index: 148, Salary: rp 8.000.000 – rp 12.000.000 per month
Index: 149, Salary: rp 3.500.000 – rp 4.700.000 per month
Index: 150, Salary: rp 6.000.000 – rp 8.500.000 per month
Index: 151, Salary: rp 7.000.000 – rp 9.000.000 per month
Index: 152, Salary: rp 6,000,000 – rp 8,000,000 per month
Index: 153, Salary: rp 3.000.000 – rp 4.500.000 per month
Index: 154, Salary: rp 3.000.000 – rp 3.500.000 per month
Index: 155, Salary: rp 35.000.000 – rp 40.000.000 per month
Index: 156, Salary: rp 15.000.000 – rp 20.000.000 per month
Index: 157, Salary: rp 4.500.000 – rp 5.500.000 per month
Index: 158, Salary: rp 10.000.000 – rp 12.000.000 per month
Index: 159, Salary: rp 3.500.000 – rp 4.000.000 per month
Index: 160, Salary: rp 18.000.000 – rp 23.000.000 per month
Index: 161, Salary: rp 5.000.000 – rp 6.000.000 per month
Index: 162, Salary: rp 5.000.000 – rp 6.000.000 per month
Index: 163, Salary: rp 3,500,000 – rp 4,500,000 per month
Index: 164, Salary: rp 4.000.000 – rp 5.000.000 per month
Index: 165, Salary: rp 5.000.000 – rp 6.500.000 per month
Index: 166, Salary: rp 10.000.000 – rp 15.000.000 per month
Index: 167, Salary: rp 4.500.000 – rp 5.500.000 per month
Index: 168, Salary: rp 10.000.000 – rp 15.000.000 per month
Index: 169, Salary: rp 15,000,000 – rp 18,000,000 per month
Index: 170, Salary: rp 7.000.000 – rp 10.500.000 per month
Index: 171, Salary: rp 6.500.000 – rp 8.000.000 per month
Index: 172, Salary: rp 3.500.000 – rp 5.000.000 per month
Index: 173, Salary: rp 3.103.631 per month
Index: 174, Salary: rp 15.000.000 – rp 17.000.000 per month
Index: 175, Salary: idr 8,000,000 - 10,000,000
Index: 176, Salary: rp 3.000.000 – rp 4.000.000 per month
Index: 177, Salary: rp 3.350.000 – rp 4.500.000 per month
Index: 178, Salary: rp 3.475.595 – rp 4.000.000 per month
Index: 179, Salary: rp 3.000.000 – rp 4.000.000 per month
Index: 180, Salary: rp 5.500.000 – rp 6.500.000 per month
Index: 181, Salary: rp 4.700.000 – rp 5.000.000 per month
Index: 182, Salary: rp 4.000.000 – rp 5.500.000 per month
Index: 183, Salary: rp 5.000.000 – rp 7.500.000 per month
Index: 184, Salary: rp7.000.000 – rp10.000.000 per month
Index: 185, Salary: rp 5.500.000 – rp 7.500.000 per month
Index: 186, Salary: rp 7.000.000 – rp 10.000.000 per month
Index: 187, Salary: rp 15.000.000 – rp 20.000.000 per month
Index: 188, Salary: rp 7.000.000 – rp 10.000.000 per month
Index: 189, Salary: rp 7,000,000 – rp 10,000,000 per month
Index: 190, Salary: rp 9.000.000 – rp 11.500.000 per month
Index: 191, Salary: rp 6.000.000 – rp 8.000.000 per month
Index: 192, Salary: rp 5,500,000 – rp 6,500,000 per month
Index: 193, Salary: rp 6.700.000 – rp 10.000.000 per month
Index: 194, Salary: rp 10.000.000 – rp 15.000.000 per month
Index: 195, Salary: rp 5,500,000 – rp 6,500,000 per month
Index: 196, Salary: rp 4.000.000 – rp 6.000.000 per month
Index: 197, Salary: rp 3.000.000 – rp 4.500.000 per month
Index: 198, Salary: rp 4,000,000 – rp 5,600,000 per month
Index: 199, Salary: rp 4.000.000 – rp 5.000.000 per month
Index: 200, Salary: rp 6.000.000 – rp 9.000.000 per month
Index: 201, Salary: rp 5.400.000 – rp 8.000.000 per month
Index: 202, Salary: rp 3.000.000 per month
Index: 203, Salary: rp 9.000.000 – rp 12.000.000 per month
Index: 204, Salary: rp 5,100,000 – rp 6,700,000 per month
Index: 205, Salary: rp 14.000.000 – rp 16.000.000 per month
Index: 206, Salary: rp 7,000,000 – rp 10,000,000 per month
Index: 207, Salary: rp 4.500.000 – rp 5.500.000 per month
Index: 208, Salary: rp 10,000,000 – rp 13,000,000 per month
Index: 209, Salary: rp 12.000.000 – rp 14.000.000 per month
Index: 210, Salary: rp 10.000.000 – rp 11.000.000 per month
Index: 211, Salary: rp 5.000.000 – rp 7.000.000 per month
Index: 212, Salary: rp 4.000.000 – rp 6.000.000 per month
Index: 213, Salary: rp4.500.000 – rp6.000.000 per month
Index: 214, Salary: idr 4,000,000 - 5,600,000
Index: 215, Salary: rp 10.000.000 – rp 12.000.000 per month
Index: 216, Salary: rp 6.000.000 – rp 8.500.000 per month
Index: 217, Salary: rp 8.000.000 – rp 10.000.000 per month
Index: 218, Salary: rp 2.600.000 – rp 3.200.000 per month
Index: 219, Salary: rp 6.000.000 – rp 7.000.000 per month
Index: 220, Salary: rp 8.000.000 – rp 12.000.000 per month
Index: 221, Salary: rp10.000.000 – rp15.000.000 per month
Index: 222, Salary: rp 13.250.000 – rp 14.050.000 per month
Index: 223, Salary: rp 8.000.000 – rp 10.000.000 per month
Index: 224, Salary: rp 15.000.000 – rp 20.000.000 per month
Index: 225, Salary: rp 13,000,000 – rp 19,000,000 per month
Index: 226, Salary: rp 5,000,000 – rp 7,000,000 per month
Index: 227, Salary: rp 15.000.000 – rp 20.000.000 per month
Index: 228, Salary: rp 4.500.000 – rp 5.000.000 per month
Index: 229, Salary: rp 5.000.000 – rp 7.500.000 per month
Index: 230, Salary: rp 15.000.000 – rp 18.000.000 per month
Index: 231, Salary: rp 6.000.000 – rp 8.000.000 per month
Index: 232, Salary: rp 20,000,000 – rp 28,000,000 per month
Index: 233, Salary: rp 5.000.000 – rp 7.000.000 per month
Index: 234, Salary: rp 4.000.000 – rp 6.000.000 per month
Index: 235, Salary: rp 7.500.000 – rp 10.000.000 per month
Index: 236, Salary: rp 10,000,000 – rp 13,000,000 per month
Index: 237, Salary: idr 6,000,000 - 9,000,000
Index: 238, Salary: rp 7.000.000 – rp 9.000.000 per month
Index: 239, Salary: rp 6.000.000 – rp 8.000.000 per month
Index: 240, Salary: rp 4.500.000 – rp 5.500.000 per month
Index: 241, Salary: rp 4.500.000 – rp 5.000.000 per month
Index: 242, Salary: rp 2.550.000 – rp 3.800.000 per month
Index: 243, Salary: rp 8.000.000 – rp 12.000.000 per month
Index: 244, Salary: rp 5.500.000 – rp 7.000.000 per month
Index: 245, Salary: rp 5.000.000 – rp 7.000.000 per month
Index: 246, Salary: rp 5.400.000 – rp 8.000.000 per month
Index: 247, Salary: rp 7.500.000 – rp 9.500.000 per month
Index: 248, Salary: rp 7.000.000 – rp 10.500.000 per month
Index: 249, Salary: rp 2.500.000 – rp 3.000.000 per month
Index: 250, Salary: rp 5.000.000 – rp 7.000.000 per month
Index: 251, Salary: rp 3.700.000 – rp 4.100.000 per month
Index: 252, Salary: rp 12,000,000 – rp 14,000,000 per month
Index: 253, Salary: rp 8.500.000 – rp 12.000.000 per month
Index: 254, Salary: rp 8.000.000 – rp 12.000.000 per month
Index: 255, Salary: rp 3.000.000 – rp 4.000.000 per month
Index: 256, Salary: rp 5.000.000 – rp 5.067.381 per month
Index: 257, Salary: rp 5.000.000 – rp 7.000.000 per month
Index: 258, Salary: rp 9.450.000 – rp 11.700.000 per month
Index: 259, Salary: rp 8.000.000 – rp 12.000.000 per month
Index: 260, Salary: rp 5.000.000 – rp 7.500.000 per month
Index: 261, Salary: rp 5.000.000 – rp 5.500.000 per month
Index: 262, Salary: rp 20.000.000 – rp 28.000.000 per month
Index: 263, Salary: rp 7.000.000 – rp 8.000.000 per month
Index: 264, Salary: rp 7.000.000 – rp 9.000.000 per month
Index: 265, Salary: rp 5.500.000 – rp 8.000.000 per month
Index: 266, Salary: rp 4.000.000 – rp 6.000.000 per month
Index: 267, Salary: rp 15.000.000 – rp 22.000.000 per month
Index: 268, Salary: rp 6.700.000 – rp 10.000.000 per month
Index: 269, Salary: rp 5.000.000 – rp 7.000.000 per month
Index: 270, Salary: rp 7.500.000 – rp 8.500.000 per month
Index: 271, Salary: rp 12.000.000 – rp 18.000.000 per month
Index: 272, Salary: rp 5,000,000 – rp 6,500,000 per month
Index: 273, Salary: rp 2.800.000 – rp 4.200.000 per month
Index: 274, Salary: rp 10.000.000 – rp 12.000.000 per month
Index: 275, Salary: rp 4.000.000 – rp 6.000.000 per month
Index: 276, Salary: rp 3.500.000 – rp 5.000.000 per month
Index: 277, Salary: rp 5.500.000 – rp 8.250.000 per month
Index: 278, Salary: rp 6,000,000 – rp 9,000,000 per month
Index: 279, Salary: rp2.500.000 – rp3.500.000 per month
Index: 280, Salary: rp 4.000.000 – rp 6.000.000 per month
Index: 281, Salary: rp 5.000.000 – rp 6.000.000 per month
Index: 282, Salary: rp 13.000.000 – rp 18.000.000 per month
Index: 283, Salary: rp 3.500.000 – rp 4.000.000 per month
Index: 284, Salary: rp 7.000.000 – rp 9.000.000 per month
Index: 285, Salary: rp 5.000.000 – rp 7.500.000 per month
Index: 286, Salary: rp 13.000.000 – rp 18.000.000 per month
Index: 287, Salary: rp 7.000.000 – rp 9.000.000 per month
Index: 288, Salary: rp 5.000.000 – rp 6.200.000 per month
Index: 289, Salary: rp 3.500.000 – rp 4.900.000 per month
Index: 290, Salary: idr 3,900,000 - 5,400,000
Index: 291, Salary: rp 13.000.000 – rp 17.000.000 per month
Index: 292, Salary: rp 4.000.000 – rp 6.000.000 per month
Index: 293, Salary: rp 9.000.000 – rp 13.500.000 per month
Index: 294, Salary: rp 13.000.000 – rp 17.000.000 per month
Index: 295, Salary: rp 6.500.000 – rp 9.000.000 per month
Index: 296, Salary: rp 6,000,000 – rp 8,000,000 per month
Index: 297, Salary: rp 2,000,000 – rp 3,000,000 per month
Index: 298, Salary: rp 3.500.000 – rp 5.200.000 per month
Index: 299, Salary: rp 7,000,000 – rp 8,000,000 per month
Index: 300, Salary: rp 5.500.000 – rp 6.500.000 per month
Index: 301, Salary: rp 5.000.000 – rp 7.000.000 per month
Index: 302, Salary: rp 6.000.000 – rp 7.500.000 per month
Index: 303, Salary: rp 4,000,000 – rp 4,500,000 per month
Index: 304, Salary: rp 5.500.000 – rp 6.000.000 per month
Index: 305, Salary: rp 12.000.000 – rp 18.000.000 per month
Index: 306, Salary: rp 15.000.000 – rp 22.000.000 per month
Index: 307, Salary: rp 7.000.000 – rp 8.000.000 per month
Index: 308, Salary: rp 25,000,000 – rp 28,000,000 per month
Index: 309, Salary: rp 4.000.000 – rp 5.000.000 per month
Index: 310, Salary: rp2.700.000 – rp4.000.000 per month
Index: 311, Salary: rp 4,000,000 – rp 5,500,000 per month
Index: 312, Salary: rp 6.000.000 – rp 8.000.000 per month
Index: 313, Salary: rp 6.000.000 – rp 9.000.000 per month
Index: 314, Salary: rp 12.500.000 – rp 18.500.000 per month
Index: 315, Salary: rp 15.000.000 – rp 20.000.000 per month
Index: 316, Salary: rp 4.000.000 – rp 5.000.000 per month
Index: 317, Salary: rp 10.000.000 – rp 15.000.000 per month
Index: 318, Salary: rp 4.000.000 – rp 4.500.000 per month
Index: 319, Salary: rp 8.000.000 – rp 10.000.000 per month
Index: 320, Salary: rp 4.000.000 – rp 6.000.000 per month
Index: 321, Salary: rp 5.000.000 – rp 7.500.000 per month
Index: 322, Salary: rp 10.000.000 – rp 15.000.000 per month
Index: 323, Salary: rp 7.000.000 – rp 9.000.000 per month
Index: 324, Salary: rp 4.000.000 – rp 6.000.000 per month
Index: 325, Salary: rp 8.000.000 – rp 10.000.000 per month
Index: 326, Salary: rp 5.500.000 – rp 6.500.000 per month
Index: 327, Salary: rp 10.000.000 – rp 15.000.000 per month
Index: 328, Salary: rp 5.000.000 – rp 6.500.000 per month
Index: 329, Salary: rp 9.000.000 – rp 12.000.000 per month
Index: 330, Salary: rp 7.000.000 – rp 10.000.000 per month
Index: 331, Salary: rp 5,000,000 – rp 7,000,000 per month
Index: 332, Salary: rp 3.300.000 – rp 4.950.000 per month
Index: 333, Salary: rp 12.000.000 – rp 18.000.000 per month
Index: 334, Salary: rp 13.333.333 – rp 20.000.000 per month
Index: 335, Salary: rp 4.000.000 – rp 6.000.000 per month
Index: 336, Salary: rp 7.500.000 – rp 10.000.000 per month
Index: 337, Salary: rp 2.250.300 – rp 3.000.000 per month
Index: 338, Salary: rp 5.000.000 – rp 6.000.000 per month
Index: 339, Salary: rp 5.000.000 – rp 6.600.000 per month
Index: 340, Salary: rp 5.500.000 – rp 8.000.000 per month
Index: 341, Salary: rp 10,000,000 – rp 12,000,000 per month
Index: 342, Salary: rp 8.000.000 – rp 12.000.000 per month
Index: 343, Salary: rp 4.000.000 – rp 6.000.000 per month
Index: 344, Salary: rp 3.000.000 – rp 4.000.000 per month
Index: 345, Salary: rp 20.000.000 – rp 30.000.000 per month
Index: 346, Salary: rp 8.000.000 – rp 12.000.000 per month

In [102]:
#menyaring baris yang mengandung tanda $, 'my', 'per year', 'per hour', 'myr' , 'rm' atau 'million'
filtered_data = df[df['salary'].str.contains(r'\$|my|per year|per hour|myr|rm|million', case=False, na=False)]
for index, row in filtered_data.iterrows():
    print(f"Index: {index}, Salary: {row['salary']}")

In [103]:
filtered_data.shape

(0, 16)

In [104]:
df.shape

(6085, 16)

In [112]:
df['salary'] = df['salary'].str.replace('–', '-', regex=False)
df[['salary_min', 'salary_max']] = df['salary'].str.split('-', expand=True)

C:\Users\USER\AppData\Local\Temp\ipykernel_24436\1695992776.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['salary'] = df['salary'].str.replace('–', '-', regex=False)
C:\Users\USER\AppData\Local\Temp\ipykernel_24436\1695992776.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[['salary_min', 'salary_max']] = df['salary'].str.split('-', expand=True)

In [113]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6085 entries, 0 to 6130
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   title                   6085 non-null   object
 1   role                    6085 non-null   object
 2   company_name            6085 non-null   object
 3   category                6085 non-null   object
 4   location                6085 non-null   object
 5   jobId                   6085 non-null   int64
 6   type                    6085 non-null   object
 7   salary                  6085 non-null   object
 8   url                     6085 non-null   object
 9   description             6083 non-null   object
 10  title_translated        6085 non-null   object
 11  description_translated  6085 non-null   object
 12  category_translated     6085 non-null   object
 13  role_translated         6085 non-null   object
 14  category_1              6085 non-null   object
 15  category_2              6085 non-null   object
 16  salary_min              6085 non-null   object
 17  salary_max              6002 non-null   object
dtypes: int64(1), object(17)
memory usage: 903.2+ KB

In [114]:
df.head(30)

,title,role,company_name,category,location,jobId,type,salary,url,description,title_translated,description_translated,category_translated,role_translated,category_1,category_2,salary_min,salary_max
0,penerjemah bahasa mandarinasisten manajer umum,mandarin translator,onemate aksesoris mobil,"administrasi dan dukungan perkantoran, asisten...",banten,79976110,full time,rp 8.500.000 - rp 12.500.000 per month,https:atauatauid.jobstreet.comataujobatau79976110,asisten manajer umum: • membantu manajer umum ...,penerjemah bahasa mandarin，asisten manajer umum,asisten manajer umum: • membantu manajer umum ...,"administrasi dan dukungan perkantoran, asisten...",mandarin-translator,administrasi dan dukungan perkantoran,asisten administratif,rp 8.500.000,rp 12.500.000 per month
1,it business analyst,information technology business analyst,nextalent talenta nusantara,"teknologi informasi dan komunikasi, analis bis...",jakarta raya,80187093,full time,rp 10.000.000 - rp 14.000.000 per month,https:atauatauid.jobstreet.comataujobatau80187093,qualification : candidate must possess at leas...,analis bisnis ti,error: [errno 11001] getaddrinfo failed,"teknolog informasi dan komununasi, anis bisnis...",informasi-teknologi-business-analyst,teknologi informasi dan komunikasi,analis bisnisatausistem,rp 10.000.000,rp 14.000.000 per month
3,sales executive,sales executive,laxmi utama,"ritel dan produk konsumen, asisten ritel",jawa timur,79645321,full time,rp 6.000.000 - rp 9.000.000 per month,https:atauatauid.jobstreet.comataujobatau79645321,a retail garment sales executive plays a vital...,eksekutif penjualan,error: [errno 11001] getaddrinfo failed,"ritel dan produk mengkonsumsi, asist ritel",eksekutif penjualan,ritel dan produk konsumen,asisten ritel,rp 6.000.000,rp 9.000.000 per month
4,site project staff,project staff,vnv mandiri valve,"konstruksi, manajemen proyek",jawa barat,79912142,kontrak,rp 4.500.000 - rp 5.500.000 per month,https:atauatauid.jobstreet.comataujobatau79912142,"uraian tugas : menyusun rencana proyek, termas...",staf proyek situs,"uraian tugas : menyusun rencana proyek, termas...","konstruksi, manajemen proyek",staf proyek,konstruksi,manajemen proyek,rp 4.500.000,rp 5.500.000 per month
5,kepala sipil struktur engineering,engineering,renon property emporio architect,"teknik, teknik sipilataustruktural",jakarta raya,80181996,full time,rp 8.000.000 - rp 8.100.000 per month,https:atauatauid.jobstreet.comataujobatau80181996,"kami, emporio architect . firma arsitektur yan...",kepala sipil atau struktur engineering,"kami, emporio architect . firma arsitektur yan...","teknik, teknik sipilataustruktural",rekayasa,teknik,teknik sipilataustruktural,rp 8.000.000,rp 8.100.000 per month
6,sales marketing,marketing,pratama indonesia lestari,"ritel dan produk konsumen, asisten ritel",jakarta raya,80101420,full time,rp 4.500.000 - rp 6.500.000 per month,https:atauatauid.jobstreet.comataujobatau80101420,kualifikasi : pendidikan minimal smaatausedera...,pemasaran penjualan,kualifikasi : pendidikan minimal smaatausedera...,"ritel dan produk mengkonsumsi, asist ritel",pemasaran,ritel dan produk konsumen,asisten ritel,rp 4.500.000,rp 6.500.000 per month
7,staff management korean specialist,management staff,cosmax indonesia,"administrasi dan dukungan perkantoran, asisten...",jakarta raya,79602834,full time,rp 6.000.000 - rp 8.000.000 per month,https:atauatauid.jobstreet.comataujobatau79602834,pt. cosmax indonesia is a no 1 toll manufactur...,manajemen staf (spesialis korea),error: [errno 11001] getaddrinfo failed,"administrasi dan dukungan perkantoran, asisten...",staf manajemen,administrasi dan dukungan perkantoran,asisten administratif,rp 6.000.000,rp 8.000.000 per month
8,telemarketing,tidak diketahui,era manunggal sejahtera,"penjualan, perwakilanataukonsultan penjualan",jakarta raya,79576950,full time,rp 3.500.000 - rp 4.200.000 per month,https:atauatauid.jobstreet.comataujobatau79576950,pt. era manunggal sejahtera merupakan perusaha...,telemarketing,pt. era manunggal sejahtera merupakan perusaha...,"penjualan, perwakilanataukonsultan penjualan",error: expected string or bytes-like object,penjualan,perwakilanataukonsultan penjualan,rp 3.500.000,rp 4.200.000 per month
9,pengawas lapangan interiorfurniture,field supervisor,maitaru dadijaya bali,"desain dan arsitektur, desain interior",bali,80175329,full time,rp 4.500.000 - rp 6.500.000 per month,https:atauatauid.jobstreet.comataujobatau80175329,dibutuhkan pengawas lapangan interiorataufurni...,pengawas lapangan interioratautempat,dibutuhkan pengawas lapangan interiorataufurni...,"desain dan arsitektur, desain interior",supervisor lapangan,desain dan arsitektur,desain interior,rp 4.500.000,rp 6.500.000 per month
10,senior auditor public accounting firm,accounting,equilibrium cita selaras,"akuntansi, audit – eksternal",jakarta raya,80144596,full time,rp 7.500.000 - rp 11.000.000 per month,https:atauatauid.jobstreet.comataujobatau80144596,our client – ​​an established public accountin...,auditor senior (firma akuntansi publik),error: [errno 11001] getaddrinfo failed,"akuntansi, audit – eksternal",akuntansi,akuntansi,audit – eksternal,rp 7.500.000,rp 11.000.000 per month
11,sales executive,sales executive,pengiklan anonim,"penjualan, perwakilanataukonsultan penjualan",jawa barat,79702119,kontrak,rp 3.800.000 - rp 4.602.000 per month,https:atauatauid.jobstreet.comataujobatau79702119,tugas tanggungjawab : mengidentifikasi dan men...,penjualan eksekutif,tugas tanggungjawab : mengidentifikasi dan men...,"penjualan, perwakilanataukonsultan penjualan",eksekutif penjualan,penjualan,perwakilanataukonsultan penjualan,rp 3.800.000,rp 4.602.000 per month
12,merchandiser,merchandiser,kafe batavia fatahillah,"ritel dan produk konsumen, merchandiser",jakarta raya,79800476,full time,rp 5.000.000 - rp 7.000.000 per month,https:atauatauid.jobstreet.comataujobatau79800476,kualifikasi 1. pendidikan min smk atau d3 (per...,merchandiser,kualifikasi 1. pendidikan min smk atau d3 (per...,"ritel dan produk mengkonsumsi, merchandiser",merchandiser,ritel dan produk konsumen,merchandiser,rp 5.000.000,rp 7.000.000 per month
13,receiptionist bali,receptionist,samudra estetika perkasa,"ritel dan produk konsumen, asisten ritel",bali,80175828,full time,rp 3.000.000 - rp 3.096.823 per month,https:atauatauid.jobstreet.comataujobatau80175828,tanggung jawab : mengurus registrasi membalas ...,resepsionis (bali),tanggung jawab : mengurus registrasi membalas ...,"ritel dan produk mengkonsumsi, asist ritel",resepsionis,ritel dan produk konsumen,asisten ritel,rp 3.000.000,rp 3.096.823 per month
14,administrasi spv sa,supervisor,golden brilliant sanitaryware,"ritel dan produk konsumen, asisten ritel",jawa barat,80185299,full time,rp 3.500.000 - rp 4.500.000 per month,https:atauatauid.jobstreet.comataujobatau80185299,pt. golden brilliant sanitaryware (germany bri...,administrasi adalah spv sa,pt. golden brilliant sanitaryware (germany bri...,"ritel dan produk mengkonsumsi, asist ritel",pengawas,ritel dan produk konsumen,asisten ritel,rp 3.500.000,rp 4.500.000 per month
15,dokter kecantikan estetika,beauty doctor,skn atelier,"kesehatan dan medis, dokter umum",banten,79645796,full time,rp 11.500.000 - rp 15.000.000 per month,https:atauatauid.jobstreet.comataujobatau79645796,kualifikasi : pendidikan profesi dokter (s1) m...,dokter kecantikan atau estetika,kualifikasi : pendidikan profesi dokter (s1) m...,"kesehatan dan medis, dokter umum",doktor kecantikan,kesehatan dan medis,dokter umum,rp 11.500.000,rp 15.000.000 per month
16,deputy sales manager,sales manager,iconic talent indonesia,"penjualan, manajemen",jawa barat,79993623,full time,rp 23.500.000 - rp 26.500.000 per month,https:atauatauid.jobstreet.comataujobatau79993623,responsibilities or job desc • implementation ...,wakil manajer penjualan,error: [errno 11001] getaddrinfo failed,"penjualan, manajemen",manajer penjualan,penjualan,manajemen,rp 23.500.000,rp 26.500.000 per month
17,production line leader mandarin speaker,production line leader,cfu technology indonesia,"manufaktur, transportasi dan logistik, pemimpi...",jawa barat,79657626,kontrak,rp 5.500.000 - rp 6.500.000 per month,https:atauatauid.jobstreet.comataujobatau79657626,1.running day to day productionactivity in goo...,pemimpin jalur produksi (pembicara mandarin),error: [errno 11001] getaddrinfo failed,"manufaktur, transportasi dan logistik, pemimpi...",pemimpin produksi-line,manufaktur,transportasi dan logistik,rp 5.500.000,rp 6.500.000 per month
18,videographer,videographer,putra perkasa,"periklanan, seni dan media, fotografi",jawa timur,79695850,full time,"rp 5,000,000 - rp 5,500,000 per month",https:atauatauid.jobstreet.comataujobatau79695850,triv adalah salah satu bursa kripto terbesar d...,videografer,triv adalah salah satu bursa kripto terbesar d...,"periklanan, seni dan media, fotografi",videografer,periklanan,seni dan media,"rp 5,000,000","rp 5,500,000 per month"
19,analis lab plating qc staff,laboratory analyst,nichias metalworks indonesia,"sains dan teknologi, jasa laboratorium dan teknis",jawa barat,80061013,full time,rp 7.000.000 - rp 8.000.000 per month,https:atauatauid.jobstreet.comataujobatau80061013,tugas dan tanggung jawab : melakukan analisa s...,lab analis.plating (staf qc),tugas dan tanggung jawab : melakukan analisa s...,"sains dan teknologi, jasa laboratorium dan teknis",laboratorium-analis,sains dan teknologi,jasa laboratorium dan teknis,rp 7.000.000,rp 8.000.000 per month
20,sales project,sales,shinmado,"penjualan, perwakilanataukonsultan penjualan",jakarta raya,79517441,full time,rp 5.000.000 - rp 7.000.000 per month,https:atauatauid.jobstreet.comataujobatau79517441,job description qualifications: at least 2-3 y...,proyek penjualan,error: [errno 11001] getaddrinfo failed,"penjualan, perwakilanataukonsultan penjualan",penjualan,penjualan,perwakilanataukonsultan penjualan,rp 5.000.000,rp 7.000.000 per month
21,fullstack developer,full stack developer,koffiesoft group,"teknologi informasi dan komunikasi, developera...",jawa timur,80161629,full time,rp 4.500.000 - rp 6.750.000 per month,https:atauatauid.jobstreet.comataujobatau80161629,• berpengalaman minimal 3 tahun menggunakan ph...,pengembang tumpukan penuh,• berpengalaman minimal 3 tahun menggunakan ph...,"teknologi informasi dan komunikasi, developera...",pengembang full-stack,teknologi informasi dan komunikasi,developeratauprogrammer,rp 4.500.000,rp 6.750.000 per month
22,customer service japanese speaker,customer service role,akazora usaha mandiri,"call center dan layanan konsumen, layanan kons...",jawa barat,80102855,full time,rp 5.200.000 - rp 5.500.000 per month,https:atauatauid.jobstreet.comataujobatau80102855,kualifikasi: usia minimal 23 tahun maksimal 40...,layanan pelanggan (pembicara jepang),kualifikasi: usia minimal 23 tahun maksimal 40...,"call center dan layanan konsumen, layanan kons...",perangkalan layanan pelanggan,call center dan layanan konsumen,layanan konsumen – berhadapan dengan konsumen,rp 5.200.000,rp 5.500.000 per month
23,sales marketing,marketing,cia aneka selera,"penjualan, pengembangan bisnis baru",jawa barat,79760681,full time,"rp 5,500,000 - rp 6,200,000 per month",https:atauatauid.jobstreet.comataujobatau79760681,kualfikasi : bertanggung jawab pendidikan mini...,pemasaran penjualan,kualfikasi : bertanggung jawab pendidikan mini...,"penjualan, pengembangan bisnis baru",marketing,penjualan,pengembangan bisnis baru,"rp 5,500,000","rp 6,200,000 per month"
24,bancassurance specialist jakarta kemayoran,bancassurance specialist,bni life insurance,"penjualan, perwakilanataukonsultan penjualan",jakarta raya,80093228,full time,"rp 2,000,000 - rp 3,000,000 per month",https:atauatauid.jobstreet.comataujobatau80093228,bancassurance specialist (bas) representative ...,bancassurance specialist - jakarta kemayoran,bancassurance specialist (bas) representative ...,"penjualan, perwakilanataukonsultan penjualan",spesialis bancassurance,penjualan,perwakilanataukonsultan penjualan,"rp 2,000,000","rp 3,000,000 per month"
25,sales marketing,marketing,ruang sukses indonesia,"penjualan, perwakilanataukonsultan penjualan",jakarta raya,79854347,full time,rp 3.500.000 - rp 4.500.000 per month,https:atauatauid.jobstreet.comataujobatau79854347,ruangpedia sedang mencari tenaga profesional s...,penjualan dan pemasaran,ruangpedia sedang mencari tenaga profesional s...,"penjualan, perwakilanataukonsultan penjualan",pemasaran,penjualan,perwakilanataukonsultan penjualan,rp 3.500.000,rp 4.500.000 per month
26,security manager area pekanbaru,security manager,sigap prima astrea,"keterampilan dan jasa, jasa keamanan",riau,79676318,full time,"rp 6,500,000 - rp 7,000,000 per month",https:atauatauid.jobstreet.comataujobatau79676318,kualifikasi: pendidikan s1 segala jurusan deng...,security manager (area pekanbaru),kualifikasi: pendidikan s1 segala jurusan deng...,"keterampilan dan jasa, jasa keamanan",manajer keamanan,keterampilan dan jasa,jasa keamanan,"rp 6,500,000","rp 7,000,000 per month"
27,account manager,account manager,yuxi jayatama indonesia,"periklanan, seni dan media, manajemen akun agensi",jakarta raya,79720509,full time,rp 7.500.000 - rp 11.000.000 per month,https:atauatauid.jobstreet.comataujobatau79720509,about us : yuxi jayatama is an multi-channel n...,manajer akun,error: [errno 11001] getaddrinfo failed,"periklanan, seni dan media, manajemen akun agensi",manajer akun,periklanan,seni dan media,rp 7.500.000,rp 11.000.000 per month
28,recruitment officer,recruitment officer,bimasakti multi sinergi,"sumber daya manusia dan perekrutan, perekrutan...",jawa timur,79946300,full time,rp 4.500.000 - rp 5.000.000 per month,https:atauatauid.jobstreet.comataujobatau79946300,"manage sourcing for multiple, complex searches...",petugas perekrutan,error: [errno 11001] getaddrinfo failed,"sumber daya manusia dan perekrutan, perekrutan...",kepala recrutment,sumber daya manusia dan perekrutan,perekrutan – internal,rp 4.500.000,rp 5.000.000 per month
29,driver bluebird bekasi,driver,morante jaya tbk bekasi,"manufaktur, transportasi dan logistik, transpo...",jawa barat,80003440,full time,rp 4.500.000 - rp 6.500.000 per month,https:atauatauid.jobstreet.comataujobatau80003440,perusahaan jasa transportasi terbaik di indone...,driver bluebird bekasi,perusahaan jasa transportasi terbaik di indone...,"manufaktur, transportasi dan logistik, transpo...",pengemudi,manufaktur,transportasi dan logistik,rp 4.500.000,rp 6.500.000 per month
30,export import manager,export import manager,elit solusi niaga,"manufaktur, transportasi dan logistik, imporat...",jakarta raya,79705035,full time,rp 20.000.000 - rp 25.000.000 per month,https:atauatauid.jobstreet.comataujobatau79705035,qualifications bachelor’s degreeataumaster deg...,manajer impor ekspor,error: [errno 11001] getaddrinfo failed,"manufaktur, transportasi dan logistik, penting...",ekspor-impor-manajer,manufaktur,transportasi dan logistik,rp 20.000.000,rp 25.000.000 per month

In [115]:
df['salary_min'] = df['salary_min'].str.replace(r'\D', '', regex=True)
df['salary_max'] = df['salary_max'].str.replace(r'\D', '', regex=True)

C:\Users\USER\AppData\Local\Temp\ipykernel_24436\3265982763.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['salary_min'] = df['salary_min'].str.replace(r'\D', '', regex=True)
C:\Users\USER\AppData\Local\Temp\ipykernel_24436\3265982763.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['salary_max'] = df['salary_max'].str.replace(r'\D', '', regex=True)

In [116]:
df.head()

,title,role,company_name,category,location,jobId,type,salary,url,description,title_translated,description_translated,category_translated,role_translated,category_1,category_2,salary_min,salary_max
0,penerjemah bahasa mandarinasisten manajer umum,mandarin translator,onemate aksesoris mobil,"administrasi dan dukungan perkantoran, asisten...",banten,79976110,full time,rp 8.500.000 - rp 12.500.000 per month,https:atauatauid.jobstreet.comataujobatau79976110,asisten manajer umum: • membantu manajer umum ...,penerjemah bahasa mandarin，asisten manajer umum,asisten manajer umum: • membantu manajer umum ...,"administrasi dan dukungan perkantoran, asisten...",mandarin-translator,administrasi dan dukungan perkantoran,asisten administratif,8500000,12500000
1,it business analyst,information technology business analyst,nextalent talenta nusantara,"teknologi informasi dan komunikasi, analis bis...",jakarta raya,80187093,full time,rp 10.000.000 - rp 14.000.000 per month,https:atauatauid.jobstreet.comataujobatau80187093,qualification : candidate must possess at leas...,analis bisnis ti,error: [errno 11001] getaddrinfo failed,"teknolog informasi dan komununasi, anis bisnis...",informasi-teknologi-business-analyst,teknologi informasi dan komunikasi,analis bisnisatausistem,10000000,14000000
3,sales executive,sales executive,laxmi utama,"ritel dan produk konsumen, asisten ritel",jawa timur,79645321,full time,rp 6.000.000 - rp 9.000.000 per month,https:atauatauid.jobstreet.comataujobatau79645321,a retail garment sales executive plays a vital...,eksekutif penjualan,error: [errno 11001] getaddrinfo failed,"ritel dan produk mengkonsumsi, asist ritel",eksekutif penjualan,ritel dan produk konsumen,asisten ritel,6000000,9000000
4,site project staff,project staff,vnv mandiri valve,"konstruksi, manajemen proyek",jawa barat,79912142,kontrak,rp 4.500.000 - rp 5.500.000 per month,https:atauatauid.jobstreet.comataujobatau79912142,"uraian tugas : menyusun rencana proyek, termas...",staf proyek situs,"uraian tugas : menyusun rencana proyek, termas...","konstruksi, manajemen proyek",staf proyek,konstruksi,manajemen proyek,4500000,5500000
5,kepala sipil struktur engineering,engineering,renon property emporio architect,"teknik, teknik sipilataustruktural",jakarta raya,80181996,full time,rp 8.000.000 - rp 8.100.000 per month,https:atauatauid.jobstreet.comataujobatau80181996,"kami, emporio architect . firma arsitektur yan...",kepala sipil atau struktur engineering,"kami, emporio architect . firma arsitektur yan...","teknik, teknik sipilataustruktural",rekayasa,teknik,teknik sipilataustruktural,8000000,8100000

In [118]:
df.head()

,title,role,company_name,category,location,jobId,type,salary,url,description,title_translated,description_translated,category_translated,role_translated,category_1,category_2,salary_min,salary_max
0,penerjemah bahasa mandarinasisten manajer umum,mandarin translator,onemate aksesoris mobil,"administrasi dan dukungan perkantoran, asisten...",banten,79976110,full time,rp 8.500.000 - rp 12.500.000 per month,https:atauatauid.jobstreet.comataujobatau79976110,asisten manajer umum: • membantu manajer umum ...,penerjemah bahasa mandarin，asisten manajer umum,asisten manajer umum: • membantu manajer umum ...,"administrasi dan dukungan perkantoran, asisten...",mandarin-translator,administrasi dan dukungan perkantoran,asisten administratif,8500000,12500000
1,it business analyst,information technology business analyst,nextalent talenta nusantara,"teknologi informasi dan komunikasi, analis bis...",jakarta raya,80187093,full time,rp 10.000.000 - rp 14.000.000 per month,https:atauatauid.jobstreet.comataujobatau80187093,qualification : candidate must possess at leas...,analis bisnis ti,error: [errno 11001] getaddrinfo failed,"teknolog informasi dan komununasi, anis bisnis...",informasi-teknologi-business-analyst,teknologi informasi dan komunikasi,analis bisnisatausistem,10000000,14000000
3,sales executive,sales executive,laxmi utama,"ritel dan produk konsumen, asisten ritel",jawa timur,79645321,full time,rp 6.000.000 - rp 9.000.000 per month,https:atauatauid.jobstreet.comataujobatau79645321,a retail garment sales executive plays a vital...,eksekutif penjualan,error: [errno 11001] getaddrinfo failed,"ritel dan produk mengkonsumsi, asist ritel",eksekutif penjualan,ritel dan produk konsumen,asisten ritel,6000000,9000000
4,site project staff,project staff,vnv mandiri valve,"konstruksi, manajemen proyek",jawa barat,79912142,kontrak,rp 4.500.000 - rp 5.500.000 per month,https:atauatauid.jobstreet.comataujobatau79912142,"uraian tugas : menyusun rencana proyek, termas...",staf proyek situs,"uraian tugas : menyusun rencana proyek, termas...","konstruksi, manajemen proyek",staf proyek,konstruksi,manajemen proyek,4500000,5500000
5,kepala sipil struktur engineering,engineering,renon property emporio architect,"teknik, teknik sipilataustruktural",jakarta raya,80181996,full time,rp 8.000.000 - rp 8.100.000 per month,https:atauatauid.jobstreet.comataujobatau80181996,"kami, emporio architect . firma arsitektur yan...",kepala sipil atau struktur engineering,"kami, emporio architect . firma arsitektur yan...","teknik, teknik sipilataustruktural",rekayasa,teknik,teknik sipilataustruktural,8000000,8100000

In [119]:
salary_counts = df['salary_min'].value_counts()
for salary, count in salary_counts.items():
    print(f'{salary}: {count}')

5000000: 810
4000000: 580
6000000: 518
7000000: 356
8000000: 343
10000000: 336
4500000: 327
3500000: 295
5500000: 272
3000000: 267
15000000: 129
9000000: 121
2500000: 117
12000000: 100
6500000: 99
20000000: 77
2000000: 72
7500000: 64
5100000: 45
4800000: 39
4700000: 38
14000000: 37
13000000: 36
11000000: 34
18000000: 29
5200000: 28
8500000: 27
4600000: 25
25000000: 24
3300000: 23
2800000: 23
3800000: 21
5067381: 20
17000000: 20
2700000: 19
16000000: 18
3600000: 17
3200000: 17
3700000: 16
4300000: 16
4200000: 16
30000000: 15
3400000: 15
6700000: 15
3750000: 15
2200000: 14
4750000: 13
4400000: 12
5068000: 12
9500000: 10
2600000: 10
1500000: 10
5300000: 10
4900000: 9
13500000: 9
4250000: 9
3900000: 9
3250000: 9
5400000: 9
2900000: 8
12500000: 8
3100000: 7
5070000: 7
5333333: 7
2750000: 7
40000000: 7
5250000: 6
2300000: 6
2400000: 6
35000000: 6
3452000: 5
22000000: 5
5700000: 5
3350000: 5
5800000: 5
: 5
13333333: 5
23000000: 4
45000000: 4
6666667: 4
1000000: 4
4760289: 4
60000000: 4
5750000: 4
5600000: 3
27000000: 3
8666667: 3
1800000: 3
2492997: 3
8700000: 3
11500000: 3
2850000: 3
2250000: 3
50000000: 3
4666667: 3
5219263: 3
2250300: 3
3770000: 3
5060000: 3
1900000: 3
2233000: 2
6900000: 2
9400000: 2
10500000: 2
4670791: 2
5900000: 2
5080000: 2
6600000: 2
4902500: 2
4650000: 2
7199000: 2
5067500: 2
5258000: 2
3243969: 2
3545000: 2
28000000: 2
5350000: 2
24000000: 2
5067000: 2
4725000: 2
1750000: 2
4671000: 2
16666667: 2
65000000: 2
3650000: 2
4561000: 2
21000000: 2
13250000: 2
2333333: 2
6750000: 2
23500000: 2
19000000: 2
4725479: 2
5340000: 2
6200000: 2
2550000: 2
15500000: 2
7850000: 2
4670000: 2
16500000: 2
5150000: 2
4550000: 2
6800000: 2
4100000: 2
3333333: 2
3244000: 1
4760290: 1
2492000: 1
9800000: 1
53333333: 1
5270000: 1
5130000: 1
4639000: 1
4579541: 1
3712000: 1
1200000: 1
3888000: 1
4280000: 1
2390000: 1
3150000: 1
7999999: 1
3310000: 1
900000: 1
4642031: 1
5510000: 1
5065000: 1
4050000: 1
5610000: 1
2460000: 1
2049000: 1
15333333: 1
2350000: 1
2269070: 1
21500000: 1
12250000: 1
2492977: 1
5219000: 1
6000008: 1
3318628: 1
4901798: 1
500000: 1
4090000: 1
4830000: 1
2870000: 1
4580000: 1
33333333: 1
7900000: 1
4210000: 1
8300000: 1
4350000: 1
3451584: 1
4726000: 1
8200000: 1
4500999: 1
5650000: 1
3666667: 1
3103631: 1
13850000: 1
9100000: 1
4880000: 1
4120000: 1
6400000: 1
5290000: 1
5257834: 1
2324775: 1
3950000: 1
150000000: 1
4725500: 1
6350000: 1
3475595: 1
17700000: 1
8750000: 1
15: 1
17500000: 1
2176794166: 1
6100000: 1
85000000: 1
10700000: 1
2517730: 1
10750000: 1
4902000: 1
5101000: 1
6950000: 1
4638582: 1
4260000: 1
2270000: 1
2378000: 1
38000000: 1
3282812: 1
3440000: 1
20700000: 1
2692997: 1
4499768: 1
5067382: 1
1700000: 1
3294500: 1
6721716: 1
4685050: 1
16700000: 1
5666667: 1
4760000: 1
3384491: 1
8349000: 1
6825000: 1
2125897: 1
5343430: 1
4333333: 1
3480000: 1
4640000: 1
4527688: 1
2823000: 1
1: 1
3240000: 1
3319000: 1
26000000: 1
7333333: 1
3920000: 1
2533038: 1
9450000: 1
6: 1
4638581: 1
70000000: 1
8160000: 1
4950000: 1
4000008: 1
3515324: 1
4879000: 1
7400000: 1
4602000: 1
3025100: 1
6333333: 1
6777777: 1
5000004: 1
4209309: 1
5067400: 1
7049250: 1
2999999: 1
2431628: 1

In [122]:
df['salary_min'].replace(r'^\s*$', np.nan, regex=True, inplace=True)

C:\Users\USER\AppData\Local\Temp\ipykernel_24436\3001082029.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['salary_min'].replace(r'^\s*$', np.nan, regex=True, inplace=True)
C:\Users\USER\AppData\Local\Temp\ipykernel_24436\3001082029.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['salary_min'].replace(r'^\s*$', np.nan, regex=True, inplace=True)

In [123]:
df['salary_min'].isnull().sum()

5

In [124]:
df = df.dropna(subset=['salary_min'])

In [125]:
df = df[df['salary_min'].apply(lambda x: len(x) > 2)]

In [126]:
salary_counts = df['salary_min'].value_counts()
for salary, count in salary_counts.items():
    print(f'{salary}: {count}')

5000000: 810
4000000: 580
6000000: 518
7000000: 356
8000000: 343
10000000: 336
4500000: 327
3500000: 295
5500000: 272
3000000: 267
15000000: 129
9000000: 121
2500000: 117
12000000: 100
6500000: 99
20000000: 77
2000000: 72
7500000: 64
5100000: 45
4800000: 39
4700000: 38
14000000: 37
13000000: 36
11000000: 34
18000000: 29
5200000: 28
8500000: 27
4600000: 25
25000000: 24
2800000: 23
3300000: 23
3800000: 21
5067381: 20
17000000: 20
2700000: 19
16000000: 18
3200000: 17
3600000: 17
3700000: 16
4300000: 16
4200000: 16
3400000: 15
3750000: 15
30000000: 15
6700000: 15
2200000: 14
4750000: 13
4400000: 12
5068000: 12
2600000: 10
9500000: 10
5300000: 10
1500000: 10
4900000: 9
13500000: 9
4250000: 9
5400000: 9
3900000: 9
3250000: 9
2900000: 8
12500000: 8
5333333: 7
3100000: 7
2750000: 7
40000000: 7
5070000: 7
2300000: 6
2400000: 6
5250000: 6
35000000: 6
13333333: 5
3350000: 5
3452000: 5
5700000: 5
22000000: 5
5800000: 5
45000000: 4
5750000: 4
23000000: 4
4760289: 4
1000000: 4
6666667: 4
60000000: 4
5600000: 3
2492997: 3
8700000: 3
11500000: 3
1800000: 3
8666667: 3
27000000: 3
2850000: 3
5060000: 3
2250000: 3
1900000: 3
4666667: 3
3770000: 3
5219263: 3
50000000: 3
2250300: 3
3243969: 2
4561000: 2
4650000: 2
4670791: 2
6600000: 2
5900000: 2
5080000: 2
5067500: 2
10500000: 2
9400000: 2
21000000: 2
6900000: 2
4902500: 2
5350000: 2
4671000: 2
5258000: 2
3545000: 2
4725000: 2
1750000: 2
28000000: 2
24000000: 2
3650000: 2
16666667: 2
5067000: 2
65000000: 2
2233000: 2
4725479: 2
7850000: 2
13250000: 2
23500000: 2
15500000: 2
4670000: 2
6750000: 2
7199000: 2
6800000: 2
16500000: 2
2550000: 2
5340000: 2
2333333: 2
6200000: 2
19000000: 2
4550000: 2
4100000: 2
5150000: 2
3333333: 2
500000: 1
4090000: 1
2460000: 1
2049000: 1
2492977: 1
5610000: 1
4830000: 1
5290000: 1
33333333: 1
4050000: 1
4580000: 1
5065000: 1
3712000: 1
4642031: 1
900000: 1
7900000: 1
4210000: 1
7999999: 1
8300000: 1
3150000: 1
2390000: 1
4350000: 1
4280000: 1
17700000: 1
15333333: 1
5130000: 1
3888000: 1
6400000: 1
3480000: 1
2324775: 1
4500999: 1
4880000: 1
3950000: 1
9100000: 1
13850000: 1
21500000: 1
150000000: 1
3666667: 1
4725500: 1
5650000: 1
8200000: 1
12250000: 1
4726000: 1
1200000: 1
2870000: 1
2269070: 1
3451584: 1
4639000: 1
5270000: 1
53333333: 1
4760290: 1
5219000: 1
9800000: 1
6000008: 1
5257834: 1
3318628: 1
3244000: 1
4901798: 1
10750000: 1
2350000: 1
4640000: 1
4579541: 1
38000000: 1
3282812: 1
2692997: 1
6721716: 1
5666667: 1
3240000: 1
8349000: 1
8750000: 1
3384491: 1
4760000: 1
16700000: 1
4685050: 1
3294500: 1
1700000: 1
6100000: 1
2517730: 1
4527688: 1
9450000: 1
5510000: 1
3310000: 1
6350000: 1
4120000: 1
3103631: 1
3475595: 1
3515324: 1
4902000: 1
7400000: 1
3025100: 1
6333333: 1
5000004: 1
7049250: 1
6825000: 1
5067382: 1
4499768: 1
20700000: 1
4333333: 1
6777777: 1
4602000: 1
4879000: 1
4000008: 1
4950000: 1
70000000: 1
4638581: 1
3440000: 1
2533038: 1
3920000: 1
7333333: 1
26000000: 1
3319000: 1
2823000: 1
4209309: 1
5067400: 1
2999999: 1
8160000: 1
5343430: 1
2125897: 1
2270000: 1
4260000: 1
4638582: 1
6950000: 1
5101000: 1
2492000: 1
10700000: 1
85000000: 1
2176794166: 1
17500000: 1
2378000: 1
2431628: 1

In [127]:
df['salary_max'].replace(r'^\s*$', np.nan, regex=True, inplace=True)
df['salary_max'].isnull().sum()

77

In [128]:
#mengisi nilai kosong di salary_max dengan nilai dari salary_min
df['salary_max'].fillna(df['salary_min'], inplace=True)

In [129]:
df['salary_max'].isnull().sum()

0

In [130]:
df = df[df['salary_min'] != '2176794166']

In [131]:
salary_counts = df['salary_min'].value_counts()
for salary, count in salary_counts.items():
    print(f'{salary}: {count}')

5000000: 810
4000000: 580
6000000: 518
7000000: 356
8000000: 343
10000000: 336
4500000: 327
3500000: 295
5500000: 272
3000000: 267
15000000: 129
9000000: 121
2500000: 117
12000000: 100
6500000: 99
20000000: 77
2000000: 72
7500000: 64
5100000: 45
4800000: 39
4700000: 38
14000000: 37
13000000: 36
11000000: 34
18000000: 29
5200000: 28
8500000: 27
4600000: 25
25000000: 24
3300000: 23
2800000: 23
3800000: 21
17000000: 20
5067381: 20
2700000: 19
16000000: 18
3200000: 17
3600000: 17
3700000: 16
4300000: 16
4200000: 16
3750000: 15
6700000: 15
30000000: 15
3400000: 15
2200000: 14
4750000: 13
4400000: 12
5068000: 12
9500000: 10
1500000: 10
5300000: 10
2600000: 10
4250000: 9
13500000: 9
3250000: 9
4900000: 9
3900000: 9
5400000: 9
2900000: 8
12500000: 8
40000000: 7
5333333: 7
3100000: 7
2750000: 7
5070000: 7
2400000: 6
35000000: 6
2300000: 6
5250000: 6
3452000: 5
22000000: 5
3350000: 5
5800000: 5
5700000: 5
13333333: 5
4760289: 4
1000000: 4
45000000: 4
6666667: 4
60000000: 4
23000000: 4
5750000: 4
1800000: 3
27000000: 3
8666667: 3
2850000: 3
5600000: 3
2492997: 3
8700000: 3
5060000: 3
11500000: 3
5219263: 3
2250000: 3
3770000: 3
1900000: 3
4666667: 3
2250300: 3
50000000: 3
4725000: 2
5067500: 2
4902500: 2
6600000: 2
2233000: 2
28000000: 2
10500000: 2
3545000: 2
9400000: 2
5258000: 2
6900000: 2
4670791: 2
1750000: 2
21000000: 2
5350000: 2
3243969: 2
65000000: 2
5080000: 2
3650000: 2
4650000: 2
24000000: 2
5067000: 2
4561000: 2
16666667: 2
4671000: 2
7199000: 2
5150000: 2
7850000: 2
4670000: 2
6800000: 2
13250000: 2
2550000: 2
6750000: 2
6200000: 2
19000000: 2
15500000: 2
5900000: 2
16500000: 2
2333333: 2
4725479: 2
4100000: 2
4550000: 2
23500000: 2
3333333: 2
5340000: 2
2049000: 1
2460000: 1
15333333: 1
500000: 1
4090000: 1
4901798: 1
2492977: 1
4830000: 1
4050000: 1
5610000: 1
4580000: 1
33333333: 1
3888000: 1
5065000: 1
7900000: 1
4642031: 1
900000: 1
4210000: 1
7999999: 1
3150000: 1
8300000: 1
2390000: 1
4280000: 1
4350000: 1
3712000: 1
4500999: 1
1200000: 1
3244000: 1
5290000: 1
4880000: 1
9100000: 1
13850000: 1
5257834: 1
21500000: 1
2324775: 1
3666667: 1
3950000: 1
150000000: 1
5650000: 1
8200000: 1
4725500: 1
12250000: 1
10750000: 1
6400000: 1
4726000: 1
2269070: 1
4639000: 1
5270000: 1
53333333: 1
2870000: 1
3451584: 1
5219000: 1
6000008: 1
4760290: 1
9800000: 1
3318628: 1
5130000: 1
17700000: 1
4685050: 1
3480000: 1
5666667: 1
8750000: 1
6100000: 1
38000000: 1
3282812: 1
2692997: 1
6721716: 1
3240000: 1
4902000: 1
4579541: 1
8349000: 1
3384491: 1
4760000: 1
16700000: 1
3294500: 1
2517730: 1
6825000: 1
4640000: 1
3103631: 1
4120000: 1
2350000: 1
2492000: 1
5510000: 1
3310000: 1
6350000: 1
3475595: 1
7049250: 1
9450000: 1
3515324: 1
7400000: 1
3025100: 1
6333333: 1
5000004: 1
1700000: 1
5067382: 1
4499768: 1
4638581: 1
4602000: 1
4879000: 1
4000008: 1
4950000: 1
70000000: 1
4333333: 1
2533038: 1
20700000: 1
3920000: 1
7333333: 1
26000000: 1
3319000: 1
2823000: 1
4527688: 1
6777777: 1
4209309: 1
5067400: 1
2999999: 1
8160000: 1
5343430: 1
2125897: 1
2270000: 1
4260000: 1
4638582: 1
6950000: 1
5101000: 1
10700000: 1
85000000: 1
17500000: 1
2378000: 1
3440000: 1
2431628: 1

In [132]:
df.shape

(6076, 18)

# url

In [133]:
# kolom url tidak diapa-apain

# Description

In [2]:
import re
from nltk.corpus import wordnet
from nltk.stem import WordNetLemmatizer
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory

In [143]:
df.head()

,title,role,company_name,category,location,jobId,type,salary,url,description,category_1,category_2,salary_min,salary_max
0,penerjemah bahasa mandarinasisten manajer umum,mandarin translator,onemate aksesoris mobil,"administrasi dan dukungan perkantoran, asisten...",banten,79976110,full time,rp 8.500.000 - rp 12.500.000 per month,https:atauatauid.jobstreet.comataujobatau79976110,asisten manajer umum: • membantu manajer umum ...,administrasi dan dukungan perkantoran,asisten administratif,8500000,12500000
1,it business analyst,information technology business analyst,nextalent talenta nusantara,"teknologi informasi dan komunikasi, analis bis...",jakarta raya,80187093,full time,rp 10.000.000 - rp 14.000.000 per month,https:atauatauid.jobstreet.comataujobatau80187093,qualification : candidate must possess at leas...,teknologi informasi dan komunikasi,analis bisnisatausistem,10000000,14000000
3,sales executive,sales executive,laxmi utama,"ritel dan produk konsumen, asisten ritel",jawa timur,79645321,full time,rp 6.000.000 - rp 9.000.000 per month,https:atauatauid.jobstreet.comataujobatau79645321,a retail garment sales executive plays a vital...,ritel dan produk konsumen,asisten ritel,6000000,9000000
4,site project staff,project staff,vnv mandiri valve,"konstruksi, manajemen proyek",jawa barat,79912142,kontrak,rp 4.500.000 - rp 5.500.000 per month,https:atauatauid.jobstreet.comataujobatau79912142,"uraian tugas : menyusun rencana proyek, termas...",konstruksi,manajemen proyek,4500000,5500000
5,kepala sipil struktur engineering,engineering,renon property emporio architect,"teknik, teknik sipilataustruktural",jakarta raya,80181996,full time,rp 8.000.000 - rp 8.100.000 per month,https:atauatauid.jobstreet.comataujobatau80181996,"kami, emporio architect . firma arsitektur yan...",teknik,teknik sipilataustruktural,8000000,8100000

In [144]:
# Inisialisasi stemmer Sastrawi untuk Bahasa Indonesia
factory = StemmerFactory()
stemmer_indo = factory.create_stemmer()

In [145]:
# Inisialisasi lemmatizer NLTK untuk Bahasa Inggris
lemmatizer_en = WordNetLemmatizer()

In [7]:
#hapus tanda baca, emotikon, dan hurus non latin.
def clean_text(text):
    text = re.sub(r'[^\w\s]', '', text)  # Hapus tanda baca
    text = re.sub(r'\d+', '', text)      # Hapus angka
    text = re.sub(r'[^\x00-\x7F]+', '', text)  # Hapus karakter non-ASCII
    return text.lower()

In [147]:
# Lematisasi campuran bahasa
def lemmatize_mixed_language(text):
    words = text.split()
    lemmatized_words = []
    for word in words:
        # Lematisasi menggunakan NLTK untuk kata Bahasa Inggris
        if wordnet.synsets(word):
            lemmatized_word = lemmatizer_en.lemmatize(word.lower())
        else:
            # Lematisasi menggunakan Sastrawi untuk kata Bahasa Indonesia
            lemmatized_word = stemmer_indo.stem(word.lower())
        lemmatized_words.append(lemmatized_word)
    return ' '.join(lemmatized_words)

In [149]:
df['cleaned_description'] = df['description'].apply(lambda x: lemmatize_mixed_language(clean_text(str(x))))
print(df[['description', 'cleaned_description']].head())

                                         description  \
0  asisten manajer umum: • membantu manajer umum ...
1  qualification : candidate must possess at leas...
3  a retail garment sales executive plays a vital...
4  uraian tugas : menyusun rencana proyek, termas...
5  kami, emporio architect . firma arsitektur yan...

                                 cleaned_description
0  asisten manajer umum bantu manajer umum dalam ...
1  qualification candidate must posse at least di...
3  a retail garment sale executive play a vital r...
4  urai tugas susun rencana proyek masuk jadwal d...
5  kami emporio architect firma arsitektur yang g...

In [150]:
df.head(30)

,title,role,company_name,category,location,jobId,type,salary,url,description,category_1,category_2,salary_min,salary_max,cleaned_description
0,penerjemah bahasa mandarinasisten manajer umum,mandarin translator,onemate aksesoris mobil,"administrasi dan dukungan perkantoran, asisten...",banten,79976110,full time,rp 8.500.000 - rp 12.500.000 per month,https:atauatauid.jobstreet.comataujobatau79976110,asisten manajer umum: • membantu manajer umum ...,administrasi dan dukungan perkantoran,asisten administratif,8500000,12500000,asisten manajer umum bantu manajer umum dalam ...
1,it business analyst,information technology business analyst,nextalent talenta nusantara,"teknologi informasi dan komunikasi, analis bis...",jakarta raya,80187093,full time,rp 10.000.000 - rp 14.000.000 per month,https:atauatauid.jobstreet.comataujobatau80187093,qualification : candidate must possess at leas...,teknologi informasi dan komunikasi,analis bisnisatausistem,10000000,14000000,qualification candidate must posse at least di...
3,sales executive,sales executive,laxmi utama,"ritel dan produk konsumen, asisten ritel",jawa timur,79645321,full time,rp 6.000.000 - rp 9.000.000 per month,https:atauatauid.jobstreet.comataujobatau79645321,a retail garment sales executive plays a vital...,ritel dan produk konsumen,asisten ritel,6000000,9000000,a retail garment sale executive play a vital r...
4,site project staff,project staff,vnv mandiri valve,"konstruksi, manajemen proyek",jawa barat,79912142,kontrak,rp 4.500.000 - rp 5.500.000 per month,https:atauatauid.jobstreet.comataujobatau79912142,"uraian tugas : menyusun rencana proyek, termas...",konstruksi,manajemen proyek,4500000,5500000,urai tugas susun rencana proyek masuk jadwal d...
5,kepala sipil struktur engineering,engineering,renon property emporio architect,"teknik, teknik sipilataustruktural",jakarta raya,80181996,full time,rp 8.000.000 - rp 8.100.000 per month,https:atauatauid.jobstreet.comataujobatau80181996,"kami, emporio architect . firma arsitektur yan...",teknik,teknik sipilataustruktural,8000000,8100000,kami emporio architect firma arsitektur yang g...
6,sales marketing,marketing,pratama indonesia lestari,"ritel dan produk konsumen, asisten ritel",jakarta raya,80101420,full time,rp 4.500.000 - rp 6.500.000 per month,https:atauatauid.jobstreet.comataujobatau80101420,kualifikasi : pendidikan minimal smaatausedera...,ritel dan produk konsumen,asisten ritel,4500000,6500000,kualifikasi didik minimal smaatausederajat mil...
7,staff management korean specialist,management staff,cosmax indonesia,"administrasi dan dukungan perkantoran, asisten...",jakarta raya,79602834,full time,rp 6.000.000 - rp 8.000.000 per month,https:atauatauid.jobstreet.comataujobatau79602834,pt. cosmax indonesia is a no 1 toll manufactur...,administrasi dan dukungan perkantoran,asisten administratif,6000000,8000000,pt cosmax indonesia is a no toll manufacturing...
8,telemarketing,tidak diketahui,era manunggal sejahtera,"penjualan, perwakilanataukonsultan penjualan",jakarta raya,79576950,full time,rp 3.500.000 - rp 4.200.000 per month,https:atauatauid.jobstreet.comataujobatau79576950,pt. era manunggal sejahtera merupakan perusaha...,penjualan,perwakilanataukonsultan penjualan,3500000,4200000,pt era manunggal sejahtera rupa usaha yang ger...
9,pengawas lapangan interiorfurniture,field supervisor,maitaru dadijaya bali,"desain dan arsitektur, desain interior",bali,80175329,full time,rp 4.500.000 - rp 6.500.000 per month,https:atauatauid.jobstreet.comataujobatau80175329,dibutuhkan pengawas lapangan interiorataufurni...,desain dan arsitektur,desain interior,4500000,6500000,butuh awas lapang interiorataufurniture at mai...
10,senior auditor public accounting firm,accounting,equilibrium cita selaras,"akuntansi, audit – eksternal",jakarta raya,80144596,full time,rp 7.500.000 - rp 11.000.000 per month,https:atauatauid.jobstreet.comataujobatau80144596,our client – ​​an established public accountin...,akuntansi,audit – eksternal,7500000,11000000,our client an established public accounting fi...
11,sales executive,sales executive,pengiklan anonim,"penjualan, perwakilanataukonsultan penjualan",jawa barat,79702119,kontrak,rp 3.800.000 - rp 4.602.000 per month,https:atauatauid.jobstreet.comataujobatau79702119,tugas tanggungjawab : mengidentifikasi dan men...,penjualan,perwakilanataukonsultan penjualan,3800000,4602000,tugas tanggungjawab identifikasi dan cari pelu...
12,merchandiser,merchandiser,kafe batavia fatahillah,"ritel dan produk konsumen, merchandiser",jakarta raya,79800476,full time,rp 5.000.000 - rp 7.000.000 per month,https:atauatauid.jobstreet.comataujobatau79800476,kualifikasi 1. pendidikan min smk atau d3 (per...,ritel dan produk konsumen,merchandiser,5000000,7000000,kualifikasi didik min smk atau d hotel atau re...
13,receiptionist bali,receptionist,samudra estetika perkasa,"ritel dan produk konsumen, asisten ritel",bali,80175828,full time,rp 3.000.000 - rp 3.096.823 per month,https:atauatauid.jobstreet.comataujobatau80175828,tanggung jawab : mengurus registrasi membalas ...,ritel dan produk konsumen,asisten ritel,3000000,3096823,tanggung jawab urus registrasi balas whatsapp ...
14,administrasi spv sa,supervisor,golden brilliant sanitaryware,"ritel dan produk konsumen, asisten ritel",jawa barat,80185299,full time,rp 3.500.000 - rp 4.500.000 per month,https:atauatauid.jobstreet.comataujobatau80185299,pt. golden brilliant sanitaryware (germany bri...,ritel dan produk konsumen,asisten ritel,3500000,4500000,pt golden brilliant sanitaryware germany brill...
15,dokter kecantikan estetika,beauty doctor,skn atelier,"kesehatan dan medis, dokter umum",banten,79645796,full time,rp 11.500.000 - rp 15.000.000 per month,https:atauatauid.jobstreet.comataujobatau79645796,kualifikasi : pendidikan profesi dokter (s1) m...,kesehatan dan medis,dokter umum,11500000,15000000,kualifikasi didik profesi dokter s milik str a...
16,deputy sales manager,sales manager,iconic talent indonesia,"penjualan, manajemen",jawa barat,79993623,full time,rp 23.500.000 - rp 26.500.000 per month,https:atauatauid.jobstreet.comataujobatau79993623,responsibilities or job desc • implementation ...,penjualan,manajemen,23500000,26500000,responsibility or job desc implementation of a...
17,production line leader mandarin speaker,production line leader,cfu technology indonesia,"manufaktur, transportasi dan logistik, pemimpi...",jawa barat,79657626,kontrak,rp 5.500.000 - rp 6.500.000 per month,https:atauatauid.jobstreet.comataujobatau79657626,1.running day to day productionactivity in goo...,manufaktur,transportasi dan logistik,5500000,6500000,running day to day productionactivity in good ...
18,videographer,videographer,putra perkasa,"periklanan, seni dan media, fotografi",jawa timur,79695850,full time,"rp 5,000,000 - rp 5,500,000 per month",https:atauatauid.jobstreet.comataujobatau79695850,triv adalah salah satu bursa kripto terbesar d...,periklanan,seni dan media,5000000,5500000,triv adalah salah satu bursa kripto besar dan ...
19,analis lab plating qc staff,laboratory analyst,nichias metalworks indonesia,"sains dan teknologi, jasa laboratorium dan teknis",jawa barat,80061013,full time,rp 7.000.000 - rp 8.000.000 per month,https:atauatauid.jobstreet.comataujobatau80061013,tugas dan tanggung jawab : melakukan analisa s...,sains dan teknologi,jasa laboratorium dan teknis,7000000,8000000,tugas dan tanggung jawab laku analisa cara kim...
20,sales project,sales,shinmado,"penjualan, perwakilanataukonsultan penjualan",jakarta raya,79517441,full time,rp 5.000.000 - rp 7.000.000 per month,https:atauatauid.jobstreet.comataujobatau79517441,job description qualifications: at least 2-3 y...,penjualan,perwakilanataukonsultan penjualan,5000000,7000000,job description qualification at least year of...
21,fullstack developer,full stack developer,koffiesoft group,"teknologi informasi dan komunikasi, developera...",jawa timur,80161629,full time,rp 4.500.000 - rp 6.750.000 per month,https:atauatauid.jobstreet.comataujobatau80161629,• berpengalaman minimal 3 tahun menggunakan ph...,teknologi informasi dan komunikasi,developeratauprogrammer,4500000,6750000,alam minimal tahun guna php html cs javascript...
22,customer service japanese speaker,customer service role,akazora usaha mandiri,"call center dan layanan konsumen, layanan kons...",jawa barat,80102855,full time,rp 5.200.000 - rp 5.500.000 per month,https:atauatauid.jobstreet.comataujobatau80102855,kualifikasi: usia minimal 23 tahun maksimal 40...,call center dan layanan konsumen,layanan konsumen – berhadapan dengan konsumen,5200000,5500000,kualifikasi usia minimal tahun maksimal tahun ...
23,sales marketing,marketing,cia aneka selera,"penjualan, pengembangan bisnis baru",jawa barat,79760681,full time,"rp 5,500,000 - rp 6,200,000 per month",https:atauatauid.jobstreet.comataujobatau79760681,kualfikasi : bertanggung jawab pendidikan mini...,penjualan,pengembangan bisnis baru,5500000,6200000,kualfikasi tanggung jawab didik minimal dataus...
24,bancassurance specialist jakarta kemayoran,bancassurance specialist,bni life insurance,"penjualan, perwakilanataukonsultan penjualan",jakarta raya,80093228,full time,"rp 2,000,000 - rp 3,000,000 per month",https:atauatauid.jobstreet.comataujobatau80093228,bancassurance specialist (bas) representative ...,penjualan,perwakilanataukonsultan penjualan,2000000,3000000,bancassurance specialist ba representative bni...
25,sales marketing,marketing,ruang sukses indonesia,"penjualan, perwakilanataukonsultan penjualan",jakarta raya,79854347,full time,rp 3.500.000 - rp 4.500.000 per month,https:atauatauid.jobstreet.comataujobatau79854347,ruangpedia sedang mencari tenaga profesional s...,penjualan,perwakilanataukonsultan penjualan,3500000,4500000,ruangpedia sedang cari tenaga profesional sale...
26,security manager area pekanbaru,security manager,sigap prima astrea,"keterampilan dan jasa, jasa keamanan",riau,79676318,full time,"rp 6,500,000 - rp 7,000,000 per month",https:atauatauid.jobstreet.comataujobatau79676318,kualifikasi: pendidikan s1 segala jurusan deng...,keterampilan dan jasa,jasa keamanan,6500000,7000000,kualifikasi didik s segala jurus dengan alam b...
27,account manager,account manager,yuxi jayatama indonesia,"periklanan, seni dan media, manajemen akun agensi",jakarta raya,79720509,full time,rp 7.500.000 - rp 11.000.000 per month,https:atauatauid.jobstreet.comataujobatau79720509,about us : yuxi jayatama is an multi-channel n...,periklanan,seni dan media,7500000,11000000,about u yuxi jayatama is an multichannel netwo...
28,recruitment officer,recruitment officer,bimasakti multi sinergi,"sumber daya manusia dan perekrutan, perekrutan...",jawa timur,79946300,full time,rp 4.500.000 - rp 5.000.000 per month,https:atauatauid.jobstreet.comataujobatau79946300,"manage sourcing for multiple, complex searches...",sumber daya manusia dan perekrutan,perekrutan – internal,4500000,5000000,manage sourcing for multiple complex search to...
29,driver bluebird bekasi,driver,morante jaya tbk bekasi,"manufaktur, transportasi dan logistik, transpo...",jawa barat,80003440,full time,rp 4.500.000 - rp 6.500.000 per month,https:atauatauid.jobstreet.comataujobatau80003440,perusahaan jasa transportasi terbaik di indone...,manufaktur,transportasi dan logistik,4500000,6500000,usaha jasa transportasi baik di indonesia pt b...
30,export import manager,export import manager,elit solusi niaga,"manufaktur, transportasi dan logistik, imporat...",jakarta raya,79705035,full time,rp 20.000.000 - rp 25.000.000 per month,https:atauatauid.jobstreet.comataujobatau79705035,qualifications bachelor’s degreeataumaster deg...,manufaktur,transportasi dan logistik,20000000,25000000,qualification bachelor degreeataumaster degree...

In [151]:
df['cleaned_description'].replace(r'^\s*$', np.nan, regex=True, inplace=True)
df['cleaned_description'].isnull().sum()

C:\Users\USER\AppData\Local\Temp\ipykernel_24436\3290518362.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['cleaned_description'].replace(r'^\s*$', np.nan, regex=True, inplace=True)

3

In [152]:
df.shape

(6076, 15)

In [153]:
df.dropna(subset='cleaned_description', inplace=True)

In [154]:
df.shape

(6073, 15)

In [156]:
df.head(1)

,title,role,company_name,category,location,jobId,type,salary,url,description,category_1,category_2,salary_min,salary_max,cleaned_description
0,penerjemah bahasa mandarinasisten manajer umum,mandarin translator,onemate aksesoris mobil,"administrasi dan dukungan perkantoran, asisten...",banten,79976110,full time,rp 8.500.000 - rp 12.500.000 per month,https:atauatauid.jobstreet.comataujobatau79976110,asisten manajer umum: • membantu manajer umum ...,administrasi dan dukungan perkantoran,asisten administratif,8500000,12500000,asisten manajer umum bantu manajer umum dalam ...

In [ ]:
df = df.drop(columns='description')

In [161]:
df = df.drop(columns='salary')

In [164]:
df = df.drop(columns='category')

In [165]:
df.head(1)

,title,role,company_name,location,jobId,type,url,category_1,category_2,salary_min,salary_max,cleaned_description
0,penerjemah bahasa mandarinasisten manajer umum,mandarin translator,onemate aksesoris mobil,banten,79976110,full time,https:atauatauid.jobstreet.comataujobatau79976110,administrasi dan dukungan perkantoran,asisten administratif,8500000,12500000,asisten manajer umum bantu manajer umum dalam ...

In [3]:
df_for_remove_stopwords = pd.read_csv("D:\ds tools\data_cleaned_100%.csv")
df_for_remove_stopwords.head()

,Unnamed: 0,title,role,company_name,location,jobId,type,url,category_1,category_2,salary_min,salary_max,cleaned_description
0,0,penerjemah bahasa mandarinasisten manajer umum,mandarin translator,onemate aksesoris mobil,banten,79976110,full time,https:atauatauid.jobstreet.comataujobatau79976110,administrasi dan dukungan perkantoran,asisten administratif,8500000,12500000,asisten manajer umum bantu manajer umum dalam ...
1,1,it business analyst,information technology business analyst,nextalent talenta nusantara,jakarta raya,80187093,full time,https:atauatauid.jobstreet.comataujobatau80187093,teknologi informasi dan komunikasi,analis bisnisatausistem,10000000,14000000,qualification candidate must posse at least di...
2,3,sales executive,sales executive,laxmi utama,jawa timur,79645321,full time,https:atauatauid.jobstreet.comataujobatau79645321,ritel dan produk konsumen,asisten ritel,6000000,9000000,a retail garment sale executive play a vital r...
3,4,site project staff,project staff,vnv mandiri valve,jawa barat,79912142,kontrak,https:atauatauid.jobstreet.comataujobatau79912142,konstruksi,manajemen proyek,4500000,5500000,urai tugas susun rencana proyek masuk jadwal d...
4,5,kepala sipil struktur engineering,engineering,renon property emporio architect,jakarta raya,80181996,full time,https:atauatauid.jobstreet.comataujobatau80181996,teknik,teknik sipilataustruktural,8000000,8100000,kami emporio architect firma arsitektur yang g...

In [4]:
# Mengambil daftar stopwords Bahasa Indonesia
factory = StopWordRemoverFactory()
stopwords_indo = set(factory.get_stop_words())

In [5]:
# Mengambil daftar stopwords Bahasa Inggris
stopwords_en = set(stopwords.words('english'))

In [6]:
# Menggabungkan stopword Bahasa Indonesia dan Inggris
stopwords_combined = stopwords_indo.union(stopwords_en)

In [8]:
def remove_stopwords(text):
    words = word_tokenize(text)  # Tokenisasi kata
    filtered_words = [word for word in words if word not in stopwords_combined]
    return ' '.join(filtered_words)

In [11]:
df_for_remove_stopwords['cleaned_description'] = df_for_remove_stopwords['cleaned_description'].fillna('').astype(str)

In [12]:
df_for_remove_stopwords['cleaned_description'].isnull().sum()

0

In [13]:
df_for_remove_stopwords['cleaned_description_with_stopwordremove'] = df_for_remove_stopwords['cleaned_description'].apply(lambda x: remove_stopwords(clean_text(x)))

In [14]:
print(df_for_remove_stopwords[['cleaned_description', 'cleaned_description_with_stopwordremove']])

                                    cleaned_description  \
0     asisten manajer umum bantu manajer umum dalam ...
1     qualification candidate must posse at least di...
2     a retail garment sale executive play a vital r...
3     urai tugas susun rencana proyek masuk jadwal d...
4     kami emporio architect firma arsitektur yang g...
...                                                 ...
6068  pt era manunggal sejahtera rupa usaha yang ger...
6069  jobdesc pasti performa cabang dalam capai omse...
6070  requirement didik minimal s utama jurus psikol...
6071  responsibility oversee all financial operation...
6072  job description maintain permit process with r...

                cleaned_description_with_stopwordremove
0     asisten manajer umum bantu manajer umum tangan...
1     qualification candidate must posse least diplo...
2     retail garment sale executive play vital role ...
3     urai tugas susun rencana proyek masuk jadwal a...
4     emporio architect firma arsitektur gerak jasa ...
...                                                 ...
6068  pt era manunggal sejahtera rupa usaha gerak bi...
6069  jobdesc performa cabang capai omset sesuai tar...
6070  requirement didik minimal utama jurus psikolog...
6071  responsibility oversee financial operation inc...
6072  job description maintain permit process rwatau...

[6073 rows x 2 columns]

In [15]:
df_for_remove_stopwords.head(1)

,Unnamed: 0,title,role,company_name,location,jobId,type,url,category_1,category_2,salary_min,salary_max,cleaned_description,cleaned_description_with_stopwordremove
0,0,penerjemah bahasa mandarinasisten manajer umum,mandarin translator,onemate aksesoris mobil,banten,79976110,full time,https:atauatauid.jobstreet.comataujobatau79976110,administrasi dan dukungan perkantoran,asisten administratif,8500000,12500000,asisten manajer umum bantu manajer umum dalam ...,asisten manajer umum bantu manajer umum tangan...

In [16]:
df_for_remove_stopwords.drop(columns='Unnamed: 0', inplace=True)

In [17]:
df_for_remove_stopwords.head(1)

,title,role,company_name,location,jobId,type,url,category_1,category_2,salary_min,salary_max,cleaned_description,cleaned_description_with_stopwordremove
0,penerjemah bahasa mandarinasisten manajer umum,mandarin translator,onemate aksesoris mobil,banten,79976110,full time,https:atauatauid.jobstreet.comataujobatau79976110,administrasi dan dukungan perkantoran,asisten administratif,8500000,12500000,asisten manajer umum bantu manajer umum dalam ...,asisten manajer umum bantu manajer umum tangan...

In [18]:
df_for_remove_stopwords.to_csv('data_cleaned_100%_with_stopwordremove.csv')

# Type

In [167]:
df['type'].unique()

array(['full time', 'kontrak', 'paruh waktu', 'kasual'], dtype=object)

In [168]:
df['type'].replace(r'^\s*$', np.nan, regex=True, inplace=True)
df['type'].isnull().sum()

0

In [169]:
df.to_csv('data_cleaned_100%.csv')